// T16c restoration tests, anchored to REAL Contract C5 producer workbooks.
//
// The fixtures under `__fixtures__/c5/` are generated by the actual backend
// exporter (openpyxl via `nurse_scheduling.exporter`; see
// `generate-c5-goldens.py`), so these tests exercise the true OOXML the frontend
// downloads — prettify styles, history columns, frozen panes, and a Notes sheet
// with hyperlinks — not a synthetic ExcelJS round-trip.
//
// Preservation is proven two independent ways, neither relying on the module's
// own value reassignment:
//   1. the schedule sheet is re-read with a SECOND ExcelJS instance and only
//      the column-A people cells differ in value, with styles and types intact;
//   2. an openpyxl semantic diff (a different library, a different parse) —
//      gated on a Python with openpyxl — confirms the same thing across the
//      whole workbook, including the Notes sheet, freeze panes, and any styles.

import { execFileSync, spawnSync } from "node:child_process";
import { readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import ExcelJS from "exceljs";
import { describe, expect, it } from "vitest";

import type { PeopleReverseMap } from "@/lib/scenario";

import {
  RESTORED_XLSX_MIME_TYPE,
  XlsxRestorationError,
  applyPeopleIdRestoration,
  restorePeopleIdsInXlsx,
} from "./restore-people-ids-in-xlsx";

const FIXTURES_DIR = join(dirname(fileURLToPath(import.meta.url)), "__fixtures__", "c5");

interface FixtureMeta {
  file: string;
  peopleCount: number;
  columnAIds: string[];
  prettify: boolean;
}

const MANIFEST: Record<string, FixtureMeta> = JSON.parse(
  readFileSync(join(FIXTURES_DIR, "manifest.json"), "utf-8"),
);

function fixtureBytes(file: string): Uint8Array {
  return new Uint8Array(readFileSync(join(FIXTURES_DIR, file)));
}

function fixtureBlob(file: string): Blob {
  return new Blob([fixtureBytes(file) as BlobPart], { type: RESTORED_XLSX_MIME_TYPE });
}

async function blobBytes(blob: Blob): Promise<Uint8Array> {
  return new Uint8Array(await blob.arrayBuffer());
}

/** Distinct originals covering string, numeric, and Unicode restore paths. */
const ORIGINALS: ReadonlyArray<string | number> = ["alice", 202, "田中太郎", "Ærøskøbing"];

function buildReverseMap(meta: FixtureMeta): PeopleReverseMap {
  return meta.columnAIds.map((anon, i) => [
    anon,
    ORIGINALS[i % ORIGINALS.length],
  ]) as PeopleReverseMap;
}

/** Re-open a workbook with a fresh ExcelJS instance for independent inspection. */
async function readRestored(blob: Blob): Promise<ExcelJS.Workbook> {
  const wb = new ExcelJS.Workbook();
  await wb.xlsx.load((await blob.arrayBuffer()) as unknown as ArrayBuffer);
  return wb;
}

// --- Optional independent openpyxl semantic diff --------------------------------

const DIFF_PYTHON = detectDiffPython();

function detectDiffPython(): string | null {
  for (const candidate of [process.env.XLSX_DIFF_PYTHON, "python3", "python"]) {
    if (!candidate) continue;
    const probe = spawnSync(candidate, ["-c", "import openpyxl"], { encoding: "utf-8" });
    if (probe.status === 0) return candidate;
  }
  return null;
}

interface SemanticDiffEntry {
  kind: string;
  sheet?: string;
  coord?: string;
}

function semanticDiff(
  originalPath: string,
  restored: Uint8Array,
  label: string,
): SemanticDiffEntry[] {
  const tmp = join(FIXTURES_DIR, `.restored.${label}.tmp.xlsx`);
  writeFileSync(tmp, restored);
  try {
    const out = execFileSync(
      DIFF_PYTHON as string,
      [join(FIXTURES_DIR, "xlsx-semantic-diff.py"), join(FIXTURES_DIR, originalPath), tmp],
      { encoding: "utf-8" },
    );
    return (JSON.parse(out).diffs as SemanticDiffEntry[]) ?? [];
  } finally {
    rmSync(tmp, { force: true });
  }
}

// Re-open a fixture, mutate it in-memory with ExcelJS, and re-serialize — used
// to build tampered inputs for fail-closed tests without touching raw XML.
async function tamperedFixture(
  file: string,
  mutate: (sheet: ExcelJS.Worksheet, workbook: ExcelJS.Workbook) => void,
): Promise<Blob> {
  const wb = new ExcelJS.Workbook();
  await wb.xlsx.load(fixtureBytes(file) as unknown as ArrayBuffer);
  mutate(wb.worksheets[0], wb);
  const buffer = await wb.xlsx.writeBuffer();
  return new Blob([buffer as BlobPart], { type: RESTORED_XLSX_MIME_TYPE });
}

// ------------------------------------------------------------------------------

describe("restorePeopleIdsInXlsx — real C5 producer workbooks", () => {
  for (const [key, meta] of Object.entries(MANIFEST)) {
    describe(`fixture: ${key}`, () => {
      const map = buildReverseMap(meta);

      it("restores column A, returns the C5 MIME, and does not mutate the input blob", async () => {
        const originalBlob = fixtureBlob(meta.file);
        const originalBytes = await blobBytes(originalBlob);

        const restored = await restorePeopleIdsInXlsx(originalBlob, map, meta.peopleCount);

        expect(restored.type).toBe(RESTORED_XLSX_MIME_TYPE);
        // Input blob is untouched: the test does not rely on ExcelJS being
        // copy-not-mutate, it confirms it.
        expect(Buffer.from(await blobBytes(originalBlob))).toEqual(Buffer.from(originalBytes));

        const restoredSheet = (await readRestored(restored)).worksheets[0];
        for (let i = 0; i < meta.columnAIds.length; i += 1) {
          const row = 3 + i;
          const value = restoredSheet.getCell(row, 1).value;
          const original = ORIGINALS[i % ORIGINALS.length];
          expect(value, `A${row} should hold the original id`).toBe(original);
        }
      });

      it("changes ONLY the column-A people cells (independent re-read with ExcelJS)", async () => {
        const originalSheet = (await readRestored(fixtureBlob(meta.file))).worksheets[0];
        const restoredSheet = (
          await readRestored(
            await restorePeopleIdsInXlsx(fixtureBlob(meta.file), map, meta.peopleCount),
          )
        ).worksheets[0];

        // Boundary labels survive at the same rows.
        const lastPeopleRow = 3 + meta.peopleCount - 1;
        expect(restoredSheet.getCell(lastPeopleRow + 1, 1).value).toBe("Score");
        expect(restoredSheet.getCell(lastPeopleRow + 2, 1).value).toBe("Status");

        // Walk a generous window of cells; every non-people cell must match the
        // original value, and every people cell must hold its mapped original.
        const rowCount = Math.max(originalSheet.rowCount, restoredSheet.rowCount);
        const colCount = Math.max(originalSheet.columnCount, restoredSheet.columnCount);
        for (let r = 1; r <= rowCount; r += 1) {
          for (let c = 1; c <= colCount; c += 1) {
            const before = originalSheet.getCell(r, c).value;
            const after = restoredSheet.getCell(r, c).value;
            if (r >= 3 && r <= lastPeopleRow && c === 1) {
              const expected = ORIGINALS[(r - 3) % ORIGINALS.length];
              expect(after, `people cell A${r}`).toBe(expected);
            } else {
              expect(after, `untouched cell at ${r},${c}`).toEqual(before);
            }
          }
        }
      });

      it("preserves people-cell style (font/numFmt) on every restored id", async () => {
        const originalSheet = (await readRestored(fixtureBlob(meta.file))).worksheets[0];
        const restoredSheet = (
          await readRestored(
            await restorePeopleIdsInXlsx(fixtureBlob(meta.file), map, meta.peopleCount),
          )
        ).worksheets[0];

        for (let i = 0; i < meta.columnAIds.length; i += 1) {
          const row = 3 + i;
          const before = originalSheet.getCell(row, 1);
          const after = restoredSheet.getCell(row, 1);
          expect(after.style.font?.name ?? null).toBe(before.style.font?.name ?? null);
          expect(after.style.font?.size ?? null).toBe(before.style.font?.size ?? null);
          expect(after.numFmt).toBe(before.numFmt);
        }
      });

      it("keeps every worksheet beyond the schedule sheet (Notes, etc.)", async () => {
        const originalWb = await readRestored(fixtureBlob(meta.file));
        const restoredWb = await readRestored(
          await restorePeopleIdsInXlsx(fixtureBlob(meta.file), map, meta.peopleCount),
        );
        expect(restoredWb.worksheets.map((w) => w.name)).toEqual(
          originalWb.worksheets.map((w) => w.name),
        );
      });

      it.runIf(DIFF_PYTHON !== null)(
        "openpyxl sees only the column-A people cells change (independent semantic diff)",
        async () => {
          const restored = await restorePeopleIdsInXlsx(
            fixtureBlob(meta.file),
            map,
            meta.peopleCount,
          );
          const diffs = semanticDiff(meta.file, await blobBytes(restored), key);
          const peopleCoords = new Set(meta.columnAIds.map((_, i) => `A${3 + i}`));

          for (const entry of diffs) {
            expect(
              entry.kind,
              `unexpected ${entry.kind} diff at ${entry.sheet}!${entry.coord}`,
            ).toBe("value");
            expect(
              peopleCoords.has(entry.coord ?? ""),
              `unexpected value change at ${entry.coord}`,
            ).toBe(true);
          }
          // Every people cell must actually have changed.
          const changed = new Set(diffs.map((d) => d.coord));
          for (const coord of peopleCoords) expect(changed.has(coord)).toBe(true);
        },
      );
    });
  }

  it("treats numeric and string originals as distinct types", async () => {
    const meta = MANIFEST["plain-3people"];
    // P1 -> number, P2 -> string that looks like a number, P3 -> unicode string.
    const map: PeopleReverseMap = [
      ["P1", 5],
      ["P2", "5"],
      ["P3", "Yuki"],
    ];
    const restored = await readRestored(
      await restorePeopleIdsInXlsx(fixtureBlob(meta.file), map, meta.peopleCount),
    );
    const sheet = restored.worksheets[0];
    expect(sheet.getCell(3, 1).value).toBe(5);
    expect(sheet.getCell(4, 1).value).toBe("5");
    expect(sheet.getCell(5, 1).value).toBe("Yuki");
  });
});

describe("restorePeopleIdsInXlsx — fail closed", () => {
  const plain = MANIFEST["plain-3people"];
  const validMap = () => plain.columnAIds.map((anon) => [anon, `orig-${anon}`]) as PeopleReverseMap;

  it("rejects a non-XLSX (non-zip) blob", async () => {
    const blob = new Blob([new Uint8Array([0, 1, 2, 3, 4]) as BlobPart], {
      type: RESTORED_XLSX_MIME_TYPE,
    });
    await expect(restorePeopleIdsInXlsx(blob, [["P1", "a"]], 1)).rejects.toThrow(
      XlsxRestorationError,
    );
  });

  it("rejects an invalid people count", async () => {
    await expect(restorePeopleIdsInXlsx(fixtureBlob(plain.file), validMap(), 0)).rejects.toThrow(
      XlsxRestorationError,
    );
    await expect(restorePeopleIdsInXlsx(fixtureBlob(plain.file), validMap(), -1)).rejects.toThrow(
      XlsxRestorationError,
    );
  });

  it("rejects a cardinality mismatch (validatePeopleReverseMap)", async () => {
    await expect(restorePeopleIdsInXlsx(fixtureBlob(plain.file), [["P1", "a"]], 3)).rejects.toThrow(
      XlsxRestorationError,
    );
  });

  it("rejects a corrupt reverse-map entry (validatePeopleReverseMap)", async () => {
    const corrupt = [
      ["P1", "a"],
      ["not-a-p-id", "b"],
      ["P3", "c"],
    ] as unknown as PeopleReverseMap;
    await expect(restorePeopleIdsInXlsx(fixtureBlob(plain.file), corrupt, 3)).rejects.toThrow(
      XlsxRestorationError,
    );
  });

  it("rejects a duplicate anonymized id in the map (validatePeopleReverseMap)", async () => {
    const dup = [
      ["P1", "a"],
      ["P1", "b"],
      ["P3", "c"],
    ] as unknown as PeopleReverseMap;
    await expect(restorePeopleIdsInXlsx(fixtureBlob(plain.file), dup, 3)).rejects.toThrow(
      XlsxRestorationError,
    );
  });

  it("rejects a duplicate typed original in the map (validatePeopleReverseMap)", async () => {
    // numeric 1 and string "1" must stay distinct; two strings "alice" must not.
    const dup = [
      ["P1", "alice"],
      ["P2", "alice"],
      ["P3", "bob"],
    ] as unknown as PeopleReverseMap;
    await expect(restorePeopleIdsInXlsx(fixtureBlob(plain.file), dup, 3)).rejects.toThrow(
      XlsxRestorationError,
    );
  });

  it("rejects when a people cell has no reverse-map entry (incomplete restoration)", async () => {
    const map: PeopleReverseMap = [
      ["P1", "a"],
      ["P9", "b"],
      ["P3", "c"],
    ];
    await expect(restorePeopleIdsInXlsx(fixtureBlob(plain.file), map, 3)).rejects.toThrow(
      XlsxRestorationError,
    );
  });

  it("rejects when peopleCount undershoots the boundary (Score/Status shifted)", async () => {
    await expect(
      restorePeopleIdsInXlsx(
        fixtureBlob(plain.file),
        [
          ["P1", "a"],
          ["P2", "b"],
        ],
        2,
      ),
    ).rejects.toThrow(XlsxRestorationError);
  });

  it("rejects when peopleCount overshoots the row count", async () => {
    await expect(
      restorePeopleIdsInXlsx(
        fixtureBlob(plain.file),
        [
          ["P1", "a"],
          ["P2", "b"],
          ["P3", "c"],
          ["P4", "d"],
          ["P5", "e"],
        ],
        5,
      ),
    ).rejects.toThrow(XlsxRestorationError);
  });

  it("rejects a tampered boundary (Score label rewritten)", async () => {
    const blob = await tamperedFixture(plain.file, (sheet) => {
      // Row 6, column 1 is the real `Score` label.
      sheet.getCell(6, 1).value = "Total";
    });
    await expect(restorePeopleIdsInXlsx(blob, validMap(), 3)).rejects.toThrow(XlsxRestorationError);
  });

  it("rejects a tampered people cell (P# rewritten to a non-id)", async () => {
    const blob = await tamperedFixture(plain.file, (sheet) => {
      sheet.getCell(3, 1).value = "alice@example";
    });
    await expect(restorePeopleIdsInXlsx(blob, validMap(), 3)).rejects.toThrow(XlsxRestorationError);
  });

  it("rejects a people cell whose value is numeric (non-string layout)", async () => {
    const blob = await tamperedFixture(plain.file, (sheet) => {
      sheet.getCell(3, 1).value = 7;
    });
    await expect(restorePeopleIdsInXlsx(blob, validMap(), 3)).rejects.toThrow(XlsxRestorationError);
  });

  it("rejects a populated A1 leading header (C5 leaves A1 blank)", async () => {
    const blob = await tamperedFixture(plain.file, (sheet) => {
      sheet.getCell(1, 1).value = "Person";
    });
    await expect(restorePeopleIdsInXlsx(blob, validMap(), 3)).rejects.toThrow(XlsxRestorationError);
  });

  it("rejects a populated A2 leading header (C5 leaves A2 blank)", async () => {
    const blob = await tamperedFixture(plain.file, (sheet) => {
      sheet.getCell(2, 1).value = "Day";
    });
    await expect(restorePeopleIdsInXlsx(blob, validMap(), 3)).rejects.toThrow(XlsxRestorationError);
  });

  it("rejects a schedule column whose row-1 date header is missing", async () => {
    const blob = await tamperedFixture(plain.file, (sheet) => {
      // Strip every row-1 date so no schedule column remains a real C5 column.
      for (let c = 1; c <= sheet.columnCount; c += 1) {
        sheet.getCell(1, c).value = null;
      }
    });
    await expect(restorePeopleIdsInXlsx(blob, validMap(), 3)).rejects.toThrow(XlsxRestorationError);
  });

  it("rejects a schedule column whose row-2 weekday header is missing", async () => {
    const blob = await tamperedFixture(plain.file, (sheet) => {
      // Strip every row-2 weekday so no schedule column remains a real C5 column.
      for (let c = 1; c <= sheet.columnCount; c += 1) {
        sheet.getCell(2, c).value = null;
      }
    });
    await expect(restorePeopleIdsInXlsx(blob, validMap(), 3)).rejects.toThrow(XlsxRestorationError);
  });

  it("rejects a changed freeze boundary (xSplit moved off column A)", async () => {
    const blob = await tamperedFixture(plain.file, (sheet) => {
      // Replace the frozen view outright — ExcelJS's view type narrows on
      // `state`, so mutating fields after a state change is a typing dead-end.
      sheet.views = [
        {
          ...sheet.views[0],
          state: "frozen",
          xSplit: 0,
          topLeftCell: "A3",
        } as ExcelJS.WorksheetView,
      ];
    });
    await expect(restorePeopleIdsInXlsx(blob, validMap(), 3)).rejects.toThrow(XlsxRestorationError);
  });

  it("rejects a changed freeze boundary (ySplit moved off row 2)", async () => {
    const blob = await tamperedFixture(plain.file, (sheet) => {
      sheet.views = [
        {
          ...sheet.views[0],
          state: "frozen",
          ySplit: 1,
          topLeftCell: "B2",
        } as ExcelJS.WorksheetView,
      ];
    });
    await expect(restorePeopleIdsInXlsx(blob, validMap(), 3)).rejects.toThrow(XlsxRestorationError);
  });

  it("rejects a missing freeze boundary (no worksheet views)", async () => {
    const blob = await tamperedFixture(plain.file, (sheet) => {
      sheet.views = [];
    });
    await expect(restorePeopleIdsInXlsx(blob, validMap(), 3)).rejects.toThrow(XlsxRestorationError);
  });

  it("rejects a non-frozen view at the same split (state !== 'frozen')", async () => {
    const blob = await tamperedFixture(plain.file, (sheet) => {
      sheet.views = [
        {
          ...sheet.views[0],
          state: "normal",
        } as ExcelJS.WorksheetView,
      ];
    });
    await expect(restorePeopleIdsInXlsx(blob, validMap(), 3)).rejects.toThrow(XlsxRestorationError);
  });
});

describe("applyPeopleIdRestoration — download bypass seam (T16e)", () => {
  const plain = MANIFEST["plain-3people"];

  it("bypasses restoration for a non-anonymized download (same blob, no parse)", async () => {
    const blob = fixtureBlob(plain.file);
    const result = await applyPeopleIdRestoration(blob, {
      anonymized: false,
      reverseMap: [],
      peopleCount: plain.peopleCount,
    });
    // Identity: the plain byte path is never parsed or re-serialized.
    expect(result).toBe(blob);
  });

  it("restores an anonymized download through the ExcelJS transform", async () => {
    const blob = fixtureBlob(plain.file);
    const result = await applyPeopleIdRestoration(blob, {
      anonymized: true,
      reverseMap: plain.columnAIds.map((anon) => [anon, `orig-${anon}`]) as PeopleReverseMap,
      peopleCount: plain.peopleCount,
    });
    expect(result).not.toBe(blob);
    const sheet = (await readRestored(result)).worksheets[0];
    expect(sheet.getCell(3, 1).value).toBe("orig-P1");
    expect(sheet.getCell(4, 1).value).toBe("orig-P2");
    expect(sheet.getCell(5, 1).value).toBe("orig-P3");
  });

  it("still fails closed on a malformed anonymized workbook", async () => {
    const blob = new Blob([new Uint8Array([9, 9, 9]) as BlobPart], {
      type: RESTORED_XLSX_MIME_TYPE,
    });
    await expect(
      applyPeopleIdRestoration(blob, {
        anonymized: true,
        reverseMap: [["P1", "a"]],
        peopleCount: 1,
      }),
    ).rejects.toThrow(XlsxRestorationError);
  });
});
