// F4 — the frozen v2 surface matrix.
//
// This module is the single, immutable inventory the foundation, all nine
// parallel route tickets (R1…R7) and G1 verify against. It is COMPLETE the
// moment F4 lands: seventeen rows — thirteen shipped product routes and four
// harness routes — each naming its ticket owner, canonical prototype,
// deterministic seed strategy, readiness descriptor, semantic checks, axe
// exceptions and immutable static file-owner set.
//
// Route tickets do NOT edit this file. They do not add rows, retune a seed,
// widen a file-owner set, or flip a flag; there is no migration ledger and no
// `test.skip`. Owner selection (see `v2-owner-selection.ts`) filters these rows
// BEFORE Playwright declares a test, so `pnpm test:e2e` at F4 registers only the
// foundation row and carries no hidden route debt. If a descriptor here turns
// out to be wrong, F4 is reopened and repaired serially — that cost is the point
// of freezing it, not an accident of it.
//
// Everything here is plain data with no Playwright runtime import, so the
// focused unit tests next door can exercise it in the node vitest environment.

// ---------------------------------------------------------------------------
// Owners
// ---------------------------------------------------------------------------

/** Every ticket that owns at least one row. R2a/R2b/R2c stay distinct values. */
export const V2_OWNERS = [
  "foundation",
  "R1",
  "R2a",
  "R2b",
  "R2c",
  "R3",
  "R4",
  "R5",
  "R6",
  "R7",
] as const;

export type V2Owner = (typeof V2_OWNERS)[number];

/** The accepted `V2_MATRIX_OWNER` / `V2_STYLE_OWNER` vocabulary. */
export const V2_SELECTORS = [...V2_OWNERS, "all"] as const;

export type V2Selector = (typeof V2_SELECTORS)[number];

// ---------------------------------------------------------------------------
// Seed and readiness vocabulary
// ---------------------------------------------------------------------------

/**
 * Named deterministic seed strategies. Every builder produces byte-stable
 * identifiers and dates (see `v2-seed.ts`) — no clock, no randomness, no
 * dependency on another row having run first.
 */
export const V2_SEED_KEYS = [
  /** Reset only. The row's surface needs no scenario data. */
  "empty",
  /** One roster week: range, staff + group, shift types + group, date group. */
  "roster-week",
  /** `roster-week` plus the guided-rule source constraints. */
  "roster-week-rules",
  /** `roster-week` plus one card of every constraint kind. */
  "roster-week-constraints",
  /** `roster-week` plus leave / request / off matrix cells. */
  "roster-week-requests",
  /** `roster-week` recorded as a current Workspace backup, then edited stale. */
  "roster-week-backup",
  /** The minimum required data that enables an Optimize run. */
  "optimize-ready",
  /** Reset only: the harness page seeds its own deterministic state. */
  "harness-self-seeded",
] as const;

export type V2SeedKey = (typeof V2_SEED_KEYS)[number];

/**
 * Named readiness strategies. `app-shell` waits out the real T04 hydration
 * lifecycle behind `HydrationGate`; `bare` is for the routes that render outside
 * the `(app)` group and therefore have no gate to wait on. Both then wait for
 * the row's own marker, `document.fonts.ready`, settled portals and a stable
 * animation frame. A fixed sleep is never a correctness signal.
 */
export const V2_READINESS_STRATEGIES = ["app-shell", "bare"] as const;

export type V2ReadinessStrategy = (typeof V2_READINESS_STRATEGIES)[number];

/** The app-mode preference a direct visit must adopt before the validity gate runs. */
export type V2RouteMode = "guided" | "advanced" | null;

export interface V2ReadinessDescriptor {
  readonly strategy: V2ReadinessStrategy;
  /**
   * The row's EXISTING screen/fixture marker — a selector that already exists in
   * the shipped source today. F4 invents no new product markers.
   */
  readonly marker: string;
  /**
   * `advanced` for the DL12 §2 Advanced-only routes, whose direct visit would
   * otherwise be bounced to Home by `useRouteValidityGate` once the stored
   * preference adopts. `null` where the route carries no mode policy at all.
   */
  readonly mode: V2RouteMode;
  /** Whether the row needs the `window.__nsStore` seam (test-bridge.tsx). */
  readonly storeSeam: boolean;
}

// ---------------------------------------------------------------------------
// Semantic checks
// ---------------------------------------------------------------------------

/**
 * The closed surface-recipe vocabulary (v2 technical plan, "Surface recipe").
 * The runtime runner resolves each role to its expected tone token and elevation
 * through `V2_ROLE_CONTRACT` below, so a row declares the ROLE it means rather
 * than restating a token — the same indirection the recipe itself uses.
 */
export const V2_SURFACE_ROLES = [
  "page",
  "surface",
  "selected",
  "drop-target",
  "raised",
  "drawer",
  "well",
  "band",
  "zebra",
  "sticky",
] as const;

export type V2SurfaceRole = (typeof V2_SURFACE_ROLES)[number];

export interface V2RoleContract {
  /** The runtime tone variable the role's background must resolve to. */
  readonly tone: string;
  /** `outer` — a drop shadow; `inset` — an inset well; `none` — flat. */
  readonly elevation: "outer" | "inset" | "none";
}

/**
 * Role → tone/elevation, straight from the technical plan's recipe table. A well
 * never takes an outer shadow and a raised surface never takes an inset one
 * (DESIGN.md §4 rule 1), which is why elevation is part of the contract and not
 * a free choice of the consumer.
 */
export const V2_ROLE_CONTRACT: Readonly<Record<V2SurfaceRole, V2RoleContract>> = Object.freeze({
  page: { tone: "--bg", elevation: "none" },
  surface: { tone: "--surface", elevation: "outer" },
  selected: { tone: "--surface", elevation: "outer" },
  "drop-target": { tone: "--panel-alt", elevation: "outer" },
  raised: { tone: "--surface2", elevation: "outer" },
  drawer: { tone: "--sidebar", elevation: "outer" },
  well: { tone: "--panel", elevation: "inset" },
  band: { tone: "--panel", elevation: "none" },
  zebra: { tone: "--panel-alt", elevation: "none" },
  sticky: { tone: "--surface", elevation: "outer" },
});

/** Radius roles. `square` is the explicit data-surface treatment, not an absence. */
export const V2_RADIUS_ROLES = ["card", "control", "chip", "pill", "square"] as const;

export type V2RadiusRole = (typeof V2_RADIUS_ROLES)[number];

/** Role → the exact px Chromium must compute. Absolute; never multiplied by 0.9. */
export const V2_RADIUS_CONTRACT: Readonly<Record<V2RadiusRole, string>> = Object.freeze({
  card: "16px",
  control: "12px",
  chip: "9px",
  pill: "999px",
  square: "0px",
});

/**
 * One declared expectation about one selector. `role` and `radius` are
 * independently optional because they are independent contracts: DESIGN.md §5
 * is explicit that radius is NOT inferred from tone, so a specimen may pin its
 * geometry without claiming a surface role (the radius specimens are a plain
 * bordered box whose only contract is the corner) and a role may be pinned
 * without geometry (the owner chooses that). At least one must be present,
 * which `v2-surface-matrix.test.ts` asserts for every row.
 */
export interface V2SemanticCheck {
  /** Human label used verbatim in the failure diagnostic. */
  readonly label: string;
  /** A selector resolved inside the loaded route. */
  readonly selector: string;
  readonly role?: V2SurfaceRole;
  /** Declared only where geometry is part of THIS owner's contract. */
  readonly radius?: V2RadiusRole;
  /** The check must match at least this many elements (default 1). */
  readonly minCount?: number;
}

// ---------------------------------------------------------------------------
// Axe exceptions
// ---------------------------------------------------------------------------

/**
 * One rule, one exact element, one reason. There is deliberately no shape here
 * that can express "disable colour-contrast" or "exclude this route": an
 * exception names a single axe rule id AND a single selector, and the runner
 * filters violation NODES rather than switching the rule off, so any other node
 * that breaks the same rule still fails. G1 re-evaluates every entry.
 */
export interface V2AxeException {
  readonly rule: string;
  readonly selector: string;
  readonly reason: string;
}

// ---------------------------------------------------------------------------
// Rows
// ---------------------------------------------------------------------------

export interface V2Row {
  readonly route: string;
  readonly kind: "product" | "harness";
  readonly owner: V2Owner;
  /**
   * The canonical prototype screen this route is judged against (repo-relative),
   * or `HARNESS_NO_PROTOTYPE` for a test harness with no product prototype.
   */
  readonly prototype: string;
  readonly seed: V2SeedKey;
  readonly readiness: V2ReadinessDescriptor;
  readonly semanticChecks: readonly V2SemanticCheck[];
  readonly axeExceptions: readonly V2AxeException[];
}

/** The literal a harness row records instead of naming a prototype screen. */
export const HARNESS_NO_PROTOTYPE = "harness/no product prototype";

const PROTOTYPE_DIR = "docs/design_prototype/source";

/** The `(app)`-group screen marker every product route already renders today. */
const SCREEN_MARKER = '[data-testid="screen"]';

function appShell(marker: string, mode: Exclude<V2RouteMode, null>): V2ReadinessDescriptor {
  return Object.freeze({ strategy: "app-shell", marker, mode, storeSeam: true });
}

function bare(marker: string): V2ReadinessDescriptor {
  return Object.freeze({ strategy: "bare", marker, mode: null, storeSeam: false });
}

/**
 * The seventeen rows.
 *
 * Scope of `semanticChecks`: each row declares only what its OWN owner's
 * contract fixes today. The universal battery — No-Black, horizontal overflow,
 * coarse-pointer target size, axe AA, square data surfaces, scrim provenance and
 * status pairing — is applied by the shared runner to every registered row and
 * is deliberately NOT restated seventeen times here. Route-specific internals
 * beyond the declarations below belong in each ticket's own route-local spec,
 * which is the one file that ticket owns.
 */
const ROWS: readonly V2Row[] = [
  // --- foundation ---------------------------------------------------------
  {
    route: "/design-system",
    kind: "harness",
    owner: "foundation",
    prototype: HARNESS_NO_PROTOTYPE,
    seed: "empty",
    readiness: bare('[data-testid="palette"]'),
    // The nine surface-ladder specimens are the foundation's own contract, one
    // per recipe role, so this is the one row where every role is proven in a
    // real browser rather than declared. `drawer` has no specimen (it is the
    // mobile navigation plane, owned by R1's shell) and is deliberately absent.
    semanticChecks: [
      {
        label: "L0 page specimen",
        selector: '[data-testid="specimen-page"]',
        role: "page",
        radius: "square",
      },
      {
        label: "L1 surface specimen",
        selector: '[data-testid="specimen-surface"]',
        role: "surface",
        radius: "card",
      },
      {
        label: "L1 selected specimen",
        selector: '[data-testid="specimen-selected"]',
        role: "selected",
        radius: "card",
      },
      {
        label: "drop-target specimen",
        selector: '[data-testid="specimen-drop-target"]',
        role: "drop-target",
        radius: "card",
      },
      {
        label: "L2 raised specimen",
        selector: '[data-testid="specimen-raised"]',
        role: "raised",
        radius: "card",
      },
      {
        label: "inset well specimen",
        selector: '[data-testid="specimen-well"]',
        role: "well",
        radius: "control",
      },
      {
        label: "header band specimen",
        selector: '[data-testid="specimen-band"]',
        role: "band",
        radius: "square",
      },
      {
        label: "zebra specimen",
        selector: '[data-testid="specimen-zebra"]',
        role: "zebra",
        radius: "square",
      },
      {
        label: "sticky edge specimen",
        selector: '[data-testid="specimen-sticky"]',
        role: "sticky",
        radius: "square",
      },
      // Radius-only: these specimens are a plain bordered box whose entire
      // contract is the corner, so they pin geometry and claim no role.
      {
        label: "card radius role",
        selector: '[data-testid="radius-rounded-card"]',
        radius: "card",
      },
      {
        label: "control radius role",
        selector: '[data-testid="radius-rounded-control"]',
        radius: "control",
      },
      {
        label: "chip radius role",
        selector: '[data-testid="radius-rounded-chip"]',
        radius: "chip",
      },
      {
        label: "pill radius role",
        selector: '[data-testid="radius-rounded-pill"]',
        radius: "pill",
      },
      {
        label: "explicit square role",
        selector: '[data-testid="radius-rounded-none"]',
        radius: "square",
      },
      {
        label: "palette swatches stay square",
        selector: '[data-testid^="swatch-"] > div',
        radius: "square",
        minCount: 20,
      },
    ],
    axeExceptions: [],
  },

  // --- R1 — shell + Home --------------------------------------------------
  {
    route: "/",
    kind: "product",
    owner: "R1",
    prototype: `${PROTOTYPE_DIR}/ScreenHome.dc.html`,
    seed: "roster-week",
    readiness: appShell('[data-testid="home-screen"]', "guided"),
    semanticChecks: [
      { label: "Home screen root", selector: '[data-testid="home-screen"]', role: "page" },
    ],
    axeExceptions: [],
  },

  // --- R2a/R2b/R2c — setup editors ----------------------------------------
  {
    route: "/dates",
    kind: "product",
    owner: "R2a",
    prototype: `${PROTOTYPE_DIR}/ScreenDates.dc.html`,
    seed: "roster-week",
    readiness: appShell(SCREEN_MARKER, "guided"),
    semanticChecks: [{ label: "Dates screen root", selector: SCREEN_MARKER, role: "page" }],
    axeExceptions: [],
  },
  {
    route: "/people",
    kind: "product",
    owner: "R2b",
    prototype: `${PROTOTYPE_DIR}/ScreenStaff.dc.html`,
    seed: "roster-week",
    readiness: appShell(SCREEN_MARKER, "guided"),
    semanticChecks: [{ label: "Staff screen root", selector: SCREEN_MARKER, role: "page" }],
    axeExceptions: [],
  },
  {
    route: "/shift-types",
    kind: "product",
    owner: "R2c",
    prototype: `${PROTOTYPE_DIR}/ScreenShifts.dc.html`,
    seed: "roster-week",
    readiness: appShell(SCREEN_MARKER, "guided"),
    semanticChecks: [{ label: "Shifts screen root", selector: SCREEN_MARKER, role: "page" }],
    axeExceptions: [],
  },

  // --- R3 — guided rules ---------------------------------------------------
  {
    route: "/rules",
    kind: "product",
    owner: "R3",
    prototype: `${PROTOTYPE_DIR}/ScreenRules.dc.html`,
    seed: "roster-week-rules",
    readiness: appShell(SCREEN_MARKER, "guided"),
    semanticChecks: [{ label: "Rules screen root", selector: SCREEN_MARKER, role: "page" }],
    axeExceptions: [],
  },

  // --- R4 — the shared Card Editor family (Advanced-only, DL12 §2) ---------
  ...(
    [
      "/shift-type-requirements",
      "/shift-type-successions",
      "/shift-counts",
      "/shift-affinities",
      "/shift-type-coverings",
    ] as const
  ).map(
    (route): V2Row => ({
      route,
      kind: "product",
      owner: "R4",
      prototype: `${PROTOTYPE_DIR}/ScreenCards.dc.html`,
      seed: "roster-week-constraints",
      readiness: appShell(SCREEN_MARKER, "advanced"),
      semanticChecks: [
        { label: `${route} card-editor root`, selector: SCREEN_MARKER, role: "page" },
      ],
      axeExceptions: [],
    }),
  ),

  // --- R5 — requests -------------------------------------------------------
  {
    route: "/shift-requests",
    kind: "product",
    owner: "R5",
    prototype: `${PROTOTYPE_DIR}/ScreenRequests.dc.html`,
    seed: "roster-week-requests",
    readiness: appShell(SCREEN_MARKER, "guided"),
    semanticChecks: [{ label: "Requests screen root", selector: SCREEN_MARKER, role: "page" }],
    axeExceptions: [],
  },

  // --- R6 — Optimize & Export, plus its three harnesses --------------------
  {
    route: "/optimize-and-export",
    kind: "product",
    owner: "R6",
    prototype: `${PROTOTYPE_DIR}/ScreenGenerate.dc.html`,
    seed: "optimize-ready",
    readiness: appShell(SCREEN_MARKER, "guided"),
    semanticChecks: [{ label: "Optimize screen root", selector: SCREEN_MARKER, role: "page" }],
    axeExceptions: [],
  },
  {
    route: "/optimize-screen-fixture",
    kind: "harness",
    owner: "R6",
    prototype: HARNESS_NO_PROTOTYPE,
    seed: "harness-self-seeded",
    readiness: bare('[data-testid="optimize-fixture"]'),
    semanticChecks: [
      {
        label: "Optimize fixture root",
        selector: '[data-testid="optimize-fixture"]',
        role: "page",
      },
    ],
    axeExceptions: [],
  },
  {
    route: "/progress-chart-fixture",
    kind: "harness",
    owner: "R6",
    prototype: HARNESS_NO_PROTOTYPE,
    seed: "harness-self-seeded",
    readiness: bare('[data-testid="fixture-chart-host"]'),
    semanticChecks: [
      {
        label: "chart host is an L1 surface",
        selector: '[data-testid="fixture-chart-host"]',
        role: "surface",
      },
    ],
    axeExceptions: [],
  },
  {
    route: "/optimize-durable-fixture",
    kind: "harness",
    owner: "R6",
    prototype: HARNESS_NO_PROTOTYPE,
    seed: "harness-self-seeded",
    readiness: appShell('[data-testid="optimize-durable-fixture"]', "guided"),
    semanticChecks: [
      {
        label: "durable fixture root",
        selector: '[data-testid="optimize-durable-fixture"]',
        role: "page",
      },
    ],
    axeExceptions: [],
  },

  // --- R7 — save & load ----------------------------------------------------
  {
    route: "/save-and-load",
    kind: "product",
    owner: "R7",
    prototype: `${PROTOTYPE_DIR}/ScreenSaveLoad.dc.html`,
    seed: "roster-week-backup",
    readiness: appShell(SCREEN_MARKER, "guided"),
    semanticChecks: [{ label: "Save & Load screen root", selector: SCREEN_MARKER, role: "page" }],
    axeExceptions: [],
  },
];

/** The frozen manifest. Deep-frozen so a spec cannot mutate a row in place. */
export const V2_SURFACE_MATRIX: readonly V2Row[] = Object.freeze(
  ROWS.map((row) =>
    Object.freeze({
      ...row,
      readiness: Object.freeze({ ...row.readiness }),
      semanticChecks: Object.freeze(row.semanticChecks.map((c) => Object.freeze({ ...c }))),
      axeExceptions: Object.freeze(row.axeExceptions.map((e) => Object.freeze({ ...e }))),
    }),
  ),
);

/** The thirteen shipped product routes, in manifest order. */
export const V2_PRODUCT_ROUTES: readonly string[] = Object.freeze(
  V2_SURFACE_MATRIX.filter((r) => r.kind === "product").map((r) => r.route),
);

/** The four harness routes, in manifest order. */
export const V2_HARNESS_ROUTES: readonly string[] = Object.freeze(
  V2_SURFACE_MATRIX.filter((r) => r.kind === "harness").map((r) => r.route),
);

// ---------------------------------------------------------------------------
// Immutable static file ownership
// ---------------------------------------------------------------------------

/**
 * The presentation-bearing source each owner may author, as `web/`-relative glob
 * patterns. This is the set `V2_STYLE_OWNER` selects for the static provenance
 * scanner, and it is also the ownership map the parallel wave depends on: two
 * tickets that could both touch one file could both break it, and neither review
 * would see the other's change.
 *
 * The sets are exhaustive over the app's presentation sources and provably
 * disjoint — both properties are asserted in `v2-surface-matrix.test.ts` against
 * what is actually on disk, so a new component cannot be added without being
 * given an owner.
 */
export const V2_STYLE_OWNER_FILES: Readonly<Record<V2Owner, readonly string[]>> = Object.freeze({
  // The value authority plus every shared primitive, theme control and shared
  // entity-editor presenter migrated once by F1–F3 ahead of its route consumers.
  //
  // The entity-editor presenters are enumerated by FAMILY rather than swept with
  // `components/entity-editor/**/*.tsx`, because exactly one file in that
  // directory is NOT foundation-owned: `working-time-fields.tsx` belongs to R2c
  // (see the R2c entry below). The glob grammar here is deliberately tiny — `**`
  // and `*`, no negation — so an exception is expressed by naming what IS owned,
  // not by subtracting from a sweep. The consequence is intended: a NEW
  // entity-editor presenter matches no owner and fails the "every presentation
  // source has exactly one owner" gate until it is assigned, which is the
  // fail-closed behaviour this map exists for.
  foundation: Object.freeze([
    "app/globals.css",
    "app/layout.tsx",
    "app/providers.tsx",
    "app/design-system/page.tsx",
    "components/ui/**/*.tsx",
    "components/theme/**/*.tsx",
    "components/entity-editor/groups-section*.tsx",
    "components/entity-editor/transfer-list*.tsx",
    "components/icons.tsx",
    "components/app-version.tsx",
  ]),
  R1: Object.freeze([
    "app/(app)/layout.tsx",
    "app/(app)/page.tsx",
    "components/shell/**/*.tsx",
    "components/home/**/*.tsx",
  ]),
  // The FullCalendar override sheet is presentation-bearing CSS and belongs to
  // the Dates owner like the rest of that screen — it is the second stylesheet
  // in the app, and the only one outside the foundation.
  R2a: Object.freeze([
    "app/(app)/dates/page.tsx",
    "components/dates/**/*.tsx",
    "components/dates/calendar.css",
  ]),
  R2b: Object.freeze(["app/(app)/people/page.tsx", "components/people/**/*.tsx"]),
  // `working-time-fields` is the one entity-editor presenter that is NOT
  // foundation-owned. Shift Types is its only live UI consumer, so the R2c
  // ticket is authoritative that R2c is its sole visual owner — and the static
  // scan has to agree, or `V2_STYLE_OWNER=R2c` silently skips a file R2c
  // changed. Named as exact paths, never a `working-time-fields*` sweep: an
  // exception should not be able to widen itself.
  R2c: Object.freeze([
    "app/(app)/shift-types/page.tsx",
    "components/shift-types/**/*.tsx",
    "components/entity-editor/working-time-fields.tsx",
    "components/entity-editor/working-time-fields.test.tsx",
  ]),
  R3: Object.freeze(["app/(app)/rules/page.tsx", "components/guided-rules/**/*.tsx"]),
  R4: Object.freeze([
    "app/(app)/shift-type-requirements/page.tsx",
    "app/(app)/shift-type-successions/page.tsx",
    "app/(app)/shift-counts/page.tsx",
    "app/(app)/shift-affinities/page.tsx",
    "app/(app)/shift-type-coverings/page.tsx",
    "components/card-editor/**/*.tsx",
    "components/requirements/**/*.tsx",
    "components/successions/**/*.tsx",
    "components/counts/**/*.tsx",
    "components/affinities/**/*.tsx",
    "components/coverings/**/*.tsx",
  ]),
  R5: Object.freeze(["app/(app)/shift-requests/page.tsx", "components/requests/**/*.tsx"]),
  R6: Object.freeze([
    "app/(app)/optimize-and-export/page.tsx",
    "app/(app)/optimize-durable-fixture/**/*.tsx",
    "app/optimize-screen-fixture/**/*.tsx",
    "app/progress-chart-fixture/**/*.tsx",
    "components/optimize/**/*.tsx",
  ]),
  R7: Object.freeze(["app/(app)/save-and-load/page.tsx", "components/save-load/**/*.tsx"]),
});

// ---------------------------------------------------------------------------
// Lookups
// ---------------------------------------------------------------------------

/** Every row owned by `owner`. */
export function rowsForOwner(owner: V2Owner): readonly V2Row[] {
  return V2_SURFACE_MATRIX.filter((row) => row.owner === owner);
}

/** The row for an exact route, or undefined. Routes are unique across the matrix. */
export function rowForRoute(route: string): V2Row | undefined {
  return V2_SURFACE_MATRIX.find((row) => row.route === route);
}

/** A compact inventory string, used verbatim in configuration-failure messages. */
export function manifestInventory(): string {
  return V2_OWNERS.map(
    (owner) =>
      `${owner}: ${
        rowsForOwner(owner)
          .map((r) => r.route)
          .join(", ") || "(none)"
      }`,
  ).join(" | ");
}
