// Edited-XLSX patch tests (F5), anchored to REAL Contract C5 producer workbooks.
//
// The fixtures under `optimize/__fixtures__/c5/` are generated by the actual
// backend exporter (see `generate-c5-goldens.py`), so these tests patch genuine
// C5 OOXML — history columns, frozen panes, the Score/Status boundary, and a
// real Notes sheet with bidirectional hyperlinks — not a synthetic round-trip.
//
// Per the orchestrator's correction: the adversarial multi-notes / multi-cell
// matrix is built by loading the genuine `c5-notes-hyperlinks.xlsx` and ENRICHING
// its existing Notes sheet in-test (extra notes for one edited cell + another
// noted cell + matching hyperlinks), then feeding those bytes to the production
// patcher — real C5 structure, constructed adversarial input.

import { execFileSync, spawnSync } from "node:child_process";
import { readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import ExcelJS from "exceljs";
import { describe, expect, it } from "vitest";

import {
  buildEditedCellPatches,
  EditedXlsxError,
  patchFrozenXlsxWithEdits,
  tryPatchFrozenXlsxWithEdits,
} from "./edited-xlsx";
import { fixtureRosterDocument } from "./test-fixtures";
import type { RosterCoordinateMap, RosterEdit } from "./types";

const FIXTURES_DIR = join(
  dirname(fileURLToPath(import.meta.url)),
  "..",
  "optimize",
  "__fixtures__",
  "c5",
);

interface FixtureMeta {
  file: string;
  peopleCount: number;
  columnAIds: string[];
  prettify: boolean;
}

const MANIFEST: Record<string, FixtureMeta> = JSON.parse(
  readFileSync(join(FIXTURES_DIR, "manifest.json"), "utf-8"),
);

function fixtureBytes(file: string): Uint8Array {
  return new Uint8Array(readFileSync(join(FIXTURES_DIR, file)));
}

function fixtureBlob(file: string): Blob {
  return new Blob([fixtureBytes(file) as BlobPart], {
    type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  });
}

async function reRead(blob: Blob): Promise<ExcelJS.Workbook> {
  const wb = new ExcelJS.Workbook();
  await wb.xlsx.load((await blob.arrayBuffer()) as unknown as ArrayBuffer);
  return wb;
}

/**
 * The coordinate map the exporter produces for a C5 fixture. `historyCols` is the
 * global max history length when prettify is on (the generator gives P1 a single
 * history entry, so it is 1); the date columns follow the exact exporter formula
 * `leadingCols + historyCols + 1 + dateIdx`.
 */
function fixtureCoordinateMap(meta: FixtureMeta): RosterCoordinateMap {
  const historyCols = meta.prettify ? 1 : 0;
  const peopleRows = Array.from({ length: meta.peopleCount }, (_, i) => 3 + i);
  // The generator scenario always spans 3 dates.
  const dateColumns = Array.from({ length: 3 }, (_, i) => 1 + historyCols + 1 + i);
  return {
    peopleRows,
    dateColumns,
    firstPeopleRow: 3,
    leadingCols: 1,
    historyCols,
    prettify: meta.prettify,
  };
}

/** The provenance a roster document carries; values are not load-bearing here. */
function fixtureProvenance() {
  return {
    solverStatus: "OPTIMAL" as const,
    score: 9,
    solvedBaselineId: "abc123def456",
    appBuild: "0.0.0-test",
  };
}

// --- Optional independent openpyxl semantic diff --------------------------------

const DIFF_PYTHON = detectDiffPython();

function detectDiffPython(): string | null {
  for (const candidate of [process.env.XLSX_DIFF_PYTHON, "python3", "python"]) {
    if (!candidate) continue;
    const probe = spawnSync(candidate, ["-c", "import openpyxl"], { encoding: "utf-8" });
    if (probe.status === 0) return candidate;
  }
  return null;
}

interface SemanticDiffEntry {
  kind: string;
  sheet?: string;
  coord?: string;
}

function semanticDiff(
  originalBytes: Uint8Array,
  patched: Uint8Array,
  label: string,
): SemanticDiffEntry[] {
  const origTmp = join(FIXTURES_DIR, `.orig.${label}.tmp.xlsx`);
  const patchedTmp = join(FIXTURES_DIR, `.patched.${label}.tmp.xlsx`);
  writeFileSync(origTmp, originalBytes);
  writeFileSync(patchedTmp, patched);
  try {
    const out = execFileSync(
      DIFF_PYTHON as string,
      [join(FIXTURES_DIR, "xlsx-semantic-diff.py"), origTmp, patchedTmp],
      { encoding: "utf-8" },
    );
    return (JSON.parse(out).diffs as SemanticDiffEntry[]) ?? [];
  } finally {
    rmSync(origTmp, { force: true });
    rmSync(patchedTmp, { force: true });
  }
}

/**
 * Strip the dedicated provenance sheet from a patched workbook so the openpyxl
 * diff (which short-circuits on a sheetname mismatch) proceeds to cell-level
 * comparison. The provenance sheet's presence is asserted separately; this is
 * only for proving unedited schedule cells are byte-faithful.
 */
async function stripProvenanceSheet(patched: Uint8Array): Promise<Uint8Array> {
  const wb = new ExcelJS.Workbook();
  await wb.xlsx.load(patched as unknown as ArrayBuffer);
  const provenance = wb.worksheets.find((ws) => ws.name === "Roster provenance");
  if (provenance !== undefined) wb.removeWorksheet(provenance.id);
  const buffer = await wb.xlsx.writeBuffer();
  return new Uint8Array(buffer as ArrayBuffer);
}

// ------------------------------------------------------------------------------

describe("buildEditedCellPatches", () => {
  it("maps each edit to explicit 1-based worksheet coordinates", () => {
    const coordinateMap: RosterCoordinateMap = {
      peopleRows: [3, 4],
      dateColumns: [3, 4, 5, 6],
      firstPeopleRow: 3,
      leadingCols: 1,
      historyCols: 1,
      prettify: true,
    };
    const edits: RosterEdit[] = [
      { personIdx: 1, dateIdx: 0, day: { kind: "off" } },
      { personIdx: 0, dateIdx: 3, day: { kind: "shift", shiftId: "N" } },
    ];
    expect(buildEditedCellPatches(edits, coordinateMap)).toEqual([
      { row: 4, col: 3, day: { kind: "off" } },
      { row: 3, col: 6, day: { kind: "shift", shiftId: "N" } },
    ]);
  });
});

describe("patchFrozenXlsxWithEdits — no edits", () => {
  it("returns the frozen bytes unchanged without an ExcelJS round-trip", async () => {
    const blob = fixtureBlob("c5-prettify-history.xlsx");
    const result = await patchFrozenXlsxWithEdits({
      frozenXlsx: blob,
      edits: [],
      coordinateMap: fixtureCoordinateMap(MANIFEST["prettify-history"]),
      provenance: fixtureProvenance(),
    });
    // Same byte content: no re-serialization occurred.
    expect(new Uint8Array(await result.arrayBuffer())).toEqual(
      fixtureBytes("c5-prettify-history.xlsx"),
    );
  });
});

describe("patchFrozenXlsxWithEdits — real C5 plain workbook", () => {
  const meta = MANIFEST["plain-3people"];
  const coordinateMap = fixtureCoordinateMap(meta);

  it("patches the edited cell value (worked→worked) and leaves unedited cells untouched", async () => {
    // P1 (row 3), first date (col 2): "D" -> "N".
    const edits: RosterEdit[] = [
      { personIdx: 0, dateIdx: 0, day: { kind: "shift", shiftId: "N" } },
    ];
    const patched = await patchFrozenXlsxWithEdits({
      frozenXlsx: fixtureBlob(meta.file),
      edits,
      coordinateMap,
      provenance: fixtureProvenance(),
    });
    const wb = await reRead(patched);
    const sheet = wb.worksheets[0];
    expect(sheet.getCell(3, 2).value).toBe("N"); // edited
    expect(sheet.getCell(3, 3).value).toBe("D"); // unedited
    expect(sheet.getCell(4, 2).value).toBe("E"); // unedited other person
  });

  it("OFF edits write an empty string and Leave writes 'Leave'", async () => {
    const edits: RosterEdit[] = [
      { personIdx: 0, dateIdx: 1, day: { kind: "off" } },
      { personIdx: 1, dateIdx: 2, day: { kind: "leave" } },
    ];
    const patched = await patchFrozenXlsxWithEdits({
      frozenXlsx: fixtureBlob(meta.file),
      edits,
      coordinateMap,
      provenance: fixtureProvenance(),
    });
    const sheet = (await reRead(patched)).worksheets[0];
    expect(sheet.getCell(3, 3).value).toBe(""); // OFF -> ""
    expect(sheet.getCell(4, 4).value).toBe("Leave");
  });

  it("preserves the Score and Status rows exactly", async () => {
    const edits: RosterEdit[] = [
      { personIdx: 0, dateIdx: 0, day: { kind: "shift", shiftId: "N" } },
    ];
    const patched = await patchFrozenXlsxWithEdits({
      frozenXlsx: fixtureBlob(meta.file),
      edits,
      coordinateMap,
      provenance: fixtureProvenance(),
    });
    const sheet = (await reRead(patched)).worksheets[0];
    // Plain fixture: Score label A6, value B6; Status label A7, value B7.
    expect(sheet.getCell(6, 1).value).toBe("Score");
    expect(sheet.getCell(6, 2).value).toBe(9);
    expect(sheet.getCell(7, 1).value).toBe("Status");
    expect(sheet.getCell(7, 2).value).toBe("OPTIMAL");
  });
});

describe("patchFrozenXlsxWithEdits — real C5 prettify workbook (history columns)", () => {
  const meta = MANIFEST["prettify-history"];
  const coordinateMap = fixtureCoordinateMap(meta);

  it("patches the edited value and clears fill/font while preserving the border", async () => {
    // P1 (row 3), first date (col 3): "D" -> "N".
    const edits: RosterEdit[] = [
      { personIdx: 0, dateIdx: 0, day: { kind: "shift", shiftId: "N" } },
    ];
    const patched = await patchFrozenXlsxWithEdits({
      frozenXlsx: fixtureBlob(meta.file),
      edits,
      coordinateMap,
      provenance: fixtureProvenance(),
    });
    const sheet = (await reRead(patched)).worksheets[0];

    // Value patched.
    expect(sheet.getCell(3, 3).value).toBe("N");

    // Fill cleared to "none".
    expect(sheet.getCell(3, 3).fill).toMatchObject({ type: "pattern", pattern: "none" });

    // Font colour override stripped (structural name/size kept).
    const editedFont = sheet.getCell(3, 3).font;
    expect(editedFont?.color).toBeUndefined();
    expect(editedFont?.name).toBe("Calibri");

    // Border preserved wholesale (whatever it was, it is unchanged from the
    // unedited neighbour — both come from the same frozen Styler).
    const uneditedNeighbour = (await reRead(fixtureBlob(meta.file))).worksheets[0].getCell(
      3,
      3,
    ).border;
    expect(sheet.getCell(3, 3).border).toEqual(uneditedNeighbour);
  });

  // Gated on `DIFF_PYTHON`, not short-circuited inside the body (qq0.28.1). An absent
  // openpyxl is a reported SKIP here — mirroring `restore-people-ids-in-xlsx.test.ts` —
  // never a silent pass that would let this suite's requirement look satisfied on a host
  // that cannot run it.
  it.runIf(DIFF_PYTHON !== null)(
    "leaves every unedited cell and the Score/Status rows byte-faithful (openpyxl diff on the plain C5 workbook)",
    async () => {
      // The plain C5 fixture carries no prettify Styler styling, so the openpyxl
      // semantic diff has no ExcelJS round-trip style artifacts to wade through:
      // every diff is a genuine semantic change. We edit only B3 (P1, first date)
      // and assert the ONLY diff openpyxl sees anywhere is that one cell's value.
      const plain = MANIFEST["plain-3people"];
      const plainMap = fixtureCoordinateMap(plain);
      const edits: RosterEdit[] = [
        { personIdx: 0, dateIdx: 0, day: { kind: "shift", shiftId: "N" } },
      ];
      const patched = await patchFrozenXlsxWithEdits({
        frozenXlsx: fixtureBlob(plain.file),
        edits,
        coordinateMap: plainMap,
        provenance: fixtureProvenance(),
      });
      const patchedBytes = new Uint8Array(await patched.arrayBuffer());
      // Strip the provenance sheet so the diff compares schedule-sheet cells only.
      const stripped = await stripProvenanceSheet(patchedBytes);
      const diffs = semanticDiff(fixtureBytes(plain.file), stripped, "plain-edited");

      // The single expected diff: B3's value changed D→N. Nothing else — not the
      // Score/Status rows, not any other cell, not the sheet dimensions.
      expect(diffs).toHaveLength(1);
      expect(diffs[0]).toMatchObject({ kind: "value", sheet: "Sheet1", coord: "B3" });
    },
  );
});

// ------------------------------------------------------------------------------
// The adversarial Notes matrix: real C5 notes-hyperlinks workbook, ENRICHED
// in-test with multiple notes for one edited cell + another noted cell.
// ------------------------------------------------------------------------------

interface EnrichedNotes {
  blob: Blob;
  /** The schedule cell (A1) that has notes AND will be edited. */
  editedCell: { row: number; col: number; address: string };
  /** The schedule cell (A1) that has notes and will SURVIVE. */
  survivingCell: { row: number; col: number; address: string };
}

/**
 * Load the genuine `c5-notes-hyperlinks.xlsx` and enrich its Notes sheet: give the
 * existing noted cell (E3) a SECOND note, and add TWO notes for a second cell
 * (D3) that did not have any. This constructs the multi-notes / multi-cell
 * adversarial matrix on top of REAL C5 structure (real history columns, real
 * Score/Status boundary, real freeze panes, real Hyperlink style on the existing
 * note row).
 */
async function enrichNotesFixture(): Promise<EnrichedNotes> {
  const wb = new ExcelJS.Workbook();
  await wb.xlsx.load(fixtureBytes("c5-notes-hyperlinks.xlsx") as unknown as ArrayBuffer);
  const sheet = wb.worksheets[0];
  const notes = wb.worksheets.find((ws) => ws.name === "Notes");
  expect(notes).toBeDefined();
  if (notes === undefined) throw new Error("Notes sheet missing");

  const scheduleName = sheet.name.replace(/'/g, "''");
  const notesName = notes.name.replace(/'/g, "''");

  // The existing note is on E3 (row 3, col 5). Append a second note row for E3.
  notes.addRow([
    { text: "E3", hyperlink: `#'${scheduleName}'!E3` },
    "D",
    "Second note for the edited cell (enriched in-test).",
  ]);
  // The Hyperlink visual style is cosmetic; the TARGET on the value is what the
  // contract requires rebuilt, so it is not set on the enriched input.

  // Add TWO notes for D3 (row 3, col 4) — a cell with no notes originally.
  for (const noteText of [
    "First surviving note (enriched).",
    "Second surviving note (enriched).",
  ]) {
    notes.addRow([{ text: "D3", hyperlink: `#'${scheduleName}'!D3` }, "D", noteText]);
  }
  // Point D3 at its first note row (the first of the two we just added).
  const d3cell = sheet.getCell("D3");
  d3cell.value = { text: "D", hyperlink: `#'${notesName}'!A${notes.rowCount - 1}` };

  const buffer = await wb.xlsx.writeBuffer();
  return {
    blob: new Blob([buffer as BlobPart], {
      type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    }),
    editedCell: { row: 3, col: 5, address: "E3" },
    survivingCell: { row: 3, col: 4, address: "D3" },
  };
}

describe("patchFrozenXlsxWithEdits — adversarial Notes matrix on real C5 workbook", () => {
  const meta = MANIFEST["notes-hyperlinks"];
  const coordinateMap = fixtureCoordinateMap(meta);

  it("removes every Notes row for the edited cell and rebuilds surviving rows + hyperlinks", async () => {
    const enriched = await enrichNotesFixture();

    // Accepting control: verify the enriched workbook really carries 2 notes for
    // E3 (edited) and 2 for D3 (surviving) before patching.
    const before = (await reRead(enriched.blob)).worksheets.find((ws) => ws.name === "Notes");
    expect(before).toBeDefined();
    if (before === undefined) return;
    const beforeCoords = collectNoteCoordinates(before);
    expect(beforeCoords.filter((c) => c === "E3")).toHaveLength(2);
    expect(beforeCoords.filter((c) => c === "D3")).toHaveLength(2);

    // Edit E3 (personIdx 0, dateIdx 2 -> row 3, col 5). D3 is left unedited.
    const edits: RosterEdit[] = [
      { personIdx: 0, dateIdx: 2, day: { kind: "shift", shiftId: "N" } },
    ];
    const patched = await patchFrozenXlsxWithEdits({
      frozenXlsx: enriched.blob,
      edits,
      coordinateMap,
      provenance: fixtureProvenance(),
    });
    const wb = await reRead(patched);
    const sheet = wb.worksheets[0];
    const notes = wb.worksheets.find((ws) => ws.name === "Notes");

    // E3 value patched; its hyperlink into Notes is gone.
    const e3 = sheet.getCell(enriched.editedCell.row, enriched.editedCell.col);
    expect(e3.value).toBe("N");
    expect(getCellHyperlink(e3)).toBeUndefined();

    // D3 still carries a hyperlink into Notes, re-pointed at its rebuilt first row.
    const d3 = sheet.getCell(enriched.survivingCell.row, enriched.survivingCell.col);
    const d3Link = getCellHyperlink(d3);
    expect(d3Link).toMatch(/^#'Notes'!A\d+$/);

    // Notes sheet: NO rows for E3 remain; BOTH D3 rows survive, contiguously,
    // and their A-cells link back to D3. The header row is intact.
    expect(notes).toBeDefined();
    if (notes === undefined) return;
    const afterCoords = collectNoteCoordinates(notes);
    expect(afterCoords.filter((c) => c === "E3")).toHaveLength(0);
    expect(afterCoords.filter((c) => c === "D3")).toHaveLength(2);
    expect(notes.getCell(1, 1).value).toBe("Cell");
    expect(notes.getCell(1, 2).value).toBe("Schedule Value");
    expect(notes.getCell(1, 3).value).toBe("Note");

    // The surviving D3 group's first row address matches the schedule cell's
    // rebuilt hyperlink target (no dangling link).
    const d3FirstRow = afterCoords.indexOf("D3") + 2; // +1 header, +1 to 1-index the first D3
    expect(d3Link).toBe(`#'Notes'!A${d3FirstRow}`);

    // Every surviving note row's A-cell links back to the schedule cell.
    for (let r = 2; r <= notes.rowCount; r++) {
      const coord = noteCoordinate(notes.getCell(r, 1).value);
      const link = getCellHyperlink(notes.getCell(r, 1));
      expect(coord).toBe("D3");
      expect(link).toBe(`#'Sheet1'!D3`);
    }
  });

  it("preserves the genuine C5 Notes worksheet metadata (freeze, auto-filter, column widths)", async () => {
    // The genuine c5-notes-hyperlinks.xlsx carries freeze_panes=A2,
    // auto_filter=A1:C1, and column widths A=14/B=24/C=80. Editing a noted cell
    // must rebuild the Notes sheet WITHOUT dropping that metadata.
    const enriched = await enrichNotesFixture();

    // Accepting control: the enriched input really carries the freeze + filter.
    const before = (await reRead(enriched.blob)).worksheets.find((ws) => ws.name === "Notes");
    expect(before).toBeDefined();
    if (before === undefined) return;
    const beforeView = before.views[0] as Record<string, unknown> | undefined;
    expect(beforeView?.state).toBe("frozen");
    expect(beforeView?.topLeftCell).toBe("A2");
    expect(before.getColumn(1).width).toBe(14);
    expect(before.getColumn(2).width).toBe(24);
    expect(before.getColumn(3).width).toBe(80);

    // Edit E3 (a noted cell) so the Notes sheet is rebuilt.
    const edits: RosterEdit[] = [
      { personIdx: 0, dateIdx: 2, day: { kind: "shift", shiftId: "N" } },
    ];
    const patched = await patchFrozenXlsxWithEdits({
      frozenXlsx: enriched.blob,
      edits,
      coordinateMap,
      provenance: fixtureProvenance(),
    });
    const notes = (await reRead(patched)).worksheets.find((ws) => ws.name === "Notes");
    expect(notes).toBeDefined();
    if (notes === undefined) return;

    // The rebuilt Notes sheet preserves the freeze pane, the auto-filter range,
    // and the per-column widths — an edit does not degrade the Notes surface.
    const view = notes.views[0] as Record<string, unknown> | undefined;
    expect(view?.state).toBe("frozen");
    expect(view?.topLeftCell).toBe("A2");
    expect(notes.getColumn(1).width).toBe(14);
    expect(notes.getColumn(2).width).toBe(24);
    expect(notes.getColumn(3).width).toBe(80);
  });

  it("places provenance on a dedicated sheet and never relabels Score/Status", async () => {
    const enriched = await enrichNotesFixture();
    const edits: RosterEdit[] = [{ personIdx: 0, dateIdx: 2, day: { kind: "off" } }];
    const patched = await patchFrozenXlsxWithEdits({
      frozenXlsx: enriched.blob,
      edits,
      coordinateMap,
      provenance: fixtureProvenance(),
    });
    const wb = await reRead(patched);
    const sheet = wb.worksheets[0];

    // Score/Status labels intact on the schedule sheet (restoration boundary).
    expect(sheet.getCell(6, 1).value).toBe("Score");
    expect(sheet.getCell(7, 1).value).toBe("Status");

    // Dedicated provenance sheet exists and carries the "as solved" provenance.
    const provenance = wb.worksheets.find((ws) => ws.name === "Roster provenance");
    expect(provenance).toBeDefined();
    const rows = readSheetRows(provenance!);
    expect(rows.find((r) => r[0] === "Solver status (as solved)")?.[1]).toBe("OPTIMAL");
    expect(rows.find((r) => r[0] === "Solver score (as solved)")?.[1]).toBe(9);
    expect(rows.find((r) => r[0] === "Edited since solve")?.[1]).toBe("yes");
  });
});

describe("tryPatchFrozenXlsxWithEdits — failure handling", () => {
  it("returns a typed failure rather than throwing on an unparseable workbook", async () => {
    const result = await tryPatchFrozenXlsxWithEdits({
      frozenXlsx: new Blob(["not an xlsx"], { type: "application/octet-stream" }),
      edits: [{ personIdx: 0, dateIdx: 0, day: { kind: "off" } }],
      coordinateMap: fixtureCoordinateMap(MANIFEST["plain-3people"]),
      provenance: fixtureProvenance(),
    });
    expect(result.ok).toBe(false);
    if (!result.ok) {
      expect(result.reason).toMatch(/ExcelJS|could not be/i);
    }
  });

  it("exposes EditedXlsxError as the fail-closed type", () => {
    expect(new EditedXlsxError("x")).toBeInstanceOf(Error);
    expect(new EditedXlsxError("x").name).toBe("EditedXlsxError");
  });
});

// --- integration with the roster document fixture (in-memory edit → patch) -------

describe("patchFrozenXlsxWithEdits — roster document integration", () => {
  it("patches a document built from the F3 fixture's stand-in bytes without throwing", async () => {
    // The F3 fixture uses stand-in bytes (not a real workbook); with edits
    // present the patcher must fail closed cleanly rather than throw raw.
    const doc = await fixtureRosterDocument();
    const edits: RosterEdit[] = [{ personIdx: 0, dateIdx: 0, day: { kind: "off" } }];
    const result = await tryPatchFrozenXlsxWithEdits({
      frozenXlsx: doc.frozenXlsx,
      edits,
      coordinateMap: doc.coordinateMap,
      provenance: doc.provenance,
    });
    expect(result.ok).toBe(false);
  });
});

// ---------------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------------

function collectNoteCoordinates(notes: ExcelJS.Worksheet): string[] {
  const coords: string[] = [];
  for (let r = 2; r <= notes.rowCount; r++) {
    coords.push(noteCoordinate(notes.getCell(r, 1).value));
  }
  return coords;
}

function noteCoordinate(value: ExcelJS.CellValue): string {
  if (typeof value === "string") return value;
  if (value !== null && typeof value === "object" && !Array.isArray(value) && "text" in value) {
    return String((value as { text: unknown }).text);
  }
  return "?";
}

/** Read a cell's hyperlink whether ExcelJS folds it into the value or exposes it separately. */
function getCellHyperlink(cell: ExcelJS.Cell): string | undefined {
  const value = cell.value;
  if (
    value !== null &&
    typeof value === "object" &&
    !Array.isArray(value) &&
    "hyperlink" in value
  ) {
    const hl = (value as { hyperlink?: unknown }).hyperlink;
    return typeof hl === "string" ? hl : undefined;
  }
  const direct = (cell as unknown as { hyperlink?: unknown }).hyperlink;
  return typeof direct === "string" ? direct : undefined;
}

function readSheetRows(sheet: ExcelJS.Worksheet): ExcelJS.CellValue[][] {
  const rows: ExcelJS.CellValue[][] = [];
  for (let r = 1; r <= sheet.rowCount; r++) {
    const row: ExcelJS.CellValue[] = [];
    for (let c = 1; c <= sheet.columnCount; c++) row.push(sheet.getCell(r, c).value);
    rows.push(row);
  }
  return rows;
}
