/*
 * This file is part of Nurse Scheduling Project, see <https://github.com/j3soon/nurse-scheduling>.
 *
 * Copyright (C) 2023-2026 Johnson Sun
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

// This test is mostly AI generated.

import { render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { DataTable } from '@/components/DataTable';
import { useGroupTableColumns, useItemTableColumns } from '@/components/TableColumns';
import { Mode } from '@/constants/modes';
import { Group, Item } from '@/types/scheduling';

function ItemTableHarness({
  items,
  groups,
  onInlineEdit,
  onEdit,
  onDuplicate = vi.fn(),
  onDelete,
  itemsReadOnly = false,
  removeItemFromGroup = vi.fn(),
}: {
  items: Item[];
  groups: Group[];
  onInlineEdit: (id: string, isItem: boolean, field?: 'id' | 'description') => void;
  onEdit: (id: string) => void;
  onDuplicate?: (id: string) => void;
  onDelete: (id: string) => void;
  itemsReadOnly?: boolean;
  removeItemFromGroup?: (itemId: string, groupId: string) => void;
}) {
  const columns = useItemTableColumns({
    groups,
    mode: Mode.NORMAL,
    inlineEditingId: '',
    inlineEditingField: 'id',
    error: '',
    showIndexPrefix: true,
    onInlineSave: vi.fn(),
    onInlineCancel: vi.fn(),
    onInlineEdit,
    onEdit,
    onDuplicate,
    onDelete,
    removeItemFromGroup,
    itemsReadOnly,
  });

  return <DataTable title="Items" columns={columns} data={items} />;
}

function GroupTableHarness({
  groups,
  items,
  onInlineEdit,
  onEdit,
  onDuplicate = vi.fn(),
  onDelete,
  groupsReadOnly = false,
}: {
  groups: Group[];
  items: Item[];
  onInlineEdit: (id: string, isItem: boolean, field?: 'id' | 'description') => void;
  onEdit: (id: string) => void;
  onDuplicate?: (id: string) => void;
  onDelete: (id: string) => void;
  groupsReadOnly?: boolean;
}) {
  const columns = useGroupTableColumns({
    items,
    mode: Mode.NORMAL,
    inlineEditingId: '',
    inlineEditingField: 'id',
    error: '',
    showIndexPrefix: false,
    onInlineSave: vi.fn(),
    onInlineCancel: vi.fn(),
    onInlineEdit,
    onEdit,
    onDuplicate,
    onDelete,
    removeItemFromGroup: vi.fn(),
    groupsReadOnly,
  });

  return <DataTable title="Groups" columns={columns} data={groups} />;
}

describe('TableColumns', () => {
  it('triggers inline edit callback on double-clicking item ID', async () => {
    const user = userEvent.setup();
    const onInlineEdit = vi.fn();

    render(
      <ItemTableHarness
        items={[{ id: 'A', description: '' }]}
        groups={[]}
        onInlineEdit={onInlineEdit}
        onEdit={vi.fn()}
        onDelete={vi.fn()}
      />,
    );

    await user.dblClick(screen.getByText('1. A'));

    expect(onInlineEdit).toHaveBeenCalledWith('A', true, 'id');
  });

  it('triggers row action callbacks for edit, duplicate, and delete', async () => {
    const user = userEvent.setup();
    const onEdit = vi.fn();
    const onDuplicate = vi.fn();
    const onDelete = vi.fn();

    render(
      <ItemTableHarness
        items={[{ id: 'A', description: '' }]}
        groups={[]}
        onInlineEdit={vi.fn()}
        onEdit={onEdit}
        onDuplicate={onDuplicate}
        onDelete={onDelete}
      />,
    );

    await user.click(screen.getByRole('button', { name: /edit/i }));
    await user.click(screen.getByRole('button', { name: /duplicate/i }));
    await user.click(screen.getByRole('button', { name: /delete/i }));

    expect(onEdit).toHaveBeenCalledWith('A');
    expect(onDuplicate).toHaveBeenCalledWith('A');
    expect(onDelete).toHaveBeenCalledWith('A');
  });

  it('shows Auto label and hides actions for auto-generated items', () => {
    render(
      <ItemTableHarness
        items={[{ id: 'AUTO', description: '', isAutoGenerated: true }]}
        groups={[]}
        onInlineEdit={vi.fn()}
        onEdit={vi.fn()}
        onDelete={vi.fn()}
      />,
    );

    expect(screen.getByText('Auto')).toBeInTheDocument();
    expect(screen.queryByRole('button', { name: /edit/i })).not.toBeInTheDocument();
    expect(screen.queryByRole('button', { name: /duplicate/i })).not.toBeInTheDocument();
    expect(screen.queryByRole('button', { name: /delete/i })).not.toBeInTheDocument();
  });

  it('hides action column controls when items are read-only', () => {
    render(
      <ItemTableHarness
        items={[{ id: 'A', description: '' }]}
        groups={[]}
        onInlineEdit={vi.fn()}
        onEdit={vi.fn()}
        onDelete={vi.fn()}
        itemsReadOnly={true}
      />,
    );

    expect(screen.queryByRole('button', { name: /edit/i })).not.toBeInTheDocument();
    expect(screen.queryByRole('button', { name: /duplicate/i })).not.toBeInTheDocument();
    expect(screen.queryByRole('button', { name: /delete/i })).not.toBeInTheDocument();
  });

  it('logs and skips missing group member IDs in group member tags', () => {
    const errorSpy = vi.spyOn(console, 'error').mockImplementation(() => undefined);

    render(
      <GroupTableHarness
        groups={[{ id: 'G1', members: ['MISSING'], description: '' }]}
        items={[{ id: 'P1', description: '' }]}
        onInlineEdit={vi.fn()}
        onEdit={vi.fn()}
        onDelete={vi.fn()}
      />,
    );

    expect(errorSpy).toHaveBeenCalled();
    expect(screen.queryByText('MISSING')).not.toBeInTheDocument();
  });

  it('renders valid group member tags even when one referenced member is missing', () => {
    const errorSpy = vi.spyOn(console, 'error').mockImplementation(() => undefined);

    render(
      <GroupTableHarness
        groups={[{ id: 'G1', members: ['P1', 'MISSING'], description: '' }]}
        items={[{ id: 'P1', description: 'Primary nurse' }]}
        onInlineEdit={vi.fn()}
        onEdit={vi.fn()}
        onDelete={vi.fn()}
      />,
    );

    expect(screen.getByText('P1')).toBeInTheDocument();
    expect(screen.queryByText('MISSING')).not.toBeInTheDocument();
    expect(errorSpy).toHaveBeenCalled();
  });

  it('renders removable tags only for non-auto groups and calls remove callback', async () => {
    const user = userEvent.setup();
    const removeItemFromGroup = vi.fn();

    render(
      <ItemTableHarness
        items={[{ id: 'A', description: '' }]}
        groups={[
          { id: 'MANUAL_G', members: ['A'], description: '' },
          { id: 'AUTO_G', members: ['A'], description: '', isAutoGenerated: true },
        ]}
        onInlineEdit={vi.fn()}
        onEdit={vi.fn()}
        onDelete={vi.fn()}
        removeItemFromGroup={removeItemFromGroup}
      />,
    );

    await user.click(screen.getByTitle('Remove "MANUAL_G"'));

    expect(removeItemFromGroup).toHaveBeenCalledWith('A', 'MANUAL_G');
    expect(screen.queryByTitle('Remove "AUTO_G"')).not.toBeInTheDocument();
  });

  it('does not trigger inline edit callback for groups when groups are read-only', async () => {
    const user = userEvent.setup();
    const onInlineEdit = vi.fn();

    render(
      <GroupTableHarness
        groups={[{ id: 'G1', members: ['P1'], description: '' }]}
        items={[{ id: 'P1', description: '' }]}
        onInlineEdit={onInlineEdit}
        onEdit={vi.fn()}
        onDelete={vi.fn()}
        groupsReadOnly={true}
      />,
    );

    await user.dblClick(screen.getByText('G1'));
    expect(onInlineEdit).not.toHaveBeenCalled();
  });

  it('does not trigger inline edit callback for descriptions when read-only', async () => {
    const user = userEvent.setup();
    const onItemInlineEdit = vi.fn();
    const onGroupInlineEdit = vi.fn();

    render(
      <>
        <ItemTableHarness
          items={[{ id: 'A', description: 'Alpha' }]}
          groups={[]}
          onInlineEdit={onItemInlineEdit}
          onEdit={vi.fn()}
          onDelete={vi.fn()}
          itemsReadOnly={true}
        />
        <GroupTableHarness
          groups={[{ id: 'G1', members: ['A'], description: 'Group Alpha' }]}
          items={[{ id: 'A', description: 'Alpha' }]}
          onInlineEdit={onGroupInlineEdit}
          onEdit={vi.fn()}
          onDelete={vi.fn()}
          groupsReadOnly={true}
        />
      </>,
    );

    await user.dblClick(screen.getByText('Alpha'));
    await user.dblClick(screen.getByText('Group Alpha'));

    expect(onItemInlineEdit).not.toHaveBeenCalled();
    expect(onGroupInlineEdit).not.toHaveBeenCalled();
  });

  it('keeps auto-generated row controls hidden after rerender', () => {
    const { rerender } = render(
      <ItemTableHarness
        items={[{ id: 'AUTO', description: 'initial', isAutoGenerated: true }]}
        groups={[]}
        onInlineEdit={vi.fn()}
        onEdit={vi.fn()}
        onDelete={vi.fn()}
      />,
    );

    expect(screen.getByText('Auto')).toBeInTheDocument();
    expect(screen.queryByRole('button', { name: /edit/i })).not.toBeInTheDocument();
    expect(screen.queryByRole('button', { name: /delete/i })).not.toBeInTheDocument();

    rerender(
      <ItemTableHarness
        items={[{ id: 'AUTO', description: 'updated', isAutoGenerated: true }]}
        groups={[]}
        onInlineEdit={vi.fn()}
        onEdit={vi.fn()}
        onDelete={vi.fn()}
      />,
    );

    expect(screen.getByText('Auto')).toBeInTheDocument();
    expect(screen.queryByRole('button', { name: /edit/i })).not.toBeInTheDocument();
    expect(screen.queryByRole('button', { name: /delete/i })).not.toBeInTheDocument();
  });

  it('shows and hides overflow indicator based on members container overflow', async () => {
    const scrollHeightSpy = vi.spyOn(HTMLElement.prototype, 'scrollHeight', 'get');
    const clientHeightSpy = vi.spyOn(HTMLElement.prototype, 'clientHeight', 'get');

    scrollHeightSpy.mockReturnValue(200);
    clientHeightSpy.mockReturnValue(100);

    render(
      <ItemTableHarness
        items={[{ id: 'A', description: '' }]}
        groups={[
          { id: 'G1', members: ['A'], description: '' },
          { id: 'G2', members: ['A'], description: '' },
        ]}
        onInlineEdit={vi.fn()}
        onEdit={vi.fn()}
        onDelete={vi.fn()}
      />,
    );

    expect(screen.getByTitle('Scroll for more')).toBeInTheDocument();

    scrollHeightSpy.mockReturnValue(80);
    clientHeightSpy.mockReturnValue(100);
    window.dispatchEvent(new Event('resize'));

    await waitFor(() => {
      expect(screen.queryByTitle('Scroll for more')).not.toBeInTheDocument();
    });
  });

  it('removes the correct remaining group after rerender shrinks the membership list', async () => {
    const user = userEvent.setup();
    const removeItemFromGroup = vi.fn();
    const { rerender } = render(
      <ItemTableHarness
        items={[{ id: 'A', description: '' }]}
        groups={[
          { id: 'G1', members: ['A'], description: '' },
          { id: 'G2', members: ['A'], description: '' },
        ]}
        onInlineEdit={vi.fn()}
        onEdit={vi.fn()}
        onDelete={vi.fn()}
        removeItemFromGroup={removeItemFromGroup}
      />,
    );

    rerender(
      <ItemTableHarness
        items={[{ id: 'A', description: '' }]}
        groups={[{ id: 'G2', members: ['A'], description: '' }]}
        onInlineEdit={vi.fn()}
        onEdit={vi.fn()}
        onDelete={vi.fn()}
        removeItemFromGroup={removeItemFromGroup}
      />,
    );

    await user.click(screen.getByTitle('Remove "G2"'));

    expect(removeItemFromGroup).toHaveBeenCalledTimes(1);
    expect(removeItemFromGroup).toHaveBeenCalledWith('A', 'G2');
  });
});
