/*
 * This file is part of Nurse Scheduling Project, see <https://github.com/j3soon/nurse-scheduling>.
 *
 * Copyright (C) 2023-2026 Johnson Sun
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

// The types for the scheduling data.
export type ExportFormattingType =
  | 'cell'
  | 'row'
  | 'column'
  | 'people header'
  | 'date header'
  | 'history'
  | 'history header';

export type ExportRequestShape =
  | 'person-item-to-date-item'
  | 'people-group-to-date-item'
  | 'person-item-to-date-group'
  | 'people-group-to-date-group'
  | 'ALL';

export interface ExportPreferenceCondition {
  types: ['shift request'];
  requestShape?: ExportRequestShape[];
  satisfied?: boolean;
  weightRange?: [number, number];
}

export interface ExportFormattingCondition {
  preference: ExportPreferenceCondition;
}

export interface ExportFormattingNote {
  text: string;
}

interface BaseExportFormatting {
  description?: string;
  backgroundColor?: string;
  bottomBorderColor?: string;
  rightBorderColor?: string;
  fontColor?: string;
}

export interface ExportPersonFormatting extends BaseExportFormatting {
  type: 'row' | 'people header' | 'history';
  people: string[];
}

export interface ExportDateFormatting extends BaseExportFormatting {
  type: 'column' | 'date header';
  dates: string[];
}

export interface ExportHistoryHeaderFormatting extends BaseExportFormatting {
  type: 'history header';
}

export interface ExportCellFormatting extends BaseExportFormatting {
  type: 'cell';
  appendText?: string;
  note?: ExportFormattingNote;
  people: string[];
  dates: string[];
  shiftTypes: string[];
  when?: ExportFormattingCondition;
}

export type ExportFormatting =
  | ExportPersonFormatting
  | ExportDateFormatting
  | ExportHistoryHeaderFormatting
  | ExportCellFormatting;

export interface ExportExtraColumn {
  description?: string;
  rightBorderColor?: string;
  type: 'count';
  header: string;
  countShiftTypes: string[];
  countShiftTypeCoefficients?: ShiftCountTypeCoefficient[];
  countDates: string[];
}

export interface ExportExtraRow {
  description?: string;
  bottomBorderColor?: string;
  type: 'count';
  header: string;
  countShiftTypes: string[];
  countPeople: string[];
}

export interface ExportConfig {
  formatting?: ExportFormatting[];
  extraColumns?: ExportExtraColumn[];
  extraRows?: ExportExtraRow[];
}

export interface Item {
  id: string;
  description: string;
  history?: string[];  // Array of shift type IDs representing historical assignments for people
  isAutoGenerated?: boolean;
}

export interface Group {
  id: string;
  members: string[]; // Array of item IDs
  description: string;
  isAutoGenerated?: boolean;
}

export interface AutoGeneratedItem {
  id: string;
  description: string;
}

export interface AutoGeneratedGroup {
  id: string;
  description: string;
  generateMembers: (items: Item[], dateRange?: DateRange) => string[];
}

export interface DateRange {
  startDate?: Date;
  endDate?: Date;
}

export enum DataType {
  DATES = 'dates',
  PEOPLE = 'people',
  SHIFT_TYPES = 'shiftTypes'
}

export const AT_MOST_ONE_SHIFT_PER_DAY = 'at most one shift per day';
export const SHIFT_TYPE_REQUIREMENT = 'shift type requirement';
export const SHIFT_REQUEST = 'shift request';
export const SHIFT_TYPE_SUCCESSIONS = 'shift type successions';
export const SHIFT_COUNT = 'shift count';
export const SHIFT_AFFINITY = 'shift affinity';
export const SHIFT_TYPE_COVERING = 'shift type covering';

export const SUPPORTED_EXPRESSIONS = ['|x - T|^2', 'x >= T', 'x <= T', 'x > T', 'x < T', 'x = T'] as const;
export type ShiftCountTypeCoefficient = [string, number];

export interface BasePreference {
  type: string;
  description?: string;
}

export interface AtMostOneShiftPerDayPreference extends BasePreference {
  type: typeof AT_MOST_ONE_SHIFT_PER_DAY;
}

export interface ShiftTypeRequirementsPreference extends BasePreference {
  type: typeof SHIFT_TYPE_REQUIREMENT;
  description?: string;
  shiftType: string[];
  shiftTypeCoefficients?: ShiftCountTypeCoefficient[];
  requiredNumPeople: number;
  // Backend input accepts either null/missing or the reserved ALL selector for
  // all people. Frontend state intentionally stores the explicit ALL selector
  // so forms and persisted client state never have an implicit empty scope.
  qualifiedPeople: string[];
  preferredNumPeople?: number;
  // Backend input accepts null/missing for all dates; frontend state uses the
  // explicit ALL selector for the same reason as qualifiedPeople.
  date: string[];
  weight: number;
}

export interface ShiftRequestPreference extends BasePreference {
  type: typeof SHIFT_REQUEST;
  description?: string;
  person: string[];  // Should only contain one person
  date: string[];  // Can contain multiple dates
  shiftType: string[];  // Should only contain one shift type
  weight: number;
}

export interface ShiftTypeSuccessionsPreference extends BasePreference {
  type: typeof SHIFT_TYPE_SUCCESSIONS;
  description?: string;
  person: string[];
  pattern: string[];  // List of shift type IDs that are in succession
  // The backend permits null/missing to mean all dates; frontend state uses ALL.
  date: string[];
  weight: number;
}

export interface ShiftCountPreference extends BasePreference {
  type: typeof SHIFT_COUNT;
  description?: string;
  person: string[];
  countDates: string[];
  countShiftTypes: string[];
  countShiftTypeCoefficients?: ShiftCountTypeCoefficient[];
  expression: typeof SUPPORTED_EXPRESSIONS[number];
  target: number;
  weight: number;
}

export interface ShiftAffinityPreference extends BasePreference {
  type: typeof SHIFT_AFFINITY;
  description?: string;
  date: string[];
  people1: string[];
  people2: string[];
  shiftTypes: string[];
  weight: number;
}

export interface ShiftTypeCoveringPreference extends BasePreference {
  type: typeof SHIFT_TYPE_COVERING;
  description?: string;
  date?: string[];
  preceptors: (string | string[])[];
  preceptees: (string | string[])[];
  shiftTypes: (string | string[])[];
  weight: number;
}

// Union type for all preference types in the flattened structure
export type Preference =
  | AtMostOneShiftPerDayPreference
  | ShiftTypeRequirementsPreference
  | ShiftRequestPreference
  | ShiftTypeSuccessionsPreference
  | ShiftCountPreference
  | ShiftAffinityPreference
  | ShiftTypeCoveringPreference;
