/*
 * This file is part of Nurse Scheduling Project, see <https://github.com/j3soon/nurse-scheduling>.
 *
 * Copyright (C) 2023-2026 Johnson Sun
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

// The Save and Load page for Tab "10. Save and Load"
'use client';

import { useState, useRef, useEffect } from 'react';
import { FiHelpCircle, FiDownload, FiSave, FiX, FiCopy, FiCheck, FiAlertCircle, FiUpload } from 'react-icons/fi';
import yaml from 'js-yaml';
import { useSchedulingData } from '@/hooks/useSchedulingData';
import ToggleButton from '@/components/ToggleButton';
import UploadButton from '@/components/UploadButton';
import { CURRENT_APP_VERSION } from '@/utils/version';
import { generateYamlFromState } from '@/utils/yamlGenerator';
import { anonymizeSchedulingState } from '@/utils/anonymizeSchedulingState';
import { getMissingPreferredScatterDateGroups, randomizeConcreteDateShiftRequests } from '@/utils/randomizeShiftRequests';
import { useTabSwitchWarning } from '@/utils/unsavedEditingState';

export default function SaveAndLoadPage() {
  const {
    apiVersionData,
    descriptionData,
    dateData,
    peopleData,
    shiftTypeData,
    preferences,
    exportData,
    loadFromYaml,
    filterAutoGeneratedState
  } = useSchedulingData();

  const [showInstructions, setShowInstructions] = useState(false);
  const [isEditing, setIsEditing] = useState(false);
  const [editedYaml, setEditedYaml] = useState('');
  const [yamlError, setYamlError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);
  const [anonymizePeopleItems, setAnonymizePeopleItems] = useState(true);
  const [anonymizePeopleGroups, setAnonymizePeopleGroups] = useState(false);
  const [scatterShiftRequests, setScatterShiftRequests] = useState(false);
  const textareaRef = useRef<HTMLTextAreaElement>(null);
  const copiedResetTimeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  useEffect(() => {
    return () => {
      if (copiedResetTimeoutRef.current) {
        clearTimeout(copiedResetTimeoutRef.current);
      }
    };
  }, []);
  useTabSwitchWarning(isEditing);

  const instructions = [
    "View the complete current state of your scheduling setup in YAML format",
    "Click 'Download' to save the YAML file to your device",
    "Click 'Upload' to load a YAML file from your device (drag and drop supported)",
    "Click 'Copy' to copy the YAML content",
    "Click 'Edit' to modify the YAML directly and apply changes",
    "Use this to backup your work or share your scheduling configuration",
    "Navigate using the tabs or keyboard shortcuts (1, 2, etc.) to continue setup"
  ];

  // Create the current state object for YAML export (filtering out autogenerated items)
  const filteredState = filterAutoGeneratedState({
    apiVersion: apiVersionData,
    description: descriptionData,
    dates: dateData,
    people: peopleData,
    shiftTypes: shiftTypeData,
    preferences,
    ...(exportData ? { export: exportData } : {})
  });

  // Convert current state to YAML with custom flow style for leaf arrays
  const currentYaml = generateYamlFromState(filteredState);
  const missingPreferredScatterDateGroups = getMissingPreferredScatterDateGroups(dateData.groups);

  const downloadYaml = (yamlContent: string, filenameSuffix = '') => {
    const blob = new Blob([yamlContent], { type: 'application/x-yaml' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `nurse-scheduling${filenameSuffix}-${new Date().toISOString().split('T')[0]}.yaml`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleDownload = () => {
    downloadYaml(currentYaml);
  };

  const handleDownloadAnonymized = () => {
    try {
      const exportState = scatterShiftRequests
        ? randomizeConcreteDateShiftRequests(filteredState, dateData.items, dateData.groups)
        : filteredState;
      const anonymizedState = anonymizeSchedulingState(exportState, {
        anonymizePeopleItems,
        anonymizePeopleGroups
      });
      downloadYaml(generateYamlFromState(anonymizedState), '-anonymized');
    } catch (error) {
      alert(`Unable to randomize shift requests: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  };

  const handleCopyToClipboard = async () => {
    try {
      await navigator.clipboard.writeText(currentYaml);
      setCopied(true);
      if (copiedResetTimeoutRef.current) {
        clearTimeout(copiedResetTimeoutRef.current);
      }
      copiedResetTimeoutRef.current = setTimeout(() => {
        setCopied(false);
        copiedResetTimeoutRef.current = null;
      }, 2000);
    } catch (err) {
      console.error('Failed to copy to clipboard:', err);
    }
  };

  const handleStartEdit = () => {
    setEditedYaml(currentYaml);
    setIsEditing(true);
    setYamlError(null);
  };

  const handleCancelEdit = () => {
    setIsEditing(false);
    setEditedYaml('');
    setYamlError(null);
  };

  // Helper function to check app version mismatch and get warning message
  const getVersionWarning = (parsedData: unknown): string | null => {
    const data = parsedData as { appVersion?: string };
    const fileVersion = data?.appVersion;

    if (!fileVersion) {
      return `The loaded file does not contain app version information. It may have been created with an older version of the application. Current app version: ${CURRENT_APP_VERSION}`;
    }

    if (fileVersion.endsWith('-dirty')) {
      return `Dirty app version detected.\n\nFile app version: ${fileVersion}\nCurrent app version: ${CURRENT_APP_VERSION}\n\nThis YAML was created by a development build with uncommitted changes. It may not match a reproducible application version. If nothing breaks, you can continue.`;
    }

    if (fileVersion !== CURRENT_APP_VERSION) {
      return `App version mismatch detected.\n\nFile app version: ${fileVersion}\nCurrent app version: ${CURRENT_APP_VERSION}\n\nOlder YAML may not work after breaking changes, though we try to preserve compatibility. If nothing breaks, you can continue.`;
    }

    return null;
  };

  const handleSaveEdit = () => {
    try {
      // Validate YAML by parsing it
      const parsedData = yaml.load(editedYaml);

      // Check for version mismatch and warn user
      const versionWarning = getVersionWarning(parsedData);
      if (versionWarning) {
        const proceed = confirm(`${versionWarning}\n\nDo you want to continue applying the changes?`);
        if (!proceed) {
          return;
        }
      }

      // Load the parsed data directly without validation, this willl create a new history state
      loadFromYaml(parsedData);

      // Close the editor
      setIsEditing(false);
      setEditedYaml('');
      setYamlError(null);
    } catch (error) {
      setYamlError(error instanceof Error ? error.message : 'Invalid YAML format');
    }
  };

  const processYamlFile = (file: File) => {
    const reader = new FileReader();
    reader.onload = (e) => {
      const content = e.target?.result as string;
      if (!content) {
        alert('No content found in the uploaded file.');
        return;
      }

      try {
        // Validate YAML by parsing it
        const parsedData = yaml.load(content);

        // Check for version mismatch and warn user
        const versionWarning = getVersionWarning(parsedData);
        if (versionWarning) {
          const proceed = confirm(`${versionWarning}\n\nDo you want to continue loading the file?`);
          if (!proceed) {
            return;
          }
        }

        // Load the parsed data directly without validation, this will create a new history state
        loadFromYaml(parsedData);

        alert('YAML file loaded successfully!');
      } catch (error) {
        alert(`Error loading YAML file: ${error instanceof Error ? error.message : 'Invalid YAML format'}`);
        console.error('Error processing YAML file:', error);
      }
    };

    reader.readAsText(file);
  };

  return (
    <div className="container mx-auto px-4 py-8">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-6 gap-4">
        <div className="flex items-center gap-3">
          <h1 className="text-3xl font-bold text-gray-800">Save and Load</h1>
          {instructions.length > 0 && (
            <button
              onClick={() => setShowInstructions(!showInstructions)}
              className="text-gray-500 hover:text-gray-700 transition-colors"
              title="Toggle instructions"
            >
              <FiHelpCircle className="h-6 w-6" />
            </button>
          )}
        </div>
        <div className="flex gap-4">
          <button
            onClick={handleDownload}
            className="flex items-center gap-2 px-3 py-2 text-sm font-medium rounded-md transition-colors focus:outline-none focus:ring-2 focus:ring-offset-2 bg-blue-600 text-white hover:bg-blue-700 focus:ring-blue-500"
          >
            <FiDownload className="h-4 w-4" />
            Download
          </button>
          <UploadButton
            onFileUpload={processYamlFile}
            acceptedFileTypes={['.yaml', '.yml']}
            buttonText="Upload"
            tooltipText="Upload a YAML file to load configuration. You can click to select a file or drag and drop a file here."
            className="bg-green-600 text-white hover:bg-green-700 focus:ring-green-500"
            icon={<FiUpload className="h-4 w-4" />}
          />
          <button
            onClick={handleCopyToClipboard}
            className={`flex items-center gap-2 px-3 py-2 text-sm font-medium rounded-md transition-colors focus:outline-none focus:ring-2 focus:ring-offset-2 ${
              copied
                ? 'bg-indigo-700 text-white focus:ring-indigo-500'
                : 'bg-indigo-600 text-white hover:bg-indigo-700 focus:ring-indigo-500'
            }`}
          >
            {copied ? <FiCheck className="h-4 w-4" /> : <FiCopy className="h-4 w-4" />}
            {copied ? 'Copied!' : 'Copy'}
          </button>
          <ToggleButton
            label="Edit YAML"
            isToggled={isEditing}
            onToggle={() => {
              if (isEditing) {
                handleCancelEdit();
              } else {
                handleStartEdit();
              }
            }}
          />
        </div>
      </div>

      {showInstructions && instructions.length > 0 && (
        <div className="mb-6 bg-blue-50 border border-blue-200 rounded-lg p-4">
          <h3 className="text-lg font-medium text-blue-800 mb-3">Instructions</h3>
          <ul className="space-y-2 text-sm text-blue-700">
            {instructions.map((instruction, index) => (
              <li key={index}>• {instruction}</li>
            ))}
          </ul>
        </div>
      )}

      {/* Warning Section */}
      <div className="mb-6 bg-amber-50 border border-amber-200 rounded-lg p-4">
        <h3 className="text-lg font-medium text-amber-800 mb-3 flex items-center gap-2">
          <FiAlertCircle className="h-5 w-5" />
          Warning
        </h3>
        <div className="space-y-2 text-sm text-amber-700">
          <p>
            Please note that the <strong>Edit YAML</strong> feature only supports YAML files generated by this web UI version.
            Manual YAML editing is not recommended unless you are 100% confident in what you are doing.
            The web UI expects a specific YAML structure that differs from the more flexible format accepted by the CLI.
            During import, the app may break if the YAML is not in the expected format.
          </p>
        </div>
      </div>

      <details className="mb-6 bg-gray-50 border border-gray-200 rounded-lg p-4">
        <summary className="cursor-pointer text-lg font-medium text-gray-800">
          Anonymize YAML
        </summary>
        <div className="mt-4 space-y-3">
          <p className="text-sm text-gray-600">
            Download a temporary YAML snapshot with selected people identifiers replaced. Your current schedule is not modified.
            Free-text descriptions are not changed.
          </p>
          <div className="flex flex-wrap items-center gap-x-6 gap-y-2">
            <label className="flex items-center gap-2 text-sm text-gray-700">
              <input
                type="checkbox"
                checked={anonymizePeopleItems}
                onChange={(e) => setAnonymizePeopleItems(e.target.checked)}
                className="h-4 w-4"
              />
              Replace people item IDs
            </label>
            <label className="flex items-center gap-2 text-sm text-gray-700">
              <input
                type="checkbox"
                checked={anonymizePeopleGroups}
                onChange={(e) => setAnonymizePeopleGroups(e.target.checked)}
                className="h-4 w-4"
              />
              Replace people group IDs
            </label>
            <label className="flex items-center gap-2 text-sm text-gray-700">
              <input
                type="checkbox"
                checked={scatterShiftRequests}
                onChange={(e) => setScatterShiftRequests(e.target.checked)}
                className="h-4 w-4"
              />
              Scatter shift requests (developer only)
            </label>
          </div>
          <button
            onClick={handleDownloadAnonymized}
            disabled={!anonymizePeopleItems && !anonymizePeopleGroups && !scatterShiftRequests}
            className="flex items-center gap-2 px-3 py-2 text-sm font-medium rounded-md transition-colors focus:outline-none focus:ring-2 focus:ring-offset-2 bg-gray-700 text-white hover:bg-gray-800 focus:ring-gray-500 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            <FiDownload className="h-4 w-4" />
            Download Anonymized
          </button>
          <p className="text-sm text-gray-600">
            Developer only: scattering preserves preferred WORKDAY/FREEDAY counts and consecutive runs. Date-group requests are unchanged.
          </p>
          {scatterShiftRequests && missingPreferredScatterDateGroups.length > 0 && (
            <p className="text-sm text-amber-700">
              Warning: {missingPreferredScatterDateGroups.join(' and ')} {missingPreferredScatterDateGroups.length === 1 ? 'group is' : 'groups are'} missing.
              Scattering will fall back to WEEKDAY and WEEKEND groups.
            </p>
          )}
        </div>
      </details>

      {/* YAML Display/Editor */}
      <div className="bg-white shadow-md rounded-lg overflow-hidden">
        <div className="px-6 py-4 border-b border-gray-200 flex justify-between items-center">
          <h3 className="text-lg font-semibold text-gray-800">
            {isEditing ? 'Edit YAML Configuration' : 'Current State YAML'}
          </h3>
          {isEditing && (
            <div className="flex gap-2">
              <button
                onClick={handleCancelEdit}
                className="px-3 py-1 text-gray-600 border border-gray-300 rounded-md hover:bg-gray-50 transition-colors flex items-center gap-1 text-sm"
              >
                <FiX className="h-4 w-4" />
                Cancel
              </button>
              <button
                onClick={handleSaveEdit}
                className="px-3 py-1 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors flex items-center gap-1 text-sm"
              >
                <FiSave className="h-4 w-4" />
                Save
              </button>
            </div>
          )}
        </div>

        <div className="relative">
          {isEditing ? (
            <div>
              <textarea
                ref={textareaRef}
                value={editedYaml}
                onChange={(e) => {
                  setEditedYaml(e.target.value);
                  setYamlError(null);
                }}
                className="w-full h-96 p-4 font-mono text-sm border-none resize-none focus:outline-none focus:ring-0"
                style={{ fontFamily: 'ui-monospace,SFMono-Regular,SF Mono,Menlo,Consolas,Liberation Mono,monospace' }}
                placeholder="Enter YAML configuration..."
              />
              {yamlError && (
                <div className="px-4 py-2 bg-red-50 border-t border-red-200 text-red-700 text-sm">
                  <p className="text-sm text-red-600 flex items-center gap-1">
                    <FiAlertCircle className="h-4 w-4" />
                    {yamlError}
                  </p>
                </div>
              )}
            </div>
          ) : (
            <pre
              className="w-full h-96 p-4 font-mono text-sm overflow-auto bg-gray-50 whitespace-pre-wrap"
              style={{ fontFamily: 'ui-monospace,SFMono-Regular,SF Mono,Menlo,Consolas,Liberation Mono,monospace' }}
            >
              {currentYaml}
            </pre>
          )}
        </div>
      </div>
    </div>
  );
}
