/*
 * This file is part of Nurse Scheduling Project, see <https://github.com/j3soon/nurse-scheduling>.
 *
 * Copyright (C) 2023-2026 Johnson Sun
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

// This test is mostly AI generated.

import { act, fireEvent, render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import yaml from 'js-yaml';
import { useEffect } from 'react';
import SaveAndLoadPage from '@/app/save-and-load/page';
import {
  UnsavedEditingStateProvider,
  useUnsavedEditingState,
} from '@/utils/unsavedEditingState';

const mockUseSchedulingData = vi.hoisted(() => vi.fn());
const mockGenerateYamlFromState = vi.hoisted(() => vi.fn());

vi.mock('@/hooks/useSchedulingData', () => ({
  useSchedulingData: mockUseSchedulingData,
}));

vi.mock('@/utils/yamlGenerator', () => ({
  generateYamlFromState: mockGenerateYamlFromState,
}));

let hasTabSwitchWarningActive = () => false;

function TestTabSwitchWarningProbe() {
  const { hasTabSwitchWarningActive: readTabSwitchWarningActive } = useUnsavedEditingState();

  useEffect(() => {
    hasTabSwitchWarningActive = readTabSwitchWarningActive;
  }, [readTabSwitchWarningActive]);

  return null;
}

function saveAndLoadPageElement() {
  return (
    <UnsavedEditingStateProvider>
      <TestTabSwitchWarningProbe />
      <SaveAndLoadPage />
    </UnsavedEditingStateProvider>
  );
}

function renderSaveAndLoadPage() {
  return render(saveAndLoadPageElement());
}

describe('SaveAndLoadPage', () => {
  const loadFromYaml = vi.fn();
  const filterAutoGeneratedState = vi.fn((state) => state);
  const fileContentsByName = new Map<string, string>();

  class MockFileReader {
    onload: ((ev: ProgressEvent<FileReader>) => unknown) | null = null;

    readAsText(file: File) {
      const content = fileContentsByName.get(file.name) || '';
      this.onload?.({ target: { result: content } } as unknown as ProgressEvent<FileReader>);
    }
  }

  beforeEach(() => {
    vi.restoreAllMocks();
    loadFromYaml.mockReset();
    filterAutoGeneratedState.mockClear();
    fileContentsByName.clear();
    hasTabSwitchWarningActive = () => false;

    mockGenerateYamlFromState.mockReturnValue('apiVersion: alpha\ndescription: baseline\n');
    mockUseSchedulingData.mockReturnValue({
      apiVersionData: 'alpha',
      descriptionData: 'baseline',
      dateData: { range: { startDate: undefined, endDate: undefined }, items: [], groups: [] },
      peopleData: { items: [], groups: [], history: [] },
      shiftTypeData: { items: [], groups: [] },
      preferences: [],
      exportData: { formatting: [] },
      loadFromYaml,
      filterAutoGeneratedState,
    });

    vi.stubGlobal('confirm', vi.fn(() => true));
    vi.stubGlobal('alert', vi.fn());
    vi.stubGlobal('FileReader', MockFileReader as unknown as typeof FileReader);
    Object.defineProperty(navigator, 'clipboard', {
      value: {
        writeText: vi.fn().mockResolvedValue(undefined),
      },
      configurable: true,
    });
  });

  it('saves edited YAML and sends parsed object to loadFromYaml', async () => {
    const user = userEvent.setup();

    renderSaveAndLoadPage();

    await user.click(screen.getByRole('button', { name: /edit yaml/i }));

    const editor = screen.getByPlaceholderText('Enter YAML configuration...');
    fireEvent.change(editor, { target: { value: 'apiVersion: alpha\ndescription: edited\nappVersion: unknown\n' } });
    await user.click(screen.getByRole('button', { name: /save/i }));

    await waitFor(() => {
      expect(loadFromYaml).toHaveBeenCalledWith(
        expect.objectContaining({ apiVersion: 'alpha', description: 'edited' }),
      );
    });
  });

  it('marks the YAML editor as dirty while editing and clears it on cancel', async () => {
    const user = userEvent.setup();

    renderSaveAndLoadPage();

    await user.click(screen.getByRole('button', { name: /edit yaml/i }));
    expect(hasTabSwitchWarningActive()).toBe(true);

    await user.click(screen.getByRole('button', { name: /cancel/i }));
    expect(hasTabSwitchWarningActive()).toBe(false);
  });

  it('shows an inline error when YAML parsing fails in edit mode', async () => {
    const user = userEvent.setup();
    vi.spyOn(yaml, 'load').mockImplementationOnce(() => {
      throw new Error('Invalid YAML format');
    });

    renderSaveAndLoadPage();

    await user.click(screen.getByRole('button', { name: /edit yaml/i }));
    fireEvent.change(screen.getByPlaceholderText('Enter YAML configuration...'), {
      target: { value: 'bad: [yaml' },
    });
    await user.click(screen.getByRole('button', { name: /save/i }));

    expect(screen.getByText('Invalid YAML format')).toBeInTheDocument();
    expect(loadFromYaml).not.toHaveBeenCalled();
  });

  it('loads uploaded YAML file and reports success', async () => {
    renderSaveAndLoadPage();

    const input = document.querySelector('input[type="file"]') as HTMLInputElement;
    const file = new File(['ignored'], 'upload.yaml', { type: 'application/x-yaml' });
    fileContentsByName.set('upload.yaml', 'apiVersion: alpha\ndescription: from-upload\nappVersion: unknown\n');

    fireEvent.change(input, { target: { files: [file] } });

    await waitFor(() => {
      expect(loadFromYaml).toHaveBeenCalledWith(
        expect.objectContaining({ description: 'from-upload' }),
      );
    });

    expect(alert).toHaveBeenCalledWith('YAML file loaded successfully!');
  });

  it('does not apply edited YAML when version mismatch confirmation is cancelled', async () => {
    const user = userEvent.setup();
    (confirm as unknown as ReturnType<typeof vi.fn>).mockReturnValue(false);

    renderSaveAndLoadPage();

    await user.click(screen.getByRole('button', { name: /edit yaml/i }));
    fireEvent.change(screen.getByPlaceholderText('Enter YAML configuration...'), {
      target: { value: 'apiVersion: alpha\ndescription: edited\nappVersion: v0.0.1\n' },
    });
    await user.click(screen.getByRole('button', { name: /save/i }));

    expect(confirm).toHaveBeenCalled();
    expect(confirm).toHaveBeenCalledWith(expect.stringContaining('Older YAML may not work after breaking changes'));
    expect(confirm).toHaveBeenCalledWith(expect.stringContaining('If nothing breaks, you can continue.'));
    expect(loadFromYaml).not.toHaveBeenCalled();
  });

  it('keeps the editor open with the same text when version mismatch confirmation is cancelled', async () => {
    const user = userEvent.setup();
    (confirm as unknown as ReturnType<typeof vi.fn>).mockReturnValue(false);

    renderSaveAndLoadPage();

    await user.click(screen.getByRole('button', { name: /edit yaml/i }));
    const editor = screen.getByPlaceholderText('Enter YAML configuration...');
    fireEvent.change(editor, {
      target: { value: 'apiVersion: alpha\ndescription: staged\nappVersion: v0.0.1\n' },
    });
    await user.click(screen.getByRole('button', { name: /save/i }));

    expect(confirm).toHaveBeenCalled();
    expect(loadFromYaml).not.toHaveBeenCalled();
    expect(screen.getByPlaceholderText('Enter YAML configuration...')).toHaveValue(
      'apiVersion: alpha\ndescription: staged\nappVersion: v0.0.1\n',
    );
    expect(screen.queryByText('Current State YAML')).not.toBeInTheDocument();
  });

  it('copies the current persisted YAML after version mismatch confirmation is cancelled', async () => {
    const user = userEvent.setup();
    const writeText = vi.fn().mockResolvedValue(undefined);
    Object.defineProperty(navigator, 'clipboard', {
      value: { writeText },
      configurable: true,
    });
    (confirm as unknown as ReturnType<typeof vi.fn>).mockReturnValue(false);

    renderSaveAndLoadPage();

    await user.click(screen.getByRole('button', { name: /edit yaml/i }));
    fireEvent.change(screen.getByPlaceholderText('Enter YAML configuration...'), {
      target: { value: 'apiVersion: alpha\ndescription: staged\nappVersion: v0.0.1\n' },
    });
    await user.click(screen.getByRole('button', { name: /save/i }));
    await user.click(screen.getByRole('button', { name: /cancel/i }));
    await user.click(screen.getByRole('button', { name: /copy/i }));

    await waitFor(() => {
      expect(writeText).toHaveBeenCalledWith('apiVersion: alpha\ndescription: baseline\n');
    });
  });

  it('downloads the current persisted YAML after version mismatch confirmation is cancelled', async () => {
    const user = userEvent.setup();
    const createSpy = vi.spyOn(URL, 'createObjectURL').mockImplementation((blob: Blob | MediaSource) => {
      expect(blob).toBeInstanceOf(Blob);
      return 'blob:cancelled-version-warning';
    });
    vi.spyOn(URL, 'revokeObjectURL').mockImplementation(() => undefined);
    (confirm as unknown as ReturnType<typeof vi.fn>).mockReturnValue(false);

    renderSaveAndLoadPage();

    await user.click(screen.getByRole('button', { name: /edit yaml/i }));
    fireEvent.change(screen.getByPlaceholderText('Enter YAML configuration...'), {
      target: { value: 'apiVersion: alpha\ndescription: staged\nappVersion: v0.0.1\n' },
    });
    await user.click(screen.getByRole('button', { name: /save/i }));
    await user.click(screen.getByRole('button', { name: /cancel/i }));
    await user.click(screen.getByRole('button', { name: /^download$/i }));

    const blob = createSpy.mock.calls[0]?.[0] as Blob;
    expect(await blob.text()).toBe('apiVersion: alpha\ndescription: baseline\n');
  });

  it('does not load uploaded YAML when version mismatch confirmation is cancelled', async () => {
    (confirm as unknown as ReturnType<typeof vi.fn>).mockReturnValue(false);

    renderSaveAndLoadPage();

    const input = document.querySelector('input[type="file"]') as HTMLInputElement;
    const file = new File(['ignored'], 'upload.yaml', { type: 'application/x-yaml' });
    fileContentsByName.set('upload.yaml', 'apiVersion: alpha\ndescription: from-upload\nappVersion: v0.0.1\n');
    fireEvent.change(input, { target: { files: [file] } });

    await waitFor(() => {
      expect(confirm).toHaveBeenCalled();
    });
    expect(loadFromYaml).not.toHaveBeenCalled();
    expect(alert).not.toHaveBeenCalledWith('YAML file loaded successfully!');
  });

  it('warns when uploaded YAML app version ends with dirty even if the base version matches', async () => {
    (confirm as unknown as ReturnType<typeof vi.fn>).mockReturnValue(false);

    renderSaveAndLoadPage();

    const input = document.querySelector('input[type="file"]') as HTMLInputElement;
    const file = new File(['ignored'], 'dirty.yaml', { type: 'application/x-yaml' });
    fileContentsByName.set('dirty.yaml', 'apiVersion: alpha\ndescription: dirty-upload\nappVersion: unknown-dirty\n');
    fireEvent.change(input, { target: { files: [file] } });

    await waitFor(() => {
      expect(confirm).toHaveBeenCalledWith(expect.stringContaining('Dirty app version detected.'));
    });
    expect(confirm).toHaveBeenCalledWith(expect.stringContaining('development build with uncommitted changes'));
    expect(loadFromYaml).not.toHaveBeenCalled();
    expect(alert).not.toHaveBeenCalledWith('YAML file loaded successfully!');
  });

  it('uses the normal mismatch warning when dirty is not the app version suffix', async () => {
    (confirm as unknown as ReturnType<typeof vi.fn>).mockReturnValue(false);

    renderSaveAndLoadPage();

    const input = document.querySelector('input[type="file"]') as HTMLInputElement;
    const file = new File(['ignored'], 'dirty-middle.yaml', { type: 'application/x-yaml' });
    fileContentsByName.set('dirty-middle.yaml', 'apiVersion: alpha\ndescription: dirty-middle\nappVersion: v0.0.1-dirty-extra\n');
    fireEvent.change(input, { target: { files: [file] } });

    await waitFor(() => {
      expect(confirm).toHaveBeenCalledWith(expect.stringContaining('App version mismatch detected.'));
    });
    expect(confirm).not.toHaveBeenCalledWith(expect.stringContaining('Dirty app version detected.'));
    expect(loadFromYaml).not.toHaveBeenCalled();
  });

  it('keeps the current preview, copy, and download state after upload confirmation is cancelled', async () => {
    const user = userEvent.setup();
    const writeText = vi.fn().mockResolvedValue(undefined);
    const createSpy = vi.spyOn(URL, 'createObjectURL').mockImplementation((blob: Blob | MediaSource) => {
      expect(blob).toBeInstanceOf(Blob);
      return 'blob:upload-cancelled';
    });
    vi.spyOn(URL, 'revokeObjectURL').mockImplementation(() => undefined);
    Object.defineProperty(navigator, 'clipboard', {
      value: { writeText },
      configurable: true,
    });
    (confirm as unknown as ReturnType<typeof vi.fn>).mockReturnValue(false);

    renderSaveAndLoadPage();

    const input = document.querySelector('input[type="file"]') as HTMLInputElement;
    const file = new File(['ignored'], 'upload.yaml', { type: 'application/x-yaml' });
    fileContentsByName.set('upload.yaml', 'apiVersion: alpha\ndescription: from-upload\nappVersion: v0.0.1\n');
    fireEvent.change(input, { target: { files: [file] } });

    expect(screen.getByText('Current State YAML')).toBeInTheDocument();

    await user.click(screen.getByRole('button', { name: /copy/i }));
    await waitFor(() => {
      expect(writeText).toHaveBeenCalledWith('apiVersion: alpha\ndescription: baseline\n');
    });

    await user.click(screen.getByRole('button', { name: /^download$/i }));
    const blob = createSpy.mock.calls.at(-1)?.[0] as Blob;
    expect(await blob.text()).toBe('apiVersion: alpha\ndescription: baseline\n');
  });

  it('keeps preview, copy, and download output consistent after loading replacement YAML', async () => {
    const user = userEvent.setup();
    const writeText = vi.fn().mockResolvedValue(undefined);
    const createSpy = vi.spyOn(URL, 'createObjectURL').mockImplementation((blob: Blob | MediaSource) => {
      expect(blob).toBeInstanceOf(Blob);
      return 'blob:loaded-replacement';
    });
    vi.spyOn(URL, 'revokeObjectURL').mockImplementation(() => undefined);
    Object.defineProperty(navigator, 'clipboard', {
      value: { writeText },
      configurable: true,
    });

    mockGenerateYamlFromState.mockReturnValue('apiVersion: alpha\ndescription: uploaded state\n');

    const { rerender } = renderSaveAndLoadPage();

    const input = document.querySelector('input[type="file"]') as HTMLInputElement;
    const file = new File(['ignored'], 'upload.yaml', { type: 'application/x-yaml' });
    fileContentsByName.set('upload.yaml', 'apiVersion: alpha\ndescription: uploaded state\n');
    fireEvent.change(input, { target: { files: [file] } });

    await waitFor(() => {
      expect(loadFromYaml).toHaveBeenCalledWith(expect.objectContaining({ description: 'uploaded state' }));
    });

    mockUseSchedulingData.mockReturnValue({
      apiVersionData: 'alpha',
      descriptionData: 'uploaded state',
      dateData: { range: { startDate: undefined, endDate: undefined }, items: [], groups: [] },
      peopleData: { items: [{ id: 'Uploaded Person', description: '', history: [] }], groups: [], history: [] },
      shiftTypeData: { items: [], groups: [] },
      preferences: [],
      exportData: { formatting: [] },
      loadFromYaml,
      filterAutoGeneratedState,
    });
    rerender(saveAndLoadPageElement());

    expect(screen.getByText('Current State YAML')).toBeInTheDocument();
    expect(document.querySelector('pre')).toHaveTextContent('description: uploaded state');

    await user.click(screen.getByRole('button', { name: /copy/i }));
    await waitFor(() => {
      expect(writeText).toHaveBeenCalledWith('apiVersion: alpha\ndescription: uploaded state\n');
    });

    await user.click(screen.getByRole('button', { name: /^download$/i }));
    const blob = createSpy.mock.calls.at(-1)?.[0] as Blob;
    expect(await blob.text()).toBe('apiVersion: alpha\ndescription: uploaded state\n');
  });

  it('logs copy-to-clipboard failure', async () => {
    const user = userEvent.setup();
    const writeText = vi.fn().mockRejectedValue(new Error('clipboard denied'));
    Object.defineProperty(navigator, 'clipboard', {
      value: { writeText },
      configurable: true,
    });
    const errorSpy = vi.spyOn(console, 'error').mockImplementation(() => undefined);

    renderSaveAndLoadPage();

    await user.click(screen.getByRole('button', { name: /copy/i }));

    await waitFor(() => {
      expect(writeText).toHaveBeenCalled();
      expect(errorSpy).toHaveBeenCalledWith('Failed to copy to clipboard:', expect.any(Error));
    });
  });

  it('logs copy failure when clipboard API is missing', async () => {
    const user = userEvent.setup();
    Object.defineProperty(navigator, 'clipboard', {
      value: undefined,
      configurable: true,
    });
    const errorSpy = vi.spyOn(console, 'error').mockImplementation(() => undefined);

    renderSaveAndLoadPage();

    await user.click(screen.getByRole('button', { name: /copy/i }));

    await waitFor(() => {
      expect(errorSpy).toHaveBeenCalledWith('Failed to copy to clipboard:', expect.any(TypeError));
    });
    expect(screen.queryByRole('button', { name: /copied!/i })).not.toBeInTheDocument();
  });

  it('triggers blob URL download and revokes it', async () => {
    const user = userEvent.setup();
    const createSpy = vi.spyOn(URL, 'createObjectURL').mockReturnValue('blob:mock-url');
    const revokeSpy = vi.spyOn(URL, 'revokeObjectURL').mockImplementation(() => undefined);

    renderSaveAndLoadPage();

    await user.click(screen.getByRole('button', { name: /^download$/i }));

    expect(createSpy).toHaveBeenCalled();
    expect(revokeSpy).toHaveBeenCalledWith('blob:mock-url');
  });

  it('uses a stable date-based filename for downloads', async () => {
    const user = userEvent.setup();
    vi.spyOn(Date.prototype, 'toISOString').mockReturnValue('2026-03-17T12:34:56.000Z');

    const anchorClick = vi.fn();
    const originalAppendChild = document.body.appendChild.bind(document.body);
    const appendSpy = vi.spyOn(document.body, 'appendChild').mockImplementation((node) => {
      if (node instanceof HTMLAnchorElement) {
        vi.spyOn(node, 'click').mockImplementation(anchorClick);
        return originalAppendChild(node);
      }
      return originalAppendChild(node);
    });
    const removeSpy = vi.spyOn(document.body, 'removeChild');
    vi.spyOn(URL, 'createObjectURL').mockReturnValue('blob:mock-url');
    vi.spyOn(URL, 'revokeObjectURL').mockImplementation(() => undefined);

    renderSaveAndLoadPage();

    await user.click(screen.getByRole('button', { name: /^download$/i }));

    const appendedAnchor = appendSpy.mock.calls
      .map(([node]) => node)
      .find((node): node is HTMLAnchorElement => node instanceof HTMLAnchorElement);

    expect(appendedAnchor).toBeDefined();
    expect(appendedAnchor.download).toBe('nurse-scheduling-2026-03-17.yaml');
    expect(anchorClick).toHaveBeenCalled();
    expect(removeSpy).toHaveBeenCalledWith(appendedAnchor);
  });

  it('downloads an item-only anonymized snapshot without changing the current YAML', async () => {
    const user = userEvent.setup();
    mockUseSchedulingData.mockReturnValue({
      apiVersionData: 'alpha',
      descriptionData: 'baseline',
      dateData: { range: { startDate: undefined, endDate: undefined }, items: [], groups: [] },
      peopleData: {
        items: [{ id: 'Alice', description: '' }],
        groups: [{ id: 'Team', members: ['Alice'], description: '' }],
      },
      shiftTypeData: { items: [], groups: [] },
      preferences: [{ type: 'shift request', person: ['Alice'], date: ['01'], shiftType: ['D'], weight: 1 }],
      exportData: {
        formatting: [{ type: 'row', people: ['Alice', 'Team'] }],
        extraRows: [{ type: 'count', header: 'People', countPeople: ['Alice', 'Team'], countShiftTypes: ['D'] }],
      },
      loadFromYaml,
      filterAutoGeneratedState,
    });
    vi.spyOn(URL, 'createObjectURL').mockReturnValue('blob:mock-url');
    vi.spyOn(URL, 'revokeObjectURL').mockImplementation(() => undefined);
    vi.spyOn(HTMLAnchorElement.prototype, 'click').mockImplementation(() => undefined);

    renderSaveAndLoadPage();

    await user.click(screen.getByText('Anonymize YAML'));
    await user.click(screen.getByRole('button', { name: /download anonymized/i }));

    expect(mockGenerateYamlFromState).toHaveBeenLastCalledWith(expect.objectContaining({
      people: {
        items: [{ id: 'P1', description: '' }],
        groups: [{ id: 'Team', members: ['P1'], description: '' }],
      },
      preferences: [{ type: 'shift request', person: ['P1'], date: ['01'], shiftType: ['D'], weight: 1 }],
      export: {
        formatting: [{ type: 'row', people: ['P1', 'Team'] }],
        extraRows: [{ type: 'count', header: 'People', countPeople: ['P1', 'Team'], countShiftTypes: ['D'] }],
      },
    }));
    expect(screen.getByText('Current State YAML')).toBeInTheDocument();
  });

  it('disables anonymized download when both replacement options are unchecked', async () => {
    const user = userEvent.setup();
    renderSaveAndLoadPage();

    await user.click(screen.getByText('Anonymize YAML'));
    await user.click(screen.getByRole('checkbox', { name: /replace people item ids/i }));

    expect(screen.getByRole('button', { name: /download anonymized/i })).toBeDisabled();
  });

  it('downloads scattered and anonymized shift requests when the developer option is checked', async () => {
    const user = userEvent.setup();
    mockUseSchedulingData.mockReturnValue({
      apiVersionData: 'alpha',
      descriptionData: 'baseline',
      dateData: {
        range: { startDate: undefined, endDate: undefined },
        items: ['01', '02', '03', '04'].map(id => ({ id, description: '' })),
        groups: [
          { id: 'WORKDAY', members: ['01', '03'], description: '' },
          { id: 'FREEDAY', members: ['02', '04'], description: '' },
        ],
      },
      peopleData: { items: [{ id: 'Alice', description: '' }], groups: [] },
      shiftTypeData: { items: [{ id: 'D', description: '' }], groups: [] },
      preferences: [{ type: 'shift request', person: ['Alice'], date: ['01'], shiftType: ['D'], weight: 1 }],
      exportData: { formatting: [] },
      loadFromYaml,
      filterAutoGeneratedState,
    });
    vi.spyOn(Math, 'random').mockReturnValue(0);
    vi.spyOn(URL, 'createObjectURL').mockReturnValue('blob:mock-url');
    vi.spyOn(URL, 'revokeObjectURL').mockImplementation(() => undefined);
    vi.spyOn(HTMLAnchorElement.prototype, 'click').mockImplementation(() => undefined);

    renderSaveAndLoadPage();

    await user.click(screen.getByText('Anonymize YAML'));
    await user.click(screen.getByRole('checkbox', { name: /scatter shift requests/i }));
    await user.click(screen.getByRole('button', { name: /download anonymized/i }));

    expect(mockGenerateYamlFromState).toHaveBeenLastCalledWith(expect.objectContaining({
      people: { items: [{ id: 'P1', description: '' }], groups: [] },
      preferences: [{ type: 'shift request', person: ['P1'], date: ['03'], shiftType: ['D'], weight: 1 }],
    }));
  });

  it('warns about missing preferred scatter groups and the weekday fallback', async () => {
    const user = userEvent.setup();
    renderSaveAndLoadPage();

    await user.click(screen.getByText('Anonymize YAML'));
    await user.click(screen.getByRole('checkbox', { name: /scatter shift requests/i }));

    expect(screen.getByText(/WORKDAY and FREEDAY groups are missing/i)).toBeInTheDocument();
    expect(screen.getByText(/fall back to WEEKDAY and WEEKEND groups/i)).toBeInTheDocument();
  });

  it('alerts when uploaded YAML file has no content', () => {
    renderSaveAndLoadPage();

    const input = document.querySelector('input[type="file"]') as HTMLInputElement;
    const file = new File(['ignored'], 'empty.yaml', { type: 'application/x-yaml' });
    fileContentsByName.set('empty.yaml', '');

    fireEvent.change(input, { target: { files: [file] } });

    expect(alert).toHaveBeenCalledWith('No content found in the uploaded file.');
    expect(loadFromYaml).not.toHaveBeenCalled();
  });

  it('alerts on invalid uploaded YAML parsing errors', () => {
    const yamlSpy = vi.spyOn(yaml, 'load').mockImplementationOnce(() => {
      throw new Error('bad yaml');
    });

    renderSaveAndLoadPage();

    const input = document.querySelector('input[type="file"]') as HTMLInputElement;
    const file = new File(['ignored'], 'broken.yaml', { type: 'application/x-yaml' });
    fileContentsByName.set('broken.yaml', 'bad: [yaml');

    fireEvent.change(input, { target: { files: [file] } });

    expect(yamlSpy).toHaveBeenCalled();
    expect(alert).toHaveBeenCalledWith('Error loading YAML file: bad yaml');
    expect(loadFromYaml).not.toHaveBeenCalled();
  });

  it('loads partial YAML payloads after version warning confirmation', () => {
    renderSaveAndLoadPage();

    const input = document.querySelector('input[type="file"]') as HTMLInputElement;
    const file = new File(['ignored'], 'partial.yaml', { type: 'application/x-yaml' });
    fileContentsByName.set('partial.yaml', 'description: partial\n');

    fireEvent.change(input, { target: { files: [file] } });

    expect(confirm).toHaveBeenCalled();
    expect(loadFromYaml).toHaveBeenCalledWith(expect.objectContaining({ description: 'partial' }));
    expect(alert).toHaveBeenCalledWith('YAML file loaded successfully!');
  });

  it('passes through unknown top-level keys when loading uploaded YAML', () => {
    renderSaveAndLoadPage();

    const input = document.querySelector('input[type="file"]') as HTMLInputElement;
    const file = new File(['ignored'], 'unknown-keys.yaml', { type: 'application/x-yaml' });
    fileContentsByName.set('unknown-keys.yaml', 'description: partial\ncustomFlag: true\n');

    fireEvent.change(input, { target: { files: [file] } });

    expect(loadFromYaml).toHaveBeenCalledWith(
      expect.objectContaining({ description: 'partial', customFlag: true }),
    );
  });

  it('saves sparse edited YAML objects without surfacing an inline parse error', async () => {
    const user = userEvent.setup();

    renderSaveAndLoadPage();

    await user.click(screen.getByRole('button', { name: /edit yaml/i }));
    fireEvent.change(screen.getByPlaceholderText('Enter YAML configuration...'), {
      target: { value: 'people:\n  items:\n    - id: P1\n' },
    });
    await user.click(screen.getByRole('button', { name: /save/i }));

    await waitFor(() => {
      expect(loadFromYaml).toHaveBeenCalledWith(
        expect.objectContaining({
          people: expect.objectContaining({
            items: [expect.objectContaining({ id: 'P1' })],
          }),
        }),
      );
    });
    expect(screen.queryByText(/invalid yaml format/i)).not.toBeInTheDocument();
  });

  it('clears inline YAML error when editor text changes after a parse failure', async () => {
    const user = userEvent.setup();

    renderSaveAndLoadPage();

    await user.click(screen.getByRole('button', { name: /edit yaml/i }));
    const editor = screen.getByPlaceholderText('Enter YAML configuration...');

    fireEvent.change(editor, { target: { value: 'bad: [yaml' } });
    await user.click(screen.getByRole('button', { name: /save/i }));
    expect(screen.getByText(/unexpected end/i)).toBeInTheDocument();

    fireEvent.change(editor, { target: { value: 'description: recovered' } });
    expect(screen.queryByText(/unexpected end/i)).not.toBeInTheDocument();
  });

  it('exits editor mode after canceling from an error state', async () => {
    const user = userEvent.setup();

    renderSaveAndLoadPage();

    await user.click(screen.getByRole('button', { name: /edit yaml/i }));
    fireEvent.change(screen.getByPlaceholderText('Enter YAML configuration...'), {
      target: { value: 'bad: [yaml' },
    });
    await user.click(screen.getByRole('button', { name: /save/i }));
    expect(screen.getByText(/unexpected end/i)).toBeInTheDocument();

    await user.click(screen.getByRole('button', { name: /cancel/i }));
    expect(screen.queryByPlaceholderText('Enter YAML configuration...')).not.toBeInTheDocument();
    expect(screen.getByText('Current State YAML')).toBeInTheDocument();
  });

  it('shows copied state temporarily after successful clipboard copy', async () => {
    vi.useFakeTimers();

    renderSaveAndLoadPage();

    fireEvent.click(screen.getByRole('button', { name: /copy/i }));
    await act(async () => {
      await Promise.resolve();
    });
    expect(screen.getByRole('button', { name: /copied!/i })).toBeInTheDocument();

    act(() => {
      vi.advanceTimersByTime(2000);
    });
    expect(screen.getByRole('button', { name: /copy/i })).toBeInTheDocument();
    vi.useRealTimers();
  });

  it('resets unsaved editor text when toggling edit mode off and on again', async () => {
    const user = userEvent.setup();

    renderSaveAndLoadPage();

    await user.click(screen.getByRole('button', { name: /edit yaml/i }));
    const editor = screen.getByPlaceholderText('Enter YAML configuration...') as HTMLTextAreaElement;
    fireEvent.change(editor, { target: { value: 'description: unsaved change\n' } });

    await user.click(screen.getByRole('button', { name: /edit yaml/i }));
    expect(screen.queryByPlaceholderText('Enter YAML configuration...')).not.toBeInTheDocument();

    await user.click(screen.getByRole('button', { name: /edit yaml/i }));
    expect(screen.getByPlaceholderText('Enter YAML configuration...')).toHaveValue(
      'apiVersion: alpha\ndescription: baseline\n',
    );
  });

  it('does not prompt for confirmation when uploaded YAML has a matching app version', () => {
    renderSaveAndLoadPage();

    const input = document.querySelector('input[type="file"]') as HTMLInputElement;
    const file = new File(['ignored'], 'matching.yaml', { type: 'application/x-yaml' });
    fileContentsByName.set('matching.yaml', 'description: ok\nappVersion: unknown\n');

    fireEvent.change(input, { target: { files: [file] } });

    expect(confirm).not.toHaveBeenCalled();
    expect(loadFromYaml).toHaveBeenCalledWith(expect.objectContaining({ description: 'ok' }));
  });
});
