/*
 * This file is part of Nurse Scheduling Project, see <https://github.com/j3soon/nurse-scheduling>.
 *
 * Copyright (C) 2023-2026 Johnson Sun
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

// The people management page for Tab "2. People"
'use client';

import { useState } from 'react';
import { useSchedulingData } from '@/hooks/useSchedulingData';
import ItemGroupEditorPage from '@/components/ItemGroupEditorPage';
import { Mode } from '@/constants/modes';
import { DataType } from '@/types/scheduling';
import { filterAutoGenerated } from '@/utils/keywords';
import UploadButton from '@/components/UploadButton';

const MAX_UPLOADED_PEOPLE = 1000;

export default function PeoplePage() {
  const {
    peopleData,
    // Get functions to pass as props
    addItem,
    addGroup,
    duplicateItem,
    duplicateGroup,
    updateItem,
    updateGroup,
    deleteItem,
    deleteGroup,
    removeItemFromGroup,
    reorderItems,
    reorderGroups,
  } = useSchedulingData();

  const bulkAddPeople = (names: string[]) => {
    if (names.length === 0) {
      alert('No people names found in the uploaded file.');
      return;
    }

    const existingItemsMap = new Map(peopleData.items.map(item => [item.id, item]));
    const reorderedItems = [];
    const usedIds = new Set<string>();

    // First, add items in the order specified by names
    for (const name of names) {
      if (usedIds.has(name)) {
        alert(`Duplicate person name "${name}" found in the uploaded list. Please remove duplicates.`);
        return;
      }
      usedIds.add(name);

      const existingItem = existingItemsMap.get(name);
      if (existingItem) {
        // Move existing person to follow names order
        reorderedItems.push(existingItem);
      } else {
        // Create new item for non-existing name
        reorderedItems.push({
          id: name,
          description: '',
          history: []
        });
      }
    }

    // Then, add any existing items that weren't mentioned in names (keep them at the end)
    for (const existingItem of peopleData.items) {
      if (!usedIds.has(existingItem.id)) {
        reorderedItems.push(existingItem);
      }
    }

    // Calculate counts for the three types of people
    const existingReorderedCount = [...usedIds].filter(name => existingItemsMap.has(name)).length;
    const newlyAddedCount = usedIds.size - existingReorderedCount;
    const existingMovedToEndCount = peopleData.items.filter(item => !usedIds.has(item.id)).length;

    // Create the updated people data with reordered items
    const updatedPeopleData = {
      ...peopleData,
      items: reorderedItems
    };

    // Use reorderItems to trigger the update with the new data
    // This is a bit of a hack, but it works because reorderItems
    // calls updateData which handles the state update properly
    reorderItems(DataType.PEOPLE, updatedPeopleData, updatedPeopleData.items);
    alert(`Successfully uploaded ${names.length} people: ${existingReorderedCount} existing people reordered, ${newlyAddedCount} new people added, ${existingMovedToEndCount} existing people moved to end.`);
  };

  const [mode, setMode] = useState<Mode>(Mode.NORMAL);

  const processPeopleFile = (file: File) => {
    const reader = new FileReader();
    reader.onload = (e) => {
      const content = e.target?.result as string;
      if (!content) {
        alert('No content found in the uploaded file.');
        return;
      }

      // Parse newline-separated names
      const names = content
        .split('\n')
        .map(name => name.trim())
        .filter(name => name.length > 0 && !name.startsWith('#')); // Remove empty lines and comments

      if (names.length > MAX_UPLOADED_PEOPLE) {
        alert(`Uploaded file contains ${names.length} people, which exceeds the maximum of ${MAX_UPLOADED_PEOPLE}. Please split the file and upload fewer names at a time.`);
        return;
      }

      console.log(names);

      // Use the bulk add function to add all people at once
      bulkAddPeople(names);
    };

    reader.readAsText(file);
  };

  const uploadPeopleButton = (
    <UploadButton
      onFileUpload={processPeopleFile}
      acceptedFileTypes={['.txt', '.csv']}
      buttonText="Upload People"
      tooltipText="Upload a file with newline-separated people names. Existing people will be reordered to match the file order, new people will be added, and any existing people not in the file will be moved to the end."
    />
  );

  // Instructions for the help component
  const instructions = [
    "Add people who will be scheduled for work (e.g., \"Alice\", \"Bob\", \"Charlie\")",
    "Create groups to organize people (e.g., \"Nurses\", \"Senior Nurses\", \"Contractors\")",
    "Click and drag through checkboxes to quickly select multiple groups or people when adding or editing",
    "Drag and drop to reorder people or groups",
    "Double-click to edit names or descriptions",
    "Navigate using the tabs or keyboard shortcuts (1, 2, etc.) to continue setup"
  ];

  return (
    <ItemGroupEditorPage
      title="People Management"
      instructions={instructions}
      data={peopleData}
      dataType={DataType.PEOPLE}
      mode={mode}
      setMode={setMode}
      addItem={addItem}
      addGroup={addGroup}
      duplicateItem={duplicateItem}
      duplicateGroup={duplicateGroup}
      updateItem={updateItem}
      updateGroup={updateGroup}
      deleteItem={deleteItem}
      deleteGroup={deleteGroup}
      removeItemFromGroup={removeItemFromGroup}
      reorderItems={reorderItems}
      reorderGroups={reorderGroups}
      filterItemGroups={filterAutoGenerated}
      itemTableHeaderAction={uploadPeopleButton}
    />
  );
}
