/*
 * This file is part of Nurse Scheduling Project, see <https://github.com/j3soon/nurse-scheduling>.
 *
 * Copyright (C) 2023-2026 Johnson Sun
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

// This test is mostly AI generated.

import { render, screen } from '@testing-library/react';
import ShiftTypePage from '@/app/shift-types/page';

const mockUseSchedulingData = vi.hoisted(() => vi.fn());
const mockItemGroupEditorPage = vi.hoisted(() => vi.fn());

vi.mock('@/hooks/useSchedulingData', () => ({
  useSchedulingData: mockUseSchedulingData,
}));

vi.mock('@/components/ItemGroupEditorPage', () => ({
  __esModule: true,
  default: (props: Record<string, unknown>) => {
    mockItemGroupEditorPage(props);
    return <div>Mock Shift Type Editor</div>;
  },
}));

describe('ShiftTypePage', () => {
  beforeEach(() => {
    mockItemGroupEditorPage.mockReset();
    mockUseSchedulingData.mockReturnValue({
      shiftTypeData: {
        items: [{ id: 'D', description: 'Day' }],
        groups: [{ id: 'Day', members: ['D'], description: 'Day shifts' }],
      },
      addItem: vi.fn(),
      addGroup: vi.fn(),
      updateItem: vi.fn(),
      updateGroup: vi.fn(),
      deleteItem: vi.fn(),
      deleteGroup: vi.fn(),
      removeItemFromGroup: vi.fn(),
      reorderItems: vi.fn(),
      reorderGroups: vi.fn(),
    });
  });

  it('passes the shift-type page wiring into ItemGroupEditorPage', () => {
    render(<ShiftTypePage />);

    expect(screen.getByText('Mock Shift Type Editor')).toBeInTheDocument();
    const props = mockItemGroupEditorPage.mock.calls[0][0] as {
      title: string;
      dataType: string;
      data: { items: Array<{ id: string }> };
      filterItemGroups: (entries: Array<{ id: string; isAutoGenerated?: boolean }>) => Array<{ id: string }>;
    };

    expect(props.title).toBe('Shift Type Management');
    expect(props.dataType).toBe('shiftTypes');
    expect(props.data.items).toEqual([expect.objectContaining({ id: 'D' })]);
    expect(props.filterItemGroups).toBeTypeOf('function');
  });

  it('filters auto-generated shift types and groups from selectable entries', () => {
    render(<ShiftTypePage />);

    const props = mockItemGroupEditorPage.mock.calls[0][0] as {
      filterItemGroups: (entries: Array<{ id: string; isAutoGenerated?: boolean }>) => Array<{ id: string }>;
    };

    expect(
      props.filterItemGroups([
        { id: 'OFF', isAutoGenerated: true },
        { id: 'D' },
        { id: 'ALL', isAutoGenerated: true },
        { id: 'Day' },
      ]),
    ).toEqual([{ id: 'D' }, { id: 'Day' }]);
  });

  it('passes auto-generated OFF through the page data while still filtering it from selectable entries', () => {
    mockUseSchedulingData.mockReturnValue({
      shiftTypeData: {
        items: [
          { id: 'OFF', description: 'Off shift type', isAutoGenerated: true },
          { id: 'D', description: 'Day' },
        ],
        groups: [
          { id: 'ALL', members: ['OFF', 'D'], description: 'All shifts', isAutoGenerated: true },
          { id: 'Day', members: ['D'], description: 'Day shifts' },
        ],
      },
      addItem: vi.fn(),
      addGroup: vi.fn(),
      updateItem: vi.fn(),
      updateGroup: vi.fn(),
      deleteItem: vi.fn(),
      deleteGroup: vi.fn(),
      removeItemFromGroup: vi.fn(),
      reorderItems: vi.fn(),
      reorderGroups: vi.fn(),
    });

    render(<ShiftTypePage />);

    const props = mockItemGroupEditorPage.mock.calls[0][0] as {
      data: { items: Array<{ id: string }> };
      filterItemGroups: (entries: Array<{ id: string; isAutoGenerated?: boolean }>) => Array<{ id: string }>;
    };

    expect(props.data.items).toEqual(
      expect.arrayContaining([
        expect.objectContaining({ id: 'OFF' }),
        expect.objectContaining({ id: 'D' }),
      ]),
    );
    expect(props.filterItemGroups(props.data.items)).toEqual([{ id: 'D', description: 'Day' }]);
  });

  it('passes auto-generated ALL through group data while still filtering it from editable selections', () => {
    mockUseSchedulingData.mockReturnValue({
      shiftTypeData: {
        items: [{ id: 'D', description: 'Day' }],
        groups: [
          { id: 'ALL', members: ['D'], description: 'All shifts', isAutoGenerated: true },
          { id: 'Day', members: ['D'], description: 'Day shifts' },
        ],
      },
      addItem: vi.fn(),
      addGroup: vi.fn(),
      updateItem: vi.fn(),
      updateGroup: vi.fn(),
      deleteItem: vi.fn(),
      deleteGroup: vi.fn(),
      removeItemFromGroup: vi.fn(),
      reorderItems: vi.fn(),
      reorderGroups: vi.fn(),
    });

    render(<ShiftTypePage />);

    const props = mockItemGroupEditorPage.mock.calls[0][0] as {
      data: { groups: Array<{ id: string }> };
      filterItemGroups: (entries: Array<{ id: string; isAutoGenerated?: boolean }>) => Array<{ id: string }>;
    };

    expect(props.data.groups).toEqual(
      expect.arrayContaining([
        expect.objectContaining({ id: 'ALL' }),
        expect.objectContaining({ id: 'Day' }),
      ]),
    );
    expect(props.filterItemGroups(props.data.groups)).toEqual([{ id: 'Day', members: ['D'], description: 'Day shifts' }]);
  });
});
