name: Test Core

on:
  - push
  - pull_request

permissions:
  contents: read

jobs:
  test-core:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: cd core && python -m pip install -r requirements.txt
      - name: Test with pytest and collect coverage
        run: cd core && pytest --cov=nurse_scheduling --log-cli-level=DEBUG tests
      - name: Upload coverage to Codecov
        if: github.event_name != 'pull_request'
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: core
          name: core-pytest
