"""Check that core/ matches the recorded upstream (v1 feature/genie) blobs.

upstream-patches/manifest.toml gives every core/ file one origin row:

- `verbatim`: byte-identical to the upstream blob.
- `patched`: the upstream blob plus the named v2 patches.
- `v2-only`: no upstream file. `note` says why it exists.
- `excluded`: an upstream path (a glob) that v2 does not vendor. `note` says why.

This check copies each `verbatim` and `patched` file into a scratch tree,
reverse-applies the recorded v2 patches newest first, and compares the git blob
SHA with the recorded upstream blob. It also checks that every core/ file has
exactly one row, and that the origin table in the T19 manifest doc matches the
manifest. Needs `git` on PATH but no access to the upstream repository.

Run from core/: `python -m scripts.check_upstream_sync`. Add `--write-table` to
regenerate the doc table from the manifest.
"""

import fnmatch
import hashlib
import re
import shutil
import subprocess
import sys
import tempfile
import tomllib
from pathlib import Path

CORE = Path(__file__).resolve().parents[1]
PATCH_DIR = CORE / "upstream-patches"
DOC = CORE.parent / "docs" / "T19-upstream-backend-source-manifest.md"
TRACKED = ("verbatim", "patched")
CLASSES = (*TRACKED, "v2-only", "excluded")
TABLE_START = "<!-- origin-table:start (generated by core/scripts/check_upstream_sync.py --write-table) -->"
TABLE_END = "<!-- origin-table:end -->"


def git_blob_sha(data: bytes) -> str:
    """Return the SHA-1 that `git hash-object` gives these bytes."""
    return hashlib.sha1(b"blob %d\0" % len(data) + data).hexdigest()


def load_manifest() -> dict:
    return tomllib.loads((PATCH_DIR / "manifest.toml").read_text(encoding="utf-8"))


def core_files() -> list[str]:
    """Tracked and new (not ignored) files under core/, relative to core/."""
    out = subprocess.run(
        ["git", "ls-files", "-z", "--cached", "--others", "--exclude-standard", "."],
        cwd=CORE,
        capture_output=True,
        check=True,
    ).stdout
    return sorted({p for p in out.decode().split("\0") if p and (CORE / p).is_file()})


def patch_ids(name: str) -> list[str]:
    """Patch IDs of one patch file: from its `# hunk:` header, else its file name."""
    head = [line for line in (PATCH_DIR / name).read_text(encoding="utf-8").splitlines() if line.startswith("#")]
    ids = re.findall(r"\b(P\d+|X\d+)\b", " ".join(head)) or re.findall(r"P\d+", name)
    return sorted(set(ids), key=lambda i: (i[0], int(i[1:])))


def render_table(manifest: dict) -> str:
    """The markdown origin table, one row per manifest entry."""
    lines = [
        f"Upstream: {manifest['upstream']} at `{manifest['upstream_commit']}`.",
        "",
        "| File (under `core/`) | Class | Genie blob | Patches or reason |",
        "| --- | --- | --- | --- |",
    ]
    for entry in sorted(manifest["file"], key=lambda e: e["path"]):
        blob = f"`{entry['upstream_blob'][:12]}`" if "upstream_blob" in entry else ""
        detail = []
        for name in entry.get("patches", []):
            ids = ", ".join(patch_ids(name))
            detail.append(f"`{name}`" + (f" ({ids})" if ids else ""))
        if "note" in entry:
            detail.append(entry["note"])
        lines.append(f"| `{entry['path']}` | {entry['class']} | {blob} | {'. '.join(detail)} |")
    return "\n".join(lines)


def doc_with_table(text: str, table: str) -> str:
    start, end = text.index(TABLE_START) + len(TABLE_START), text.index(TABLE_END)
    return f"{text[:start]}\n{table}\n{text[end:]}"


def check_rows(manifest: dict) -> list[str]:
    """Every core/ file has exactly one row, and every non-excluded row names a file."""
    failures = [f"{e['path']}: unknown class {e['class']!r}" for e in manifest["file"] if e["class"] not in CLASSES]
    exact: dict[str, int] = {}
    for entry in manifest["file"]:
        if entry["class"] != "excluded":
            exact[entry["path"]] = exact.get(entry["path"], 0) + 1
    excluded = [e["path"] for e in manifest["file"] if e["class"] == "excluded"]
    files = core_files()
    for path in files:
        hits = [p for p in excluded if fnmatch.fnmatch(path, p)]
        if hits:
            failures.append(f"{path}: present in core/ but matches excluded row {hits[0]!r}")
        elif exact.get(path, 0) != 1:
            failures.append(f"{path}: has {exact.get(path, 0)} origin rows, needs exactly 1")
    present = set(files)
    failures += [f"{path}: row names a file that is not in core/" for path in exact if path not in present]
    return failures


def check_blobs(manifest: dict) -> tuple[int, list[str]]:
    tracked = [entry for entry in manifest["file"] if entry["class"] in TRACKED]
    failures: list[str] = []
    with tempfile.TemporaryDirectory() as scratch:
        root = Path(scratch)
        for entry in tracked:
            target = root / "core" / entry["path"]
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(CORE / entry["path"], target)
        for name in reversed(manifest["patch_order"]):
            result = subprocess.run(
                ["git", "apply", "-R", str(PATCH_DIR / name)], cwd=root, capture_output=True, text=True
            )
            if result.returncode != 0:
                failures.append(f"{name}: does not reverse-apply: {result.stderr.strip()}")
        for entry in tracked:
            actual = git_blob_sha((root / "core" / entry["path"]).read_bytes())
            if actual != entry["upstream_blob"]:
                failures.append(f"{entry['path']}: blob {actual} differs from upstream {entry['upstream_blob']}")
    return len(tracked), failures


def main(argv: list[str] | None = None) -> int:
    argv = sys.argv[1:] if argv is None else argv
    manifest = load_manifest()
    doc = DOC.read_text(encoding="utf-8")
    expected = doc_with_table(doc, render_table(manifest))
    if "--write-table" in argv:
        DOC.write_text(expected, encoding="utf-8")
        doc = expected
    failures = check_rows(manifest)
    count, blob_failures = check_blobs(manifest)
    failures += blob_failures
    if doc != expected:
        failures.append(f"{DOC.name}: origin table is stale; run with --write-table")
    for failure in failures:
        print(failure, file=sys.stderr)
    print(
        f"{len(manifest['file'])} rows; checked {count} files against {manifest['upstream_commit']}: "
        f"{len(failures)} problem(s)"
    )
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
