/*
 * This file is part of Nurse Scheduling Project, see <https://github.com/j3soon/nurse-scheduling>.
 *
 * Copyright (C) 2023-2026 Johnson Sun
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

// This test is mostly AI generated.

import { render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { act } from 'react';
import OptimizeAndExportPage from '@/app/optimize-and-export/page';
import {
  selectOfflineFallbackBackendApiUrl,
  selectPreferredServer,
} from '@/app/optimize-and-export/serverSelection';

const mockUseSchedulingData = vi.hoisted(() => vi.fn());
const mockGenerateYamlFromState = vi.hoisted(() => vi.fn());
const mockRestorePeopleIdsInXlsx = vi.hoisted(() => vi.fn());
const mockCurrentAppVersion = vi.hoisted(() => ({ value: 'frontend-test' }));

vi.mock('@/hooks/useSchedulingData', () => ({
  useSchedulingData: mockUseSchedulingData,
}));

vi.mock('@/utils/yamlGenerator', () => ({
  generateYamlFromState: mockGenerateYamlFromState,
}));

vi.mock('@/utils/restorePeopleIdsInXlsx', () => ({
  restorePeopleIdsInXlsx: mockRestorePeopleIdsInXlsx,
}));

vi.mock('@/utils/version', () => ({
  get CURRENT_APP_VERSION() {
    return mockCurrentAppVersion.value;
  },
  compareVersionsDescending: vi.fn(() => 0),
  parseVersionParts: (version: string) => ({
    dirty: version.endsWith('-dirty'),
  }),
}));

const LOCAL_API_URL = 'http://localhost:8000';
const PRODUCTION_API_URL = 'https://api.nursescheduling.org';

class MockEventSource {
  static instances: MockEventSource[] = [];

  listeners = new Map<string, Array<(event: MessageEvent) => void>>();
  url: string;
  close = vi.fn();

  constructor(url: string) {
    this.url = url;
    MockEventSource.instances.push(this);
  }

  addEventListener(type: string, listener: (event: MessageEvent) => void) {
    this.listeners.set(type, [...(this.listeners.get(type) ?? []), listener]);
  }

  emit(type: string, data: unknown) {
    const event = new MessageEvent(type, {
      data: typeof data === 'string' ? data : JSON.stringify(data),
    });
    this.listeners.get(type)?.forEach(listener => listener(event));
  }
}

const createSchedulingData = (overrides = {}) => ({
  apiVersionData: 'alpha',
  descriptionData: 'baseline',
  dateData: {
    range: { startDate: new Date('2026-09-01'), endDate: new Date('2026-09-01') },
    items: [{ id: '01', description: '' }],
    groups: [],
  },
  peopleData: { items: [{ id: 'P1', description: '', history: [] }], groups: [], history: [] },
  shiftTypeData: { items: [{ id: 'D', description: '' }], groups: [] },
  preferences: [],
  exportData: { formatting: [] },
  filterAutoGeneratedState: vi.fn(state => state),
  ...overrides,
});

const healthyResponse = (overrides: Partial<{
  status: string;
  version: string;
  apiVersion: string;
  appVersion: string;
}> = {}) => ({
  ok: true,
  json: vi.fn().mockResolvedValue({
    status: 'ok',
    version: 'alpha',
    apiVersion: 'alpha',
    appVersion: 'frontend-test',
    ...overrides,
  }),
});

const queueInitialLocalSelection = (fetchMock: ReturnType<typeof vi.fn>) => {
  fetchMock.mockResolvedValueOnce(healthyResponse());
  return fetchMock;
};

async function editBackendEndpoint(user: ReturnType<typeof userEvent.setup>, from: string, to: string) {
  await user.dblClick(await screen.findByTitle(from));
  const endpointInput = screen.getByDisplayValue(from);
  expect(endpointInput).toHaveAttribute('type', 'text');
  await user.clear(endpointInput);
  await user.type(endpointInput, to);
  await user.tab();
}

describe('optimize backend server selection', () => {
  it('uses healthy backend list order without comparing app versions', () => {
    const selected = selectPreferredServer([
      {
        endpoint: PRODUCTION_API_URL,
        index: 1,
        health: {
          status: 'ok',
          version: 'alpha',
          apiVersion: 'alpha',
          appVersion: 'newer-backend',
        },
      },
      {
        endpoint: LOCAL_API_URL,
        index: 0,
        health: {
          status: 'ok',
          version: 'alpha',
          apiVersion: 'alpha',
          appVersion: 'older-backend',
        },
      },
    ]);

    expect(selected?.endpoint).toBe(LOCAL_API_URL);
  });

  it('falls back to production when all production-enabled backend candidates are offline', () => {
    expect(selectOfflineFallbackBackendApiUrl([LOCAL_API_URL, PRODUCTION_API_URL])).toBe(PRODUCTION_API_URL);
  });

  it('falls back to local when production is not a backend candidate', () => {
    expect(selectOfflineFallbackBackendApiUrl([LOCAL_API_URL])).toBe(LOCAL_API_URL);
  });

  it('does not treat URLs containing the production hostname as production candidates', () => {
    expect(selectOfflineFallbackBackendApiUrl([
      LOCAL_API_URL,
      'https://api.nursescheduling.org.example.test',
      'https://example.test/https://api.nursescheduling.org',
      'https://api.nursescheduling.org.example.test/https://api.nursescheduling.org',
    ])).toBe(LOCAL_API_URL);
  });
});

describe('OptimizeAndExportPage error handling', () => {
  beforeEach(() => {
    vi.restoreAllMocks();
    MockEventSource.instances = [];
    mockGenerateYamlFromState.mockReturnValue('apiVersion: alpha\ndescription: baseline\n');
    mockRestorePeopleIdsInXlsx.mockClear();
    mockRestorePeopleIdsInXlsx.mockImplementation(async blob => blob);
    mockUseSchedulingData.mockReturnValue(createSchedulingData());
    mockCurrentAppVersion.value = 'frontend-test';
    vi.stubGlobal('fetch', vi.fn());
    vi.stubGlobal('EventSource', undefined);
    vi.spyOn(URL, 'createObjectURL').mockReturnValue('blob:mock');
    vi.spyOn(URL, 'revokeObjectURL').mockImplementation(() => undefined);
    window.localStorage.removeItem('nurse-scheduling-optimize-server-options');
  });

  it('surfaces raw non-JSON error bodies from the backend', async () => {
    const user = userEvent.setup();
    queueInitialLocalSelection(fetch as unknown as ReturnType<typeof vi.fn>)
      .mockResolvedValueOnce({
        ok: false,
        status: 503,
        text: vi.fn().mockResolvedValue('service unavailable'),
      });

    render(<OptimizeAndExportPage />);
    await screen.findByText('Server: Online');
    await user.click(screen.getByRole('button', { name: /optimize and download/i }));

    await expect(screen.findByText('Server error (503): service unavailable')).resolves.toBeInTheDocument();
  });

  it('falls back to the raw JSON text when the backend error body has no detail field', async () => {
    const user = userEvent.setup();
    queueInitialLocalSelection(fetch as unknown as ReturnType<typeof vi.fn>)
      .mockResolvedValueOnce({
        ok: false,
        status: 422,
        text: vi.fn().mockResolvedValue(JSON.stringify({ error: 'validation failed' })),
      });

    render(<OptimizeAndExportPage />);
    await screen.findByText('Server: Online');
    await user.click(screen.getByRole('button', { name: /optimize and download/i }));

    await expect(screen.findByText('Server error (422): {"error":"validation failed"}')).resolves.toBeInTheDocument();
  });

  it('keeps showing the raw response text when JSON parsing itself fails', async () => {
    const user = userEvent.setup();
    queueInitialLocalSelection(fetch as unknown as ReturnType<typeof vi.fn>)
      .mockResolvedValueOnce({
        ok: false,
        status: 500,
        text: vi.fn().mockResolvedValue('{bad json'),
      });

    render(<OptimizeAndExportPage />);
    await screen.findByText('Server: Online');
    await user.click(screen.getByRole('button', { name: /optimize and download/i }));

    await expect(screen.findByText('Server error (500): {bad json')).resolves.toBeInTheDocument();
    expect(screen.queryByText(/check that your frontend and backend versions match/i)).not.toBeInTheDocument();
  });

  it('does not show generic version compatibility guidance', () => {
    (fetch as unknown as ReturnType<typeof vi.fn>).mockImplementation(() => new Promise(() => undefined));

    render(<OptimizeAndExportPage />);

    expect(screen.queryByText(/this project is in active development/i)).not.toBeInTheDocument();
    expect(screen.queryByText(/check that your frontend and backend versions match/i)).not.toBeInTheDocument();
  });

  it('shows backend health status from the health endpoint', async () => {
    (fetch as unknown as ReturnType<typeof vi.fn>).mockResolvedValue({
      ok: true,
      json: vi.fn().mockResolvedValue({
        status: 'ok',
        version: 'alpha',
        apiVersion: 'alpha',
        appVersion: 'v-test',
      }),
    });

    render(<OptimizeAndExportPage />);

    await expect(screen.findByText('Server: Online')).resolves.toBeInTheDocument();
    expect(screen.getByText(/API version: alpha · Frontend version: frontend-test · Backend version: v-test/)).toBeInTheDocument();
    expect(screen.getByText(/Last checked: .* · \d+ ms/)).toBeInTheDocument();
  });

  it('allows an empty solver timeout while editing and clears its run error only after a value change', async () => {
    const user = userEvent.setup();
    const fetchMock = fetch as unknown as ReturnType<typeof vi.fn>;
    queueInitialLocalSelection(fetchMock);

    render(<OptimizeAndExportPage />);
    await screen.findByText('Server: Online');

    const timeoutInput = screen.getByRole('spinbutton');
    await user.clear(timeoutInput);
    await user.click(screen.getByRole('button', { name: /optimize and download/i }));

    expect(screen.getByText('Solver timeout must be a valid positive integer.')).toBeInTheDocument();
    expect(timeoutInput).toHaveClass('border-red-300');
    expect(fetchMock).toHaveBeenCalledTimes(1);

    await user.type(timeoutInput, 'abc');

    expect(screen.getByText('Solver timeout must be a valid positive integer.')).toBeInTheDocument();
    expect(timeoutInput).toHaveClass('border-red-300');

    await user.type(timeoutInput, '45');

    expect(screen.queryByText('Solver timeout must be a valid positive integer.')).not.toBeInTheDocument();
    expect(timeoutInput).not.toHaveClass('border-red-300');
  });

  it('keeps the previous backend version visible while a health check is pending and clears it when offline', async () => {
    const user = userEvent.setup();
    const fetchMock = fetch as unknown as ReturnType<typeof vi.fn>;
    queueInitialLocalSelection(fetchMock);

    render(<OptimizeAndExportPage />);

    await expect(screen.findByText('Server: Online')).resolves.toBeInTheDocument();
    const versionDetails = /API version: alpha · Frontend version: frontend-test · Backend version: frontend-test/;
    expect(screen.getByText(versionDetails)).toBeInTheDocument();

    let resolveHealthCheck: (response: { ok: boolean }) => void = () => undefined;
    fetchMock.mockImplementationOnce(() => new Promise(resolve => {
      resolveHealthCheck = resolve;
    }));
    await user.click(screen.getByRole('button', { name: /check backend/i }));

    expect(screen.getByText('Server: Checking')).toBeInTheDocument();
    expect(screen.getByText(versionDetails)).toBeInTheDocument();

    act(() => {
      resolveHealthCheck({ ok: false });
    });

    await expect(screen.findByText('Server: Offline')).resolves.toBeInTheDocument();
    expect(screen.queryByText(versionDetails)).not.toBeInTheDocument();
  });

  it('ignores an older failed health check after a newer check succeeds', async () => {
    const user = userEvent.setup();
    const fetchMock = fetch as unknown as ReturnType<typeof vi.fn>;
    queueInitialLocalSelection(fetchMock);

    render(<OptimizeAndExportPage />);

    await expect(screen.findByText('Server: Online')).resolves.toBeInTheDocument();

    let resolveOlderHealthCheck: (response: { ok: boolean }) => void = () => undefined;
    fetchMock
      .mockImplementationOnce(() => new Promise(resolve => {
        resolveOlderHealthCheck = resolve;
      }))
      .mockResolvedValueOnce(healthyResponse());

    await user.click(screen.getByRole('button', { name: /check backend/i }));
    expect(screen.getByText('Server: Checking')).toBeInTheDocument();

    await user.click(screen.getByRole('button', { name: /check backend/i }));
    await expect(screen.findByText('Server: Online')).resolves.toBeInTheDocument();

    act(() => {
      resolveOlderHealthCheck({ ok: false });
    });

    await waitFor(() => {
      expect(screen.getByText('Server: Online')).toBeInTheDocument();
      expect(screen.queryByText('Server: Offline')).not.toBeInTheDocument();
    });
  });

  it('does not fall back to the production backend during tests', async () => {
    (fetch as unknown as ReturnType<typeof vi.fn>)
      .mockRejectedValueOnce(new Error('local backend unavailable'));

    render(<OptimizeAndExportPage />);

    await expect(screen.findByTitle(LOCAL_API_URL)).resolves.toBeInTheDocument();
    await expect(screen.findByText('Server: Offline')).resolves.toBeInTheDocument();

    expect(fetch).toHaveBeenCalledWith(`${LOCAL_API_URL}/health`, expect.objectContaining({ method: 'GET' }));
    expect(fetch).not.toHaveBeenCalledWith(`${PRODUCTION_API_URL}/health`, expect.anything());
  });

  it('shows the local backend version mismatch without probing production during tests', async () => {
    (fetch as unknown as ReturnType<typeof vi.fn>).mockResolvedValueOnce(healthyResponse({ appVersion: 'backend-test' }));

    render(<OptimizeAndExportPage />);

    await expect(screen.findByTitle(LOCAL_API_URL)).resolves.toBeInTheDocument();
    await expect(screen.findByText('Server: Online')).resolves.toBeInTheDocument();
    expect(screen.getByText(/frontend and backend versions do not match/i)).toBeInTheDocument();
    expect(fetch).not.toHaveBeenCalledWith(`${PRODUCTION_API_URL}/health`, expect.anything());
  });

  it('offers default backend candidates while allowing custom endpoint input', async () => {
    const user = userEvent.setup();
    queueInitialLocalSelection(fetch as unknown as ReturnType<typeof vi.fn>);

    render(<OptimizeAndExportPage />);

    await expect(screen.findByTitle(LOCAL_API_URL)).resolves.toBeInTheDocument();
    const candidateValues = Array.from(document.querySelectorAll('#backend-api-candidates option'))
      .map(option => option.getAttribute('value'));
    expect(candidateValues).toEqual([LOCAL_API_URL]);

    await editBackendEndpoint(user, LOCAL_API_URL, 'https://backend.example.test');

    expect(screen.getByTitle('https://backend.example.test')).toBeInTheDocument();
  });

  it('hydrates stored backend options before the initial health check', async () => {
    const fetchMock = fetch as unknown as ReturnType<typeof vi.fn>;
    fetchMock.mockResolvedValue(healthyResponse({ appVersion: 'stored-backend' }));
    window.localStorage.setItem('nurse-scheduling-optimize-server-options', JSON.stringify({
      servers: [{ endpoint: 'https://stored-backend.example.test' }],
      selectedServerEndpoint: 'https://stored-backend.example.test',
    }));

    render(<OptimizeAndExportPage />);

    await expect(screen.findByTitle('https://stored-backend.example.test')).resolves.toBeInTheDocument();
    await waitFor(() => expect(fetchMock).toHaveBeenCalledWith(
      'https://stored-backend.example.test/health',
      expect.objectContaining({ method: 'GET' })
    ));
    expect(fetchMock).not.toHaveBeenCalledWith(`${LOCAL_API_URL}/health`, expect.anything());
  });

  it('selects a backend when clicking anywhere on its row', async () => {
    const user = userEvent.setup();
    const fetchMock = fetch as unknown as ReturnType<typeof vi.fn>;
    fetchMock.mockResolvedValue(healthyResponse());
    window.localStorage.setItem('nurse-scheduling-optimize-server-options', JSON.stringify({
      servers: [
        { endpoint: 'https://first-backend.example.test' },
        { endpoint: 'https://second-backend.example.test' },
      ],
      selectedServerEndpoint: 'https://first-backend.example.test',
    }));

    render(<OptimizeAndExportPage />);

    const secondBackend = await screen.findByTitle('https://second-backend.example.test');
    await user.click(secondBackend.closest('tr') as HTMLTableRowElement);

    expect(screen.getByLabelText('Select https://second-backend.example.test')).toBeChecked();
    expect(screen.getByText('Server: Online').nextElementSibling).toHaveTextContent('https://second-backend.example.test');
    expect(fetchMock).toHaveBeenCalledWith(
      'https://second-backend.example.test/health',
      expect.objectContaining({ method: 'GET' })
    );
  });

  it('disables backend dragging while editing and allows the blur click to select another row', async () => {
    const user = userEvent.setup();
    const fetchMock = fetch as unknown as ReturnType<typeof vi.fn>;
    fetchMock.mockResolvedValue(healthyResponse());
    window.localStorage.setItem('nurse-scheduling-optimize-server-options', JSON.stringify({
      servers: [
        { endpoint: 'https://first-backend.example.test' },
        { endpoint: 'https://second-backend.example.test' },
      ],
      selectedServerEndpoint: 'https://first-backend.example.test',
    }));

    render(<OptimizeAndExportPage />);

    await user.dblClick(await screen.findByTitle('https://first-backend.example.test'));
    const endpointInput = screen.getByDisplayValue('https://first-backend.example.test');
    const secondRow = (await screen.findByTitle('https://second-backend.example.test')).closest('tr') as HTMLTableRowElement;

    expect(endpointInput).toHaveFocus();
    expect(secondRow.getAttribute('draggable')).toBe('false');

    await user.click(secondRow);

    expect(screen.getByLabelText('Select https://first-backend.example.test')).not.toBeChecked();
    expect(screen.getByLabelText('Select https://second-backend.example.test')).toBeChecked();
  });

  it('cancels an empty add-backend edit on blur without validation noise', async () => {
    const user = userEvent.setup();
    queueInitialLocalSelection(fetch as unknown as ReturnType<typeof vi.fn>);

    render(<OptimizeAndExportPage />);

    await user.dblClick(await screen.findByText('Double-click to add URL'));
    const addInput = screen.getByPlaceholderText('https://backend.example.test');
    expect(addInput).toHaveFocus();

    await user.tab();

    expect(screen.getByText('Double-click to add URL')).toBeInTheDocument();
    expect(screen.queryByText('Backend URL is required.')).not.toBeInTheDocument();
  });

  it('checks a user-entered endpoint and marks it offline after the health timeout', async () => {
    const user = userEvent.setup();
    const fetchMock = fetch as unknown as ReturnType<typeof vi.fn>;
    queueInitialLocalSelection(fetchMock);

    render(<OptimizeAndExportPage />);

    fetchMock.mockImplementationOnce((_url: string, init?: RequestInit) => {
      return new Promise((_resolve, reject) => {
        init?.signal?.addEventListener('abort', () => {
          reject(new DOMException('The operation was aborted.', 'AbortError'));
        });
      });
    });
    await editBackendEndpoint(user, LOCAL_API_URL, 'https://backend.example.test');

    expect(screen.getByText('Server: Checking')).toBeInTheDocument();

    await waitFor(() => expect(fetch).toHaveBeenCalledWith(
      'https://backend.example.test/health',
      expect.objectContaining({ method: 'GET' })
    ));

    await expect(screen.findByText('Server: Offline', {}, { timeout: 4000 })).resolves.toBeInTheDocument();
  });

  it('keeps endpoint input available but disables manual health checks while initial backend selection is pending', () => {
    const fetchMock = fetch as unknown as ReturnType<typeof vi.fn>;
    fetchMock.mockImplementation((url: string, init?: RequestInit) => {
      if (url === `${LOCAL_API_URL}/health`) {
        return new Promise((_resolve, reject) => {
          init?.signal?.addEventListener('abort', () => {
            reject(new DOMException('The operation was aborted.', 'AbortError'));
          });
        });
      }

      return Promise.reject(new Error(`Unexpected URL: ${url}`));
    });

    render(<OptimizeAndExportPage />);

    expect(screen.getByText('Server: Checking')).toBeInTheDocument();
    expect(screen.getByText('Checking API endpoints...')).toBeInTheDocument();
    expect(screen.getByTitle(LOCAL_API_URL)).toBeInTheDocument();
    expect(screen.getByRole('button', { name: /check backend/i })).toBeEnabled();
  });

  it('does not overwrite a user-entered endpoint when background discovery finishes', async () => {
    const user = userEvent.setup();
    const fetchMock = fetch as unknown as ReturnType<typeof vi.fn>;
    let resolveDiscovery: (response: ReturnType<typeof healthyResponse>) => void = () => undefined;

    fetchMock.mockImplementation((url: string) => {
      if (url === `${LOCAL_API_URL}/health`) {
        return new Promise(resolve => {
          resolveDiscovery = resolve;
        });
      }
      if (url === 'https://backend.example.test/health') {
        return Promise.resolve(healthyResponse({ appVersion: 'custom-backend' }));
      }

      return Promise.reject(new Error(`Unexpected URL: ${url}`));
    });

    render(<OptimizeAndExportPage />);

    await editBackendEndpoint(user, LOCAL_API_URL, 'https://backend.example.test');

    act(() => {
      resolveDiscovery(healthyResponse());
    });

    await waitFor(() => {
      expect(screen.queryByText('Checking API endpoints...')).not.toBeInTheDocument();
    });
    expect(screen.getByTitle('https://backend.example.test')).toBeInTheDocument();
  });

  it('ignores manual health check results for an endpoint that is no longer current', async () => {
    const user = userEvent.setup();
    const fetchMock = fetch as unknown as ReturnType<typeof vi.fn>;
    let resolveManualCheck: (response: ReturnType<typeof healthyResponse>) => void = () => undefined;

    fetchMock.mockImplementation((url: string) => {
      if (url === `${LOCAL_API_URL}/health`) {
        return Promise.resolve(healthyResponse());
      }
      if (url === 'https://backend.example.test/health') {
        return new Promise(resolve => {
          resolveManualCheck = resolve;
        });
      }
      if (url === 'https://next-backend.example.test/health') {
        return new Promise(() => undefined);
      }
      if (url.startsWith('https://') && url.endsWith('/health')) {
        return new Promise(() => undefined);
      }

      return Promise.reject(new Error(`Unexpected URL: ${url}`));
    });

    render(<OptimizeAndExportPage />);
    await screen.findByText('Server: Online');

    await editBackendEndpoint(user, LOCAL_API_URL, 'https://backend.example.test');
    await editBackendEndpoint(user, 'https://backend.example.test', 'https://next-backend.example.test');

    act(() => {
      resolveManualCheck(healthyResponse({ appVersion: 'custom-backend' }));
    });

    await waitFor(() => {
      expect(screen.getByTitle('https://next-backend.example.test')).toBeInTheDocument();
    });
    expect(screen.getByText('Server: Checking')).toBeInTheDocument();
  });

  it('warns when frontend and backend versions differ', async () => {
    (fetch as unknown as ReturnType<typeof vi.fn>).mockResolvedValue({
      ok: true,
      json: vi.fn().mockResolvedValue({
        status: 'ok',
        version: 'alpha',
        apiVersion: 'alpha',
        appVersion: 'backend-test',
      }),
    });

    render(<OptimizeAndExportPage />);

    await expect(screen.findByText(/frontend and backend versions do not match/i)).resolves.toBeInTheDocument();
  });

  it('does not warn when frontend and backend versions match', async () => {
    (fetch as unknown as ReturnType<typeof vi.fn>).mockResolvedValue({
      ok: true,
      json: vi.fn().mockResolvedValue({
        status: 'ok',
        version: 'alpha',
        apiVersion: 'alpha',
        appVersion: 'frontend-test',
      }),
    });

    render(<OptimizeAndExportPage />);

    await expect(screen.findByText('Server: Online')).resolves.toBeInTheDocument();
    expect(screen.queryByText(/frontend and backend versions do not match/i)).not.toBeInTheDocument();
  });

  it('warns when frontend and backend versions match but are dirty', async () => {
    mockCurrentAppVersion.value = 'frontend-test-dirty';
    (fetch as unknown as ReturnType<typeof vi.fn>).mockResolvedValue({
      ok: true,
      json: vi.fn().mockResolvedValue({
        status: 'ok',
        version: 'alpha',
        apiVersion: 'alpha',
        appVersion: 'frontend-test-dirty',
      }),
    });

    render(<OptimizeAndExportPage />);

    await expect(screen.findByText(/frontend and backend versions do not match/i)).resolves.toBeInTheDocument();
  });

  it('shows a backend check failure message', async () => {
    (fetch as unknown as ReturnType<typeof vi.fn>).mockRejectedValue(new Error('network failed'));

    render(<OptimizeAndExportPage />);

    await expect(screen.findByText('Server: Offline')).resolves.toBeInTheDocument();
    expect(screen.getByText(/backend is not responding at the configured endpoint/i)).toBeInTheDocument();
    expect(screen.getByRole('button', { name: /optimize and download/i })).toBeDisabled();
    expect(screen.getByText(/backend unavailable/i)).toBeInTheDocument();
  });

  it('creates an optimization job, downloads the XLSX, and deletes the job', async () => {
    const user = userEvent.setup();
    const appendChildSpy = vi.spyOn(document.body, 'appendChild');
    const removeChildSpy = vi.spyOn(document.body, 'removeChild');

    queueInitialLocalSelection(fetch as unknown as ReturnType<typeof vi.fn>)
      .mockResolvedValueOnce({
        ok: true,
        json: vi.fn().mockResolvedValue({
          jobId: 'opt_test',
          status: 'queued',
          score: null,
          solverStatus: null,
          error: null,
          xlsxReady: false,
          links: {
            status: '/optimize/opt_test',
            events: '/optimize/opt_test/events',
            xlsx: '/optimize/opt_test/xlsx',
          },
        }),
      })
      .mockResolvedValueOnce({
        ok: true,
        json: vi.fn().mockResolvedValue({
          jobId: 'opt_test',
          status: 'optimal',
          score: 42000,
          solverStatus: 'OPTIMAL',
          error: null,
          xlsxReady: true,
          links: {
            status: '/optimize/opt_test',
            events: '/optimize/opt_test/events',
            xlsx: '/optimize/opt_test/xlsx',
          },
        }),
      })
      .mockResolvedValueOnce({
        ok: true,
        blob: vi.fn().mockResolvedValue(new Blob(['xlsx'])),
        headers: new Headers({
          'Content-Disposition': 'attachment; filename=schedule.xlsx',
        }),
      })
      .mockResolvedValueOnce({
        ok: true,
      });

    render(<OptimizeAndExportPage />);
    await user.click(screen.getByRole('button', { name: /optimize and download/i }));

    await expect(screen.findByText('Schedule optimized and downloaded successfully!')).resolves.toBeInTheDocument();
    expect(screen.getByText('schedule.xlsx')).toBeInTheDocument();
    expect(screen.getByText('42,000')).toBeInTheDocument();
    expect(screen.getByText('OPTIMAL')).toBeInTheDocument();

    expect(fetch).toHaveBeenCalledWith('http://localhost:8000/optimize', expect.objectContaining({ method: 'POST' }));
    expect(fetch).toHaveBeenCalledWith(
      'http://localhost:8000/optimize/opt_test',
      expect.objectContaining({ method: 'GET' })
    );
    expect(fetch).toHaveBeenCalledWith(
      'http://localhost:8000/optimize/opt_test/xlsx',
      expect.objectContaining({ method: 'GET' })
    );
    expect(fetch).toHaveBeenCalledWith(
      'http://localhost:8000/optimize/opt_test',
      expect.objectContaining({ method: 'DELETE' })
    );
    expect(appendChildSpy).toHaveBeenCalled();
    expect(removeChildSpy).toHaveBeenCalled();

    const appendCallCount = appendChildSpy.mock.calls.length;
    const removeCallCount = removeChildSpy.mock.calls.length;
    await user.click(screen.getByRole('button', { name: /download again/i }));
    expect(appendChildSpy).toHaveBeenCalledTimes(appendCallCount + 1);
    expect(removeChildSpy).toHaveBeenCalledTimes(removeCallCount + 1);
  });

  it('anonymizes schedule data by default and restores people IDs in the XLSX', async () => {
    const user = userEvent.setup();
    const xlsxBlob = new Blob(['xlsx']);
    mockUseSchedulingData.mockReturnValue(createSchedulingData({
      descriptionData: 'sensitive schedule',
      peopleData: { items: [{ id: 'Alice', description: 'sensitive person', history: [] }], groups: [], history: [] },
    }));

    queueInitialLocalSelection(fetch as unknown as ReturnType<typeof vi.fn>)
      .mockResolvedValueOnce({
        ok: true,
        json: vi.fn().mockResolvedValue({
          jobId: 'opt_anonymous',
          status: 'optimal',
          score: 1,
          solverStatus: 'OPTIMAL',
          error: null,
          xlsxReady: true,
          links: {
            status: '/optimize/opt_anonymous',
            events: '/optimize/opt_anonymous/events',
            xlsx: '/optimize/opt_anonymous/xlsx',
          },
        }),
      })
      .mockResolvedValueOnce({
        ok: true,
        blob: vi.fn().mockResolvedValue(xlsxBlob),
        headers: new Headers(),
      })
      .mockResolvedValueOnce({ ok: true });

    render(<OptimizeAndExportPage />);
    expect(screen.getByRole('checkbox', { name: /anonymize schedule data/i })).toBeChecked();
    await user.click(screen.getByRole('button', { name: /optimize and download/i }));
    await screen.findByText('Schedule optimized and downloaded successfully!');

    const submittedState = mockGenerateYamlFromState.mock.lastCall?.[0];
    expect(submittedState).toEqual(
      expect.objectContaining({
        people: expect.objectContaining({
          items: [{ id: 'P1', history: [] }],
        }),
      })
    );
    expect(submittedState).not.toHaveProperty('description');
    expect(submittedState.people.items[0]).not.toHaveProperty('description');
    expect(mockRestorePeopleIdsInXlsx).toHaveBeenCalledWith(xlsxBlob, new Map([['P1', 'Alice']]), 1);
  });

  it('sends and downloads original people IDs when anonymization is disabled', async () => {
    const user = userEvent.setup();
    const xlsxBlob = new Blob(['xlsx']);
    mockUseSchedulingData.mockReturnValue(createSchedulingData({
      descriptionData: 'sensitive schedule',
      peopleData: { items: [{ id: 'Alice', description: 'sensitive person', history: [] }], groups: [], history: [] },
    }));

    queueInitialLocalSelection(fetch as unknown as ReturnType<typeof vi.fn>)
      .mockResolvedValueOnce({
        ok: true,
        json: vi.fn().mockResolvedValue({
          jobId: 'opt_named',
          status: 'optimal',
          score: 1,
          solverStatus: 'OPTIMAL',
          error: null,
          xlsxReady: true,
          links: {
            status: '/optimize/opt_named',
            events: '/optimize/opt_named/events',
            xlsx: '/optimize/opt_named/xlsx',
          },
        }),
      })
      .mockResolvedValueOnce({
        ok: true,
        blob: vi.fn().mockResolvedValue(xlsxBlob),
        headers: new Headers(),
      })
      .mockResolvedValueOnce({ ok: true });

    render(<OptimizeAndExportPage />);
    await user.click(screen.getByRole('checkbox', { name: /anonymize schedule data/i }));
    await user.click(screen.getByRole('button', { name: /optimize and download/i }));
    await screen.findByText('Schedule optimized and downloaded successfully!');

    expect(mockGenerateYamlFromState).toHaveBeenLastCalledWith(
      expect.objectContaining({
        people: expect.objectContaining({
          items: [expect.objectContaining({ id: 'Alice' })],
        }),
      })
    );
    expect(mockRestorePeopleIdsInXlsx).not.toHaveBeenCalled();
  });

  it('shows all received SSE event types in the optimization event log', async () => {
    const user = userEvent.setup();
    vi.stubGlobal('EventSource', MockEventSource);

    queueInitialLocalSelection(fetch as unknown as ReturnType<typeof vi.fn>)
      .mockResolvedValueOnce({
        ok: true,
        json: vi.fn().mockResolvedValue({
          jobId: 'opt_sse',
          status: 'queued',
          score: null,
          solverStatus: null,
          error: null,
          xlsxReady: false,
          links: {
            status: '/optimize/opt_sse',
            events: '/optimize/opt_sse/events',
            xlsx: '/optimize/opt_sse/xlsx',
          },
        }),
      })
      .mockResolvedValueOnce({
        ok: true,
        blob: vi.fn().mockResolvedValue(new Blob(['xlsx'])),
        headers: new Headers({
          'Content-Disposition': 'attachment; filename=schedule.xlsx',
        }),
      })
      .mockResolvedValueOnce({
        ok: true,
      });

    render(<OptimizeAndExportPage />);
    await user.click(screen.getByRole('button', { name: /optimize and download/i }));
    await waitFor(() => expect(MockEventSource.instances).toHaveLength(1));

    const eventSource = MockEventSource.instances[0];
    expect(eventSource.url).toBe('http://localhost:8000/optimize/opt_sse/events');
    act(() => {
      eventSource.emit('status', { status: 'running' });
      eventSource.emit('phase', {
        source: 'scheduler:phase',
        code: 'creating_shift_variables',
        message: 'Creating shift variables',
        elapsedSeconds: 0.12,
      });
      eventSource.emit('progress', {
        source: 'ortools/cp-sat:solution-callback',
        currentBestScore: 12000,
        elapsedSeconds: 0.1,
        solutionIndex: 2,
        commentCount: 5,
      });
    });

    expect(screen.queryByRole('img', { name: /optimization progress chart/i })).not.toBeInTheDocument();

    act(() => {
      eventSource.emit('progress', {
        source: 'ortools/cp-sat:solution-callback',
        currentBestScore: 10,
        elapsedSeconds: 0.2,
        solutionIndex: 3,
        commentCount: 3,
      });
      eventSource.emit('complete', {
        jobId: 'opt_sse',
        status: 'optimal',
        score: 42,
        solverStatus: 'OPTIMAL',
        error: null,
        xlsxReady: true,
        links: {
          status: '/optimize/opt_sse',
          events: '/optimize/opt_sse/events',
          xlsx: '/optimize/opt_sse/xlsx',
        },
      });
    });

    await expect(screen.findByText('Schedule optimized and downloaded successfully!')).resolves.toBeInTheDocument();
    expect(screen.getByText('status')).toBeInTheDocument();
    expect(screen.getByText('phase')).toBeInTheDocument();
    expect(screen.getAllByText('Creating shift variables').length).toBeGreaterThan(0);
    expect(screen.getAllByText('progress')).toHaveLength(2);
    expect(screen.getByText('complete')).toBeInTheDocument();
    expect(screen.getAllByText(/Comments: 5/).length).toBeGreaterThan(0);
    expect(screen.getAllByText(/Score: 12,000/).length).toBeGreaterThan(0);
    expect(screen.getByText(/"currentBestScore":12000/)).toBeInTheDocument();
    expect(screen.getByRole('img', { name: /optimization progress chart/i })).toBeInTheDocument();
    expect(eventSource.close).toHaveBeenCalled();
  });

  it('shows queued position updates received through SSE', async () => {
    const user = userEvent.setup();
    vi.stubGlobal('EventSource', MockEventSource);

    queueInitialLocalSelection(fetch as unknown as ReturnType<typeof vi.fn>)
      .mockResolvedValueOnce({
        ok: true,
        json: vi.fn().mockResolvedValue({
          jobId: 'opt_queued',
          status: 'queued',
          queuePosition: 3,
          score: null,
          solverStatus: null,
          error: null,
          xlsxReady: false,
          links: {
            status: '/optimize/opt_queued',
            events: '/optimize/opt_queued/events',
            xlsx: '/optimize/opt_queued/xlsx',
          },
        }),
      });

    render(<OptimizeAndExportPage />);
    await user.click(screen.getByRole('button', { name: /optimize and download/i }));
    await waitFor(() => expect(MockEventSource.instances).toHaveLength(1));

    expect(screen.getByText('Queued, position 3')).toBeInTheDocument();
    expect(screen.getByText('Waiting in optimization queue at position 3.')).toBeInTheDocument();

    act(() => {
      MockEventSource.instances[0].emit('status', { status: 'queued', queuePosition: 2 });
    });

    expect(screen.getByText('Queued, position 2')).toBeInTheDocument();
    expect(screen.getByText('Waiting in optimization queue at position 2.')).toBeInTheDocument();

    act(() => {
      MockEventSource.instances[0].emit('status', { status: 'running', queuePosition: null });
    });

    expect(screen.getByText('running')).toBeInTheDocument();
    expect(screen.getByText('Waiting for first feasible solution...')).toBeInTheDocument();
  });

  it('sends heartbeats while an optimization job is active', async () => {
    const user = userEvent.setup();
    vi.stubGlobal('EventSource', MockEventSource);
    const setIntervalSpy = vi.spyOn(window, 'setInterval');
    const fetchMock = fetch as unknown as ReturnType<typeof vi.fn>;
    queueInitialLocalSelection(fetchMock)
      .mockResolvedValueOnce({
        ok: true,
        json: vi.fn().mockResolvedValue({
          jobId: 'opt_heartbeat',
          status: 'queued',
          queuePosition: 1,
          score: null,
          solverStatus: null,
          error: null,
          xlsxReady: false,
          links: {
            status: '/optimize/opt_heartbeat',
            events: '/optimize/opt_heartbeat/events',
            xlsx: '/optimize/opt_heartbeat/xlsx',
          },
        }),
      })
      .mockResolvedValue({ ok: true });

    render(<OptimizeAndExportPage />);
    await user.click(screen.getByRole('button', { name: /optimize and download/i }));
    await waitFor(() => expect(MockEventSource.instances).toHaveLength(1));

    const heartbeatCallback = setIntervalSpy.mock.calls.find(([, delay]) => delay === 10_000)?.[0];
    expect(heartbeatCallback).toBeDefined();

    act(() => {
      (heartbeatCallback as TimerHandler)();
    });

    expect(fetch).toHaveBeenCalledWith(
      'http://localhost:8000/optimize/opt_heartbeat/heartbeat',
      expect.objectContaining({ method: 'POST', cache: 'no-store' })
    );
  });

  it('disables endpoint editing while an optimization job is active', async () => {
    const user = userEvent.setup();
    vi.stubGlobal('EventSource', MockEventSource);
    const setIntervalSpy = vi.spyOn(window, 'setInterval');
    const fetchMock = fetch as unknown as ReturnType<typeof vi.fn>;
    queueInitialLocalSelection(fetchMock)
      .mockResolvedValueOnce({
        ok: true,
        json: vi.fn().mockResolvedValue({
          jobId: 'opt_active',
          status: 'queued',
          queuePosition: 1,
          score: null,
          solverStatus: null,
          error: null,
          xlsxReady: false,
          links: {
            status: '/optimize/opt_active',
            events: '/optimize/opt_active/events',
            xlsx: '/optimize/opt_active/xlsx',
          },
        }),
      })
      .mockResolvedValue({ ok: true });

    render(<OptimizeAndExportPage />);
    await expect(screen.findByTitle(LOCAL_API_URL)).resolves.toBeInTheDocument();
    await user.click(screen.getByRole('button', { name: /optimize and download/i }));
    await waitFor(() => expect(MockEventSource.instances).toHaveLength(1));

    expect(MockEventSource.instances[0].url).toBe(`${LOCAL_API_URL}/optimize/opt_active/events`);

    await user.dblClick(screen.getByTitle(LOCAL_API_URL));
    expect(screen.queryByDisplayValue(LOCAL_API_URL)).not.toBeInTheDocument();

    const heartbeatCallback = setIntervalSpy.mock.calls.find(([, delay]) => delay === 10_000)?.[0];
    expect(heartbeatCallback).toBeDefined();

    act(() => {
      (heartbeatCallback as TimerHandler)();
    });

    expect(fetch).toHaveBeenCalledWith(
      `${LOCAL_API_URL}/optimize/opt_active/heartbeat`,
      expect.objectContaining({ method: 'POST', cache: 'no-store' })
    );
  });

  it('keeps a dropped SSE stream open for automatic reconnection', async () => {
    const user = userEvent.setup();
    vi.stubGlobal('EventSource', MockEventSource);
    const appendChildSpy = vi.spyOn(document.body, 'appendChild');
    const removeChildSpy = vi.spyOn(document.body, 'removeChild');

    queueInitialLocalSelection(fetch as unknown as ReturnType<typeof vi.fn>)
      .mockResolvedValueOnce({
        ok: true,
        json: vi.fn().mockResolvedValue({
          jobId: 'opt_sse_drop',
          status: 'queued',
          score: null,
          solverStatus: null,
          error: null,
          xlsxReady: false,
          links: {
            status: '/optimize/opt_sse_drop',
            events: '/optimize/opt_sse_drop/events',
            xlsx: '/optimize/opt_sse_drop/xlsx',
          },
        }),
      })
      .mockResolvedValueOnce({
        ok: true,
        blob: vi.fn().mockResolvedValue(new Blob(['xlsx'])),
        headers: new Headers({
          'Content-Disposition': 'attachment; filename=recovered.xlsx',
        }),
      })
      .mockResolvedValueOnce({
        ok: true,
      });

    render(<OptimizeAndExportPage />);
    await user.click(screen.getByRole('button', { name: /optimize and download/i }));
    await waitFor(() => expect(MockEventSource.instances).toHaveLength(1));

    act(() => {
      MockEventSource.instances[0].listeners.get('error')?.forEach(listener => {
        listener(new Event('error') as MessageEvent);
      });
    });

    expect(screen.getByText('Optimization event stream disconnected; waiting to reconnect')).toBeInTheDocument();
    expect(MockEventSource.instances[0].close).not.toHaveBeenCalled();

    act(() => {
      MockEventSource.instances[0].emit('complete', {
        jobId: 'opt_sse_drop',
        status: 'optimal',
        score: 77,
        solverStatus: 'OPTIMAL',
        error: null,
        xlsxReady: true,
        links: {
          status: '/optimize/opt_sse_drop',
          events: '/optimize/opt_sse_drop/events',
          xlsx: '/optimize/opt_sse_drop/xlsx',
        },
      });
    });

    await expect(screen.findByText('Schedule optimized and downloaded successfully!')).resolves.toBeInTheDocument();
    expect(screen.getByText('recovered.xlsx')).toBeInTheDocument();
    expect(appendChildSpy).toHaveBeenCalled();
    expect(removeChildSpy).toHaveBeenCalled();
    expect(MockEventSource.instances[0].close).toHaveBeenCalled();
  });

  it('can request current results or cancel an active SSE job', async () => {
    const user = userEvent.setup();
    vi.stubGlobal('EventSource', MockEventSource);

    queueInitialLocalSelection(fetch as unknown as ReturnType<typeof vi.fn>)
      .mockResolvedValueOnce({
        ok: true,
        json: vi.fn().mockResolvedValue({
          jobId: 'opt_control',
          status: 'queued',
          score: null,
          solverStatus: null,
          error: null,
          xlsxReady: false,
          links: {
            status: '/optimize/opt_control',
            events: '/optimize/opt_control/events',
            xlsx: '/optimize/opt_control/xlsx',
          },
        }),
      })
      .mockResolvedValueOnce({
        ok: true,
        json: vi.fn().mockResolvedValue({
          jobId: 'opt_control',
          status: 'running',
          score: null,
          solverStatus: null,
          error: null,
          finishNowRequested: true,
          xlsxReady: false,
          links: {
            status: '/optimize/opt_control',
            events: '/optimize/opt_control/events',
            xlsx: '/optimize/opt_control/xlsx',
          },
        }),
      })
      .mockResolvedValueOnce({
        ok: true,
        json: vi.fn().mockResolvedValue({
          jobId: 'opt_control',
          status: 'cancelling',
          score: null,
          solverStatus: null,
          error: null,
          cancelRequested: true,
          xlsxReady: false,
          links: {
            status: '/optimize/opt_control',
            events: '/optimize/opt_control/events',
            xlsx: '/optimize/opt_control/xlsx',
          },
        }),
      });

    render(<OptimizeAndExportPage />);
    await user.click(screen.getByRole('button', { name: /optimize and download/i }));
    await waitFor(() => expect(MockEventSource.instances).toHaveLength(1));

    act(() => {
      MockEventSource.instances[0].emit('status', { status: 'running' });
    });

    await user.click(screen.getByRole('button', { name: /get results now/i }));
    expect(fetch).toHaveBeenCalledWith(
      'http://localhost:8000/optimize/opt_control/finish-now',
      expect.objectContaining({ method: 'POST' })
    );

    await user.click(screen.getByRole('button', { name: /^cancel$/i }));
    expect(fetch).toHaveBeenCalledWith(
      'http://localhost:8000/optimize/opt_control/cancel',
      expect.objectContaining({ method: 'POST' })
    );

    act(() => {
      MockEventSource.instances[0].emit('complete', {
        jobId: 'opt_control',
        status: 'cancelled',
        score: null,
        solverStatus: null,
        error: 'Optimization cancelled.',
        xlsxReady: false,
        links: {
          status: '/optimize/opt_control',
          events: '/optimize/opt_control/events',
          xlsx: '/optimize/opt_control/xlsx',
        },
      });
    });

    await expect(screen.findByText('Optimization cancelled.')).resolves.toBeInTheDocument();
  });

  it('keeps the optimization event log pinned to bottom when new events arrive at bottom', async () => {
    const user = userEvent.setup();
    vi.stubGlobal('EventSource', MockEventSource);

    queueInitialLocalSelection(fetch as unknown as ReturnType<typeof vi.fn>)
      .mockResolvedValueOnce({
        ok: true,
        json: vi.fn().mockResolvedValue({
          jobId: 'opt_scroll',
          status: 'queued',
          score: null,
          solverStatus: null,
          error: null,
          xlsxReady: false,
          links: {
            status: '/optimize/opt_scroll',
            events: '/optimize/opt_scroll/events',
            xlsx: '/optimize/opt_scroll/xlsx',
          },
        }),
      });

    render(<OptimizeAndExportPage />);
    await user.click(screen.getByRole('button', { name: /optimize and download/i }));
    await waitFor(() => expect(MockEventSource.instances).toHaveLength(1));

    const eventLog = screen.getByTestId('optimization-events-log');
    Object.defineProperty(eventLog, 'clientHeight', { configurable: true, value: 100 });
    Object.defineProperty(eventLog, 'scrollHeight', { configurable: true, value: 100 });
    eventLog.scrollTop = 0;

    act(() => {
      MockEventSource.instances[0].emit('status', { status: 'running' });
    });

    expect(eventLog.scrollTop).toBe(100);
  });

  it('does not move the optimization event log when new events arrive while scrolled up', async () => {
    const user = userEvent.setup();
    vi.stubGlobal('EventSource', MockEventSource);

    queueInitialLocalSelection(fetch as unknown as ReturnType<typeof vi.fn>)
      .mockResolvedValueOnce({
        ok: true,
        json: vi.fn().mockResolvedValue({
          jobId: 'opt_scroll',
          status: 'queued',
          score: null,
          solverStatus: null,
          error: null,
          xlsxReady: false,
          links: {
            status: '/optimize/opt_scroll',
            events: '/optimize/opt_scroll/events',
            xlsx: '/optimize/opt_scroll/xlsx',
          },
        }),
      });

    render(<OptimizeAndExportPage />);
    await user.click(screen.getByRole('button', { name: /optimize and download/i }));
    await waitFor(() => expect(MockEventSource.instances).toHaveLength(1));

    const eventLog = screen.getByTestId('optimization-events-log');
    Object.defineProperty(eventLog, 'clientHeight', { configurable: true, value: 100 });
    Object.defineProperty(eventLog, 'scrollHeight', { configurable: true, value: 300 });
    eventLog.scrollTop = 50;

    act(() => {
      MockEventSource.instances[0].emit('status', { status: 'running' });
    });

    expect(eventLog.scrollTop).toBe(50);
  });

  it('forbids sending and instructs users to set dates when date data is empty', async () => {
    const user = userEvent.setup();
    mockUseSchedulingData.mockReturnValue(createSchedulingData({
      dateData: { range: { startDate: undefined, endDate: undefined }, items: [], groups: [] },
    }));

    render(<OptimizeAndExportPage />);

    expect(screen.getByText(/Please set up your dates first by visiting the/i)).toBeInTheDocument();
    expect(screen.getByRole('link', { name: 'Dates' })).toHaveAttribute('href', '/dates');

    const optimizeButton = screen.getByRole('button', { name: /optimize and download/i });
    expect(optimizeButton).toBeDisabled();
    await user.click(optimizeButton);

    expect(fetch).not.toHaveBeenCalledWith('http://localhost:8000/optimize', expect.anything());
  });

  it('forbids sending and instructs users to set people when people data is empty', async () => {
    const user = userEvent.setup();
    mockUseSchedulingData.mockReturnValue(createSchedulingData({
      peopleData: { items: [], groups: [], history: [] },
    }));

    render(<OptimizeAndExportPage />);

    expect(screen.getByText(/Please set up your people first by visiting the/i)).toBeInTheDocument();
    expect(screen.getByRole('link', { name: 'People' })).toHaveAttribute('href', '/people');

    const optimizeButton = screen.getByRole('button', { name: /optimize and download/i });
    expect(optimizeButton).toBeDisabled();
    await user.click(optimizeButton);

    expect(fetch).not.toHaveBeenCalledWith('http://localhost:8000/optimize', expect.anything());
  });

  it('forbids sending and instructs users to set shift types when shift type data is empty', async () => {
    const user = userEvent.setup();
    mockUseSchedulingData.mockReturnValue(createSchedulingData({
      shiftTypeData: { items: [], groups: [] },
    }));

    render(<OptimizeAndExportPage />);

    expect(screen.getByText(/Please set up your shift types first by visiting the/i)).toBeInTheDocument();
    expect(screen.getByRole('link', { name: 'Shift Types' })).toHaveAttribute('href', '/shift-types');

    const optimizeButton = screen.getByRole('button', { name: /optimize and download/i });
    expect(optimizeButton).toBeDisabled();
    await user.click(optimizeButton);

    expect(fetch).not.toHaveBeenCalledWith('http://localhost:8000/optimize', expect.anything());
  });
});
