/*
 * This file is part of Nurse Scheduling Project, see <https://github.com/j3soon/nurse-scheduling>.
 *
 * Copyright (C) 2023-2026 Johnson Sun
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

// Helpers for attaching the latest scheduling state to Sentry error events.
'use client';

import type { SchedulingState } from '@/hooks/useSchedulingData';
import { anonymizeSchedulingState } from '@/utils/anonymizeSchedulingState';
import { generateYamlFromState } from '@/utils/yamlGenerator';

let latestSchedulingState: SchedulingState | undefined;
let latestFilterAutoGeneratedState: ((state: SchedulingState) => SchedulingState) | undefined;

export function setLatestSchedulingStateForSentry(
  state: SchedulingState,
  filterAutoGeneratedState: (state: SchedulingState) => SchedulingState
): void {
  latestSchedulingState = state;
  latestFilterAutoGeneratedState = filterAutoGeneratedState;
}

export function getLatestSchedulingYamlForSentry(): string | undefined {
  if (!latestSchedulingState || !latestFilterAutoGeneratedState) {
    return undefined;
  }

  const filteredState = latestFilterAutoGeneratedState(latestSchedulingState);
  const anonymizedState = anonymizeSchedulingState(filteredState, {
    anonymizePeopleItems: true,
    anonymizePeopleGroups: false,
    removeDescriptions: true
  });
  return generateYamlFromState(anonymizedState);
}
