/*
 * This file is part of Nurse Scheduling Project, see <https://github.com/j3soon/nurse-scheduling>.
 *
 * Copyright (C) 2023-2026 Johnson Sun
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

import { addAutoGeneratedToState } from './schedulingGeneratedData';
import { createDefaultState, SchedulingState } from './schedulingState';

const MAX_HISTORY_SIZE = 50;

export interface HistoryState {
  state: SchedulingState;
  history: SchedulingState[];
  currentHistoryIndex: number;
}

export interface HistoryMutationOptions {
  replaceLatestHistoryEntry?: boolean;
}

export function createDefaultHistoryState(): HistoryState {
  const defaultState = addAutoGeneratedToState(createDefaultState());
  return {
    state: defaultState,
    history: [defaultState],
    currentHistoryIndex: 0
  };
}

export function addToHistory(
  currentHistoryState: HistoryState,
  newState: SchedulingState,
  options: HistoryMutationOptions = {}
): HistoryState {
  // Remove any future history if we're not at the end
  const trimmedHistory = currentHistoryState.history.slice(0, currentHistoryState.currentHistoryIndex + 1);

  const newHistory =
    options.replaceLatestHistoryEntry && trimmedHistory.length > 0
      ? [...trimmedHistory.slice(0, -1), newState]
      : [...trimmedHistory, newState];

  // Limit history size
  const limitedHistory = newHistory.length > MAX_HISTORY_SIZE
    ? newHistory.slice(-MAX_HISTORY_SIZE)
    : newHistory;

  const newIndex = limitedHistory.length - 1;

  return {
    state: newState,
    history: limitedHistory,
    currentHistoryIndex: newIndex
  };
}

// Provider-owned implementation. Exported only for typing, tests, and future
