/*
 * This file is part of Nurse Scheduling Project, see <https://github.com/j3soon/nurse-scheduling>.
 *
 * Copyright (C) 2023-2026 Johnson Sun
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

import { Item, Group, DateRange, DataType } from '@/types/scheduling';
import { AUTO_GENERATED_ITEMS, AUTO_GENERATED_GROUPS, filterAutoGenerated } from '@/utils/keywords';
import { normalizeExportConfigOrder } from './schedulingExportConfig';
import { normalizePreferencesOrder } from './schedulingPreferenceOrdering';
import { SchedulingState } from './schedulingState';

export function _generateDateItems(startDate: Date, endDate: Date): Item[] {
  const dates: Item[] = [];

  // Determine ID format based on date range scope
  const sameYear = startDate.getUTCFullYear() === endDate.getUTCFullYear();
  const sameMonth = sameYear && startDate.getUTCMonth() === endDate.getUTCMonth();

  for (let date = new Date(startDate); date <= endDate; date.setUTCDate(date.getUTCDate() + 1)) {
    const dateStr = date.toISOString().split('T')[0];
    const dayName = date.toLocaleDateString('en-US', { weekday: 'long', timeZone: 'UTC' });
    const formattedDate = date.toLocaleDateString('en-US', {
      month: 'short',
      day: 'numeric',
      year: 'numeric',
      timeZone: 'UTC'
    });

    // Generate ID based on date range scope
    let id: string;
    if (sameMonth) {
      id = dateStr.slice(-2); // DD
    } else if (sameYear) {
      id = dateStr.slice(5); // MM-DD
    } else {
      id = dateStr; // YYYY-MM-DD
    }

    dates.push({
      id,
      description: `${dayName}, ${formattedDate}`
    });
  }

  return dates;
}

export function _generateAutoGeneratedItems(dataType: DataType, dateRange?: DateRange): Item[] {
  const autoGeneratedItems: Item[] = [];

  if (dataType === DataType.DATES && dateRange?.startDate && dateRange?.endDate) {
    autoGeneratedItems.push(
      ..._generateDateItems(dateRange.startDate, dateRange.endDate).map(date => ({
        id: date.id,
        description: date.description,
        isAutoGenerated: true
      }))
    );
  }
  autoGeneratedItems.push(
    ...AUTO_GENERATED_ITEMS[dataType].map(autoItem => ({
      id: autoItem.id,
      description: autoItem.description,
      isAutoGenerated: true
    }))
  );

  return autoGeneratedItems;
}

export function _generateAutoGeneratedGroups(dataType: DataType, items: Item[], dateRange?: DateRange): Group[] {
  let filteredItems = filterAutoGenerated(items);
  if (dataType === DataType.DATES && dateRange?.startDate && dateRange?.endDate) {
    filteredItems = _generateDateItems(dateRange.startDate, dateRange.endDate);
  }
  return AUTO_GENERATED_GROUPS[dataType].map(autoGroup => ({
    id: autoGroup.id,
    members: autoGroup.generateMembers(filteredItems, dateRange),
    description: autoGroup.description,
    isAutoGenerated: true
  }));
}

export function filterAutoGeneratedState(state: SchedulingState): SchedulingState {
  return {
    ...state,
    dates: {
      ...state.dates,
      items: filterAutoGenerated(state.dates.items) as Item[],
      groups: filterAutoGenerated(state.dates.groups) as Group[]
    },
    people: {
      items: filterAutoGenerated(state.people.items) as Item[],
      groups: filterAutoGenerated(state.people.groups) as Group[]
    },
    shiftTypes: {
      ...state.shiftTypes,
      items: filterAutoGenerated(state.shiftTypes.items) as Item[],
      groups: filterAutoGenerated(state.shiftTypes.groups) as Group[]
    }
  };
}

export function addAutoGeneratedToState(state: SchedulingState): SchedulingState {
  const filteredState = filterAutoGeneratedState(state);
  return {
    ...state,
    dates: {
      ...state.dates,
      items: [...filteredState.dates.items, ..._generateAutoGeneratedItems(DataType.DATES, state.dates.range)],
      groups: [...filteredState.dates.groups, ..._generateAutoGeneratedGroups(DataType.DATES, state.dates.items, state.dates.range)]
    },
    people: {
      items: [...filteredState.people.items, ..._generateAutoGeneratedItems(DataType.PEOPLE)],
      groups: [...filteredState.people.groups, ..._generateAutoGeneratedGroups(DataType.PEOPLE, state.people.items)]
    },
    shiftTypes: {
      ...state.shiftTypes,
      items: [...filteredState.shiftTypes.items, ..._generateAutoGeneratedItems(DataType.SHIFT_TYPES)],
      groups: [...filteredState.shiftTypes.groups, ..._generateAutoGeneratedGroups(DataType.SHIFT_TYPES, state.shiftTypes.items)]
    }
  };
}

export function normalizeStateForFrontend(state: SchedulingState): SchedulingState {
  const stateWithAutoGenerated = addAutoGeneratedToState(state);
  return {
    ...stateWithAutoGenerated,
    preferences: normalizePreferencesOrder(stateWithAutoGenerated.preferences, stateWithAutoGenerated),
    export: normalizeExportConfigOrder(stateWithAutoGenerated.export, stateWithAutoGenerated),
  };
}

export function replaceDateGroups(existingGroups: Group[], replacementGroups: Group[]): Group[] {
  if (replacementGroups.length === 0) {
    return existingGroups;
  }

  const replacementIds = new Set(replacementGroups.map(group => group.id.toLowerCase()));
  return [
    ...existingGroups.filter(group => !replacementIds.has(group.id.toLowerCase())),
    ...replacementGroups,
  ];
}

// Helper function to convert infinity/-infinity values to safe string representations
