/*
 * This file is part of Nurse Scheduling Project, see <https://github.com/j3soon/nurse-scheduling>.
 *
 * Copyright (C) 2023-2026 Johnson Sun
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

import { Item, Group, ExportConfig, ExportFormatting, ExportExtraColumn, ExportExtraRow } from '@/types/scheduling';
import { ALL, OFF, WEEKDAY, WEEKEND, SATURDAY, SUNDAY, filterAutoGenerated } from '@/utils/keywords';
import { getOrderedEntries, sortIdsByEntryOrder, sortPairsByFirstIdEntryOrder } from '@/utils/entityOrdering';
import { DEFAULT_SEPARATOR_COLOR, FREEDAY, WORKDAY } from './schedulingConstants';
import { SchedulingState } from './schedulingState';

export function normalizeExportFormattingOrder(formatting: ExportFormatting[] | undefined, state: SchedulingState) {
  if (!formatting) return formatting;

  const peopleEntries = getOrderedEntries(state.people);
  const shiftTypeEntries = getOrderedEntries(state.shiftTypes);
  const dateEntries = getOrderedEntries(state.dates);

  return formatting.map(rule => {
    let updatedRule = { ...rule };
    if ('people' in updatedRule) {
      updatedRule = { ...updatedRule, people: sortIdsByEntryOrder(updatedRule.people, peopleEntries) };
    }
    if ('dates' in updatedRule) {
      updatedRule = { ...updatedRule, dates: sortIdsByEntryOrder(updatedRule.dates, dateEntries) };
    }
    if ('shiftTypes' in updatedRule) {
      updatedRule = { ...updatedRule, shiftTypes: sortIdsByEntryOrder(updatedRule.shiftTypes, shiftTypeEntries) };
    }
    return updatedRule;
  });
}

export function normalizeExportExtraColumnsOrder(extraColumns: ExportExtraColumn[] | undefined, state: SchedulingState) {
  if (!extraColumns) return extraColumns;

  const shiftTypeEntries = getOrderedEntries(state.shiftTypes);
  const dateEntries = getOrderedEntries(state.dates);
  return extraColumns.map(rule => ({
    ...rule,
    countShiftTypes: sortIdsByEntryOrder(rule.countShiftTypes, shiftTypeEntries),
    countShiftTypeCoefficients: sortPairsByFirstIdEntryOrder(rule.countShiftTypeCoefficients, shiftTypeEntries),
    countDates: sortIdsByEntryOrder(rule.countDates, dateEntries),
  }));
}

export function normalizeExportExtraRowsOrder(extraRows: ExportExtraRow[] | undefined, state: SchedulingState) {
  if (!extraRows) return extraRows;

  const peopleEntries = getOrderedEntries(state.people);
  const shiftTypeEntries = getOrderedEntries(state.shiftTypes);
  return extraRows.map(rule => ({
    ...rule,
    countShiftTypes: sortIdsByEntryOrder(rule.countShiftTypes, shiftTypeEntries),
    countPeople: sortIdsByEntryOrder(rule.countPeople, peopleEntries),
  }));
}

export function normalizeExportConfigOrder(exportConfig: ExportConfig | undefined, state: SchedulingState) {
  if (!exportConfig) return exportConfig;

  return {
    ...exportConfig,
    formatting: normalizeExportFormattingOrder(exportConfig.formatting, state),
    extraColumns: normalizeExportExtraColumnsOrder(exportConfig.extraColumns, state),
    extraRows: normalizeExportExtraRowsOrder(exportConfig.extraRows, state),
  };
}


export function generateShiftTypeCountExtraColumns(shiftTypes: { items: Item[]; groups: Group[] }): ExportExtraColumn[] {
  const shiftTypeItems = filterAutoGenerated(shiftTypes.items) as Item[];
  const shiftTypeGroups = filterAutoGenerated(shiftTypes.groups) as Group[];

  return [
    ...shiftTypeItems.map((shiftType, index) => ({
      description: '',
      type: 'count' as const,
      header: `${shiftType.id} Count`,
      countShiftTypes: [shiftType.id],
      countDates: [ALL],
      ...(index === shiftTypeItems.length - 1 ? { rightBorderColor: DEFAULT_SEPARATOR_COLOR } : {})
    })),
    ...shiftTypeGroups.map(group => ({
      description: '',
      type: 'count' as const,
      header: `${group.id} Count`,
      countShiftTypes: [group.id],
      countDates: [ALL]
    }))
  ];
}

export function generateShiftTypeCountExtraRows(shiftTypes: { items: Item[]; groups: Group[] }): ExportExtraRow[] {
  const shiftTypeItems = filterAutoGenerated(shiftTypes.items) as Item[];
  const shiftTypeGroups = filterAutoGenerated(shiftTypes.groups) as Group[];

  return [
    ...shiftTypeItems.map((shiftType, index) => ({
      description: '',
      type: 'count' as const,
      header: `${shiftType.id} Count`,
      countShiftTypes: [shiftType.id],
      countPeople: [ALL],
      ...(index === shiftTypeItems.length - 1 ? { bottomBorderColor: DEFAULT_SEPARATOR_COLOR } : {})
    })),
    ...shiftTypeGroups.map(group => ({
      description: '',
      type: 'count' as const,
      header: `${group.id} Count`,
      countShiftTypes: [group.id],
      countPeople: [ALL]
    }))
  ];
}

export function generateExportLayoutConfig(
  shiftTypes: { items: Item[]; groups: Group[] },
  dateGroups: Group[] = []
): ExportConfig {
  const hasWorkdayGroup = dateGroups.some(group => group.id === WORKDAY);
  const hasFreedayGroup = dateGroups.some(group => group.id === FREEDAY);
  const workdayFreedayColumns: ExportExtraColumn[] = [
    ...(hasWorkdayGroup ? [{
      description: '',
      type: 'count' as const,
      header: `OFF (${WORKDAY})`,
      countShiftTypes: [OFF],
      countDates: [WORKDAY]
    }] : []),
    ...(hasFreedayGroup ? [{
      description: '',
      type: 'count' as const,
      header: `OFF (${FREEDAY})`,
      countShiftTypes: [OFF],
      countDates: [FREEDAY]
    }] : [])
  ];
  if (workdayFreedayColumns.length > 0) {
    workdayFreedayColumns[workdayFreedayColumns.length - 1].rightBorderColor = DEFAULT_SEPARATOR_COLOR;
  }

  return {
    formatting: [
      {
        description: 'Show requested shift request target',
        type: 'cell',
        appendText: ' [{shiftType}]',
        people: [ALL],
        dates: [ALL],
        shiftTypes: [ALL, OFF],
        when: {
          preference: {
            types: ['shift request'],
            requestShape: ['person-item-to-date-item'],
            weightRange: [-Infinity, Infinity]
          }
        }
      },
      {
        description: 'Mark unsatisfied shift requests',
        type: 'cell',
        appendText: ' [X]',
        fontColor: '#c00000',
        note: {
          text: 'Weight of unmet single-style request: {totalAbsWeight}'
        },
        people: [ALL],
        dates: [ALL],
        shiftTypes: [ALL, OFF],
        when: {
          preference: {
            types: ['shift request'],
            requestShape: ['person-item-to-date-item'],
            satisfied: false,
            weightRange: [-Infinity, Infinity]
          }
        }
      },
      {
        description: '',
        type: 'history header',
        backgroundColor: '#fefce8'
      },
      {
        description: '',
        type: 'history',
        people: [ALL],
        backgroundColor: '#fefce8'
      },
      {
        description: '',
        type: 'column',
        dates: [SATURDAY, SUNDAY],
        backgroundColor: '#dbeafe'
      },
      {
        description: '',
        type: 'column',
        dates: [SATURDAY],
        rightBorderColor: '#9ca3af'
      },
      ...(hasFreedayGroup ? [{
        description: '',
        type: 'column' as const,
        dates: [FREEDAY],
        backgroundColor: '#dcfce7'
      }] : [])
    ],
    extraColumns: [
      {
        description: '',
        type: 'count',
        header: 'OFF (Total)',
        countShiftTypes: [OFF],
        countDates: [ALL],
        rightBorderColor: DEFAULT_SEPARATOR_COLOR
      },
      ...workdayFreedayColumns,
      {
        description: '',
        type: 'count',
        header: 'OFF (Weekday)',
        countShiftTypes: [OFF],
        countDates: [WEEKDAY]
      },
      {
        description: '',
        type: 'count',
        header: 'OFF (Weekend)',
        countShiftTypes: [OFF],
        countDates: [WEEKEND],
        rightBorderColor: DEFAULT_SEPARATOR_COLOR
      },
      ...generateShiftTypeCountExtraColumns(shiftTypes)
    ],
    extraRows: [
      ...generateShiftTypeCountExtraRows(shiftTypes)
    ]
  };
}
