/*
 * This file is part of Nurse Scheduling Project, see <https://github.com/j3soon/nurse-scheduling>.
 *
 * Copyright (C) 2023-2026 Johnson Sun
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

import { DataType } from '@/types/scheduling';
import { ItemGroupEditorPageData } from '@/components/ItemGroupEditorPage';
import { SchedulingState } from './schedulingState';

export const applyDataUpdate = (
  state: SchedulingState,
  dataType: DataType,
  newData: ItemGroupEditorPageData
): SchedulingState => {
  switch (dataType) {
    case DataType.DATES:
      return {
        ...state,
        dates: {
          ...state.dates,
          // Date items are autogenerated, but the editor passes the current
          // generated item snapshot alongside groups so membership IDs stay in sync.
          items: newData.items,
          groups: newData.groups
        }
      };
    case DataType.PEOPLE:
      return {
        ...state,
        people: newData
      };
    case DataType.SHIFT_TYPES:
      return {
        ...state,
        shiftTypes: newData
      };
  }
};
