/*
 * This file is part of Nurse Scheduling Project, see <https://github.com/j3soon/nurse-scheduling>.
 *
 * Copyright (C) 2023-2026 Johnson Sun
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

import { INFINITY_PLACEHOLDER, NEGATIVE_INFINITY_PLACEHOLDER, STORAGE_KEY, WORKER_NAMESPACE_KEY } from './schedulingConstants';
import { createDefaultHistoryState, HistoryState } from './schedulingHistory';
import { filterAutoGeneratedState, normalizeStateForFrontend } from './schedulingGeneratedData';

// Helper function to convert infinity/-infinity values to safe string representations
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function replaceInfinityValues(obj: any): any {
  if (obj === null || typeof obj !== 'object') {
    if (obj === Infinity) return INFINITY_PLACEHOLDER;
    if (obj === -Infinity) return NEGATIVE_INFINITY_PLACEHOLDER;
    return obj;
  }

  if (Array.isArray(obj)) {
    return obj.map(replaceInfinityValues);
  }

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const result: any = {};
  for (const key in obj) {
    if (obj.hasOwnProperty(key)) {
      result[key] = replaceInfinityValues(obj[key]);
    }
  }
  return result;
}

// Helper function to restore infinity/-infinity values from safe string representations
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function restoreInfinityValues(obj: any): any {
  if (obj === null || typeof obj !== 'object') {
    if (obj === INFINITY_PLACEHOLDER) return Infinity;
    if (obj === NEGATIVE_INFINITY_PLACEHOLDER) return -Infinity;
    return obj;
  }

  if (Array.isArray(obj)) {
    return obj.map(restoreInfinityValues);
  }

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const result: any = {};
  for (const key in obj) {
    if (obj.hasOwnProperty(key)) {
      result[key] = restoreInfinityValues(obj[key]);
    }
  }
  return result;
}

export function loadStateFromStorage(): HistoryState {
  if (typeof window === 'undefined') return createDefaultHistoryState();

  try {
    const stored = localStorage.getItem(getStorageKey());

    if (!stored) return createDefaultHistoryState();

    const parsedHistoryState = restoreInfinityValues(JSON.parse(stored)) as HistoryState;

    for (const state of [...parsedHistoryState.history, parsedHistoryState.state]) {
      state.dates.range.startDate = state.dates.range.startDate ? new Date(state.dates.range.startDate) : undefined;
      state.dates.range.endDate = state.dates.range.endDate ? new Date(state.dates.range.endDate) : undefined;
    }

    const currentState = normalizeStateForFrontend(parsedHistoryState.state);

    return {
      state: currentState,
      history: parsedHistoryState.history.map(normalizeStateForFrontend),
      currentHistoryIndex: Math.max(0, Math.min(parsedHistoryState.currentHistoryIndex || 0, parsedHistoryState.history.length - 1))
    };
  } catch (error) {
    console.error('Failed to load data from localStorage:', error);
    return createDefaultHistoryState();
  }
}

export function saveStateToStorage(historyState: HistoryState): void {
  if (typeof window === 'undefined') return;

  try {
    // Store the complete history state, but exclude auto-generated groups and computed date items
    const historyStateToStore = {
      state: {
        ...filterAutoGeneratedState(historyState.state),
        dates: {
          ...filterAutoGeneratedState(historyState.state).dates,
          range: {
            startDate: historyState.state.dates.range.startDate?.toISOString().split('T')[0],
            endDate: historyState.state.dates.range.endDate?.toISOString().split('T')[0]
          },
          items: undefined  // Don't store computed items
        }
      },
      history: historyState.history.map(state => ({
        ...filterAutoGeneratedState(state),
        dates: {
          ...filterAutoGeneratedState(state).dates,
          range: {
            startDate: state.dates.range.startDate?.toISOString().split('T')[0],
            endDate: state.dates.range.endDate?.toISOString().split('T')[0]
          },
          items: undefined  // Don't store computed items
        }
      })),
      currentHistoryIndex: historyState.currentHistoryIndex
    };

    // Replace infinity values with safe placeholders before JSON.stringify
    const safeHistoryState = replaceInfinityValues(historyStateToStore);
    localStorage.setItem(getStorageKey(), JSON.stringify(safeHistoryState));
  } catch (error) {
    console.error('Failed to save data to localStorage:', error);
  }
}

export function getStorageKey(): string {
  if (typeof window === 'undefined') return STORAGE_KEY;

  const workerNamespace = (window as unknown as { [WORKER_NAMESPACE_KEY]?: string })[WORKER_NAMESPACE_KEY];
  return workerNamespace ? `${STORAGE_KEY}__${workerNamespace}` : STORAGE_KEY;
}
