/*
 * This file is part of Nurse Scheduling Project, see <https://github.com/j3soon/nurse-scheduling>.
 *
 * Copyright (C) 2023-2026 Johnson Sun
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

// React hook for scheduling data management with localStorage
'use client';

import { createContext, createElement, useContext, useState, useEffect, useLayoutEffect, type ReactNode } from 'react';
import { Item, Group, DateRange, ShiftTypeRequirementsPreference, ShiftRequestPreference, ShiftTypeSuccessionsPreference, DataType, Preference, SHIFT_TYPE_REQUIREMENT, SHIFT_REQUEST, SHIFT_TYPE_SUCCESSIONS, SHIFT_COUNT, ExportConfig, ExportFormatting, ExportExtraColumn, ExportExtraRow } from '@/types/scheduling';
import { ItemGroupEditorPageData } from '@/components/ItemGroupEditorPage';
import { isReservedKeyword, API_VERSION, ALL } from '@/utils/keywords';
import { setLatestSchedulingStateForSentry } from '@/utils/sentrySchedulingState';
import { buildSingaporeHolidayGroups, isSingaporeHolidayRangeSupported, SingaporeHolidayEntry } from '@/utils/singaporeHolidays';
import { ERROR_SHOULD_NOT_HAPPEN } from '@/constants/errors';
import { getUniqueCopyLabel } from '@/utils/duplicateLabels';
import { getOrderedEntries } from '@/utils/entityOrdering';
import { hasNestedReferenceIds } from '@/utils/referenceIds';
import { generateExportLayoutConfig, normalizeExportConfigOrder, normalizeExportExtraColumnsOrder, normalizeExportExtraRowsOrder, normalizeExportFormattingOrder } from './schedulingExportConfig';
import { _generateDateItems, addAutoGeneratedToState, filterAutoGeneratedState, replaceDateGroups } from './schedulingGeneratedData';
import { applyDataUpdate } from './schedulingDataUpdate';
import { duplicateEntryWithCopiedDescription } from './schedulingEntryDuplication';
import { HistoryMutationOptions, HistoryState, addToHistory, createDefaultHistoryState } from './schedulingHistory';
import { normalizePreferencesOrder, sortShiftRequestsByEntityOrder } from './schedulingPreferenceOrdering';
import { applyReferencesForIdChange, applyReferencesForIdDeletion } from './schedulingReferenceUpdates';
import { createDefaultState, SchedulingState } from './schedulingState';
import { getStorageKey, loadStateFromStorage, saveStateToStorage } from './schedulingStorage';

export { generateExportLayoutConfig } from './schedulingExportConfig';
export type { SchedulingState } from './schedulingState';

export type SchedulingDataValue = ReturnType<typeof useSchedulingDataInternal>;

const useIsomorphicLayoutEffect = typeof window === 'undefined' ? useEffect : useLayoutEffect;

interface UpdateDateRangeOptions {
  importSingaporeHolidays?: boolean;
  singaporeHolidayEntries?: SingaporeHolidayEntry[];
}

export function useSchedulingDataInternal() {
  const [historyState, setHistoryState] = useState<HistoryState>(createDefaultHistoryState);
  const [hasExternalStorageChange, setHasExternalStorageChange] = useState(false);
  const [yamlImportWarnings, setYamlImportWarnings] = useState<string[]>([]);

  useEffect(() => {
    setLatestSchedulingStateForSentry(historyState.state, filterAutoGeneratedState);
  }, [historyState.state]);

  // Load from localStorage before the browser paints so the default schedule is
  // not briefly exposed when persisted data exists.
  useIsomorphicLayoutEffect(() => {
    setHistoryState(loadStateFromStorage());
  }, []);

  useEffect(() => {
    const handleStorage = (event: StorageEvent) => {
      if (event.storageArea !== localStorage) return;
      if (event.key !== null && event.key !== getStorageKey()) return;
      setHasExternalStorageChange(true);
    };

    window.addEventListener('storage', handleStorage);
    return () => window.removeEventListener('storage', handleStorage);
  }, []);

  // Generic update function that handles both state update and storage
  const updateState = (
    updater: (prevState: SchedulingState) => SchedulingState,
    options: HistoryMutationOptions = {}
  ) => {
    setHistoryState(prevHistoryState => {
      const newState = addAutoGeneratedToState(updater(prevHistoryState.state));
      const newHistoryState = addToHistory(prevHistoryState, newState, options);
      saveStateToStorage(newHistoryState);
      return newHistoryState;
    });
  };

  // Base function to navigate to a specific history index
  const moveHistoryIndex = (delta: number) => {
    setHistoryState(prevHistoryState => {
      const targetIndex = prevHistoryState.currentHistoryIndex + delta;

      // Validate target index bounds
      if (targetIndex < 0 || targetIndex >= prevHistoryState.history.length || targetIndex === prevHistoryState.currentHistoryIndex) {
        return prevHistoryState;
      }

      const targetState = prevHistoryState.history[targetIndex];

      const restoredState = addAutoGeneratedToState(targetState);

      const newHistoryState = {
        ...prevHistoryState,
        state: restoredState,
        currentHistoryIndex: targetIndex
      };

      saveStateToStorage(newHistoryState);
      return newHistoryState;
    });
  };

  // Undo function
  const undo = () => {
    moveHistoryIndex(-1);
  };

  // Redo function
  const redo = () => {
    moveHistoryIndex(1);
  };

  // Global keyboard shortcuts for undo/redo
  useEffect(() => {
    const handleKeyDown = (event: KeyboardEvent) => {
      // Check if Ctrl (or Cmd on Mac) is pressed
      const isCtrlOrCmd = event.ctrlKey || event.metaKey;

      if (!isCtrlOrCmd || event.altKey || event.shiftKey) return;

      // Undo: Ctrl+Z
      if (event.key === 'z') {
        event.preventDefault();
        undo();
        return;
      }

      // Redo: Ctrl+Y
      if (event.key === 'y') {
        event.preventDefault();
        redo();
        return;
      }
    };

    // Add event listener to document
    document.addEventListener('keydown', handleKeyDown);

    // Cleanup function to remove event listener
    return () => {
      document.removeEventListener('keydown', handleKeyDown);
    };
  });

  const updateDateRange = (dateRange: DateRange, options: UpdateDateRangeOptions = {}) => {
    // First, determine which date IDs will be removed
    const currentDateIds = new Set(
      historyState.state.dates.range.startDate && historyState.state.dates.range.endDate
        ? _generateDateItems(historyState.state.dates.range.startDate, historyState.state.dates.range.endDate).map(item => item.id)
        : []
    );

    const newDateIds = new Set(
      dateRange.startDate && dateRange.endDate
        ? _generateDateItems(dateRange.startDate, dateRange.endDate).map(item => item.id)
        : []
    );

    const removedDateIds = [...currentDateIds].filter(id => !newDateIds.has(id));
    const generatedDateItems =
      dateRange.startDate && dateRange.endDate ? _generateDateItems(dateRange.startDate, dateRange.endDate) : [];
    const singaporeEntries = options.singaporeHolidayEntries ?? [];
    const shouldImportSingaporeHolidays =
      options.importSingaporeHolidays === true
      && isSingaporeHolidayRangeSupported(dateRange, singaporeEntries);

    // Update the date range
    updateState(prevState => {
      // Create newGroups by filtering out removed date IDs
      let newGroups = prevState.dates.groups.map(group => ({
        ...group,
        members: group.members.filter(memberId => !removedDateIds.includes(memberId))
      }));

      if (shouldImportSingaporeHolidays) {
        newGroups = replaceDateGroups(newGroups, buildSingaporeHolidayGroups(generatedDateItems, dateRange, singaporeEntries));
      }

      const nextState = {
        ...prevState,
        dates: {
          ...prevState.dates,
          range: dateRange,
          groups: newGroups
          // items will be auto-generated based on the new range
        }
      };
      return applyReferencesForIdDeletion(nextState, DataType.DATES, removedDateIds);
    });
  };


  // Private helper function to update data based on dataType
  const updateData = (
    dataType: DataType,
    newData: ItemGroupEditorPageData,
    options?: { replaceLatestHistoryEntry?: boolean }
  ): void => {
    updateState(prevState => applyDataUpdate(prevState, dataType, newData), options);
  };

  // Reset to defaults
  const createNewState = () => {
    const newState = addAutoGeneratedToState(createDefaultState());
    setYamlImportWarnings([]);
    setHistoryState(prevHistoryState => {
      const newHistoryState = addToHistory(prevHistoryState, newState);
      saveStateToStorage(newHistoryState);
      return newHistoryState;
    });
  };

  const addItem = (
    dataType: DataType,
    data: ItemGroupEditorPageData,
    id: string,
    groupIds: string[],
    description?: string
  ): void => {
    // Check if the ID is a reserved keyword
    if (isReservedKeyword(dataType, id)) {
      console.error(`Cannot add item with ID "${id}" - it is a reserved keyword. ${ERROR_SHOULD_NOT_HAPPEN}`);
      return;
    }

    // Add the item
    const newItem = dataType === DataType.PEOPLE
      ? { id, description: description || '', history: [] }
      : { id, description: description || '' };
    const newItems = [...data.items, newItem];

    // If groupIds is provided, add the item to those groups
    const updatedGroups = data.groups.map(group => {
      if (!groupIds.includes(group.id)) {
        return group;
      }
      const allMembers = [...group.members, id];
      // Sort members based on updated items order
      const sortedMembers = newItems
        .filter(item => allMembers.includes(item.id))
        .map(item => item.id);
      if (allMembers.length !== sortedMembers.length) {
        console.error(`All members length ${allMembers.length} does not match sorted members length ${sortedMembers.length}. ${ERROR_SHOULD_NOT_HAPPEN}`);
        return group;
      }
      return {
        ...group,
        members: sortedMembers
      };
    });

    const newData = { items: newItems, groups: updatedGroups };

    updateData(dataType, newData);
  };

  const addGroup = (
    dataType: DataType,
    data: ItemGroupEditorPageData,
    id: string,
    memberIds: string[],
    description?: string
  ): void => {
    // Check if the ID is a reserved keyword
    if (isReservedKeyword(dataType, id)) {
      console.error(`Cannot add group with ID "${id}" - it is a reserved keyword. ${ERROR_SHOULD_NOT_HAPPEN}`);
      return;
    }

    // Sort members based on items order
    const sortedMembers = data.items
      .filter(item => memberIds.includes(item.id))
      .map(item => item.id);

    if (memberIds.length !== sortedMembers.length) {
      console.error(`Member IDs length ${memberIds.length} does not match sorted members length ${sortedMembers.length}. ${ERROR_SHOULD_NOT_HAPPEN}`);
      return;
    }

    const newGroup = { id, members: sortedMembers, description: description || '' };
    const newGroups = [...data.groups, newGroup];

    const newData = { ...data, groups: newGroups };

    updateData(dataType, newData);
  };

  const duplicateItem = (
    dataType: DataType,
    data: ItemGroupEditorPageData,
    id: string
  ): void => {
    const newId = getUniqueCopyLabel(id, [
      ...data.items.map(item => item.id),
      ...data.groups.map(group => group.id),
    ]);

    if (isReservedKeyword(dataType, newId)) {
      console.error(`Cannot duplicate item with ID "${newId}" - it is a reserved keyword. ${ERROR_SHOULD_NOT_HAPPEN}`);
      return;
    }

    const sourceIndex = data.items.findIndex(item => item.id === id);
    if (sourceIndex === -1) {
      console.error(`Cannot duplicate item with ID "${id}" - item not found. ${ERROR_SHOULD_NOT_HAPPEN}`);
      return;
    }

    const sourceItem = data.items[sourceIndex];
    const duplicatedItem = { ...structuredClone(sourceItem), id: newId };
    const newItems = [
      ...data.items.slice(0, sourceIndex + 1),
      duplicatedItem,
      ...data.items.slice(sourceIndex + 1),
    ];
    const updatedGroups = data.groups.map(group => {
      const memberIndex = group.members.indexOf(id);
      if (memberIndex === -1) {
        return group;
      }

      return {
        ...group,
        members: [
          ...group.members.slice(0, memberIndex + 1),
          newId,
          ...group.members.slice(memberIndex + 1),
        ],
      };
    });

    updateData(dataType, { ...data, items: newItems, groups: updatedGroups });
  };

  const duplicateGroup = (
    dataType: DataType,
    data: ItemGroupEditorPageData,
    id: string
  ): void => {
    const newId = getUniqueCopyLabel(id, [
      ...data.items.map(item => item.id),
      ...data.groups.map(group => group.id),
    ]);

    if (isReservedKeyword(dataType, newId)) {
      console.error(`Cannot duplicate group with ID "${newId}" - it is a reserved keyword. ${ERROR_SHOULD_NOT_HAPPEN}`);
      return;
    }

    const sourceIndex = data.groups.findIndex(group => group.id === id);
    if (sourceIndex === -1) {
      console.error(`Cannot duplicate group with ID "${id}" - group not found. ${ERROR_SHOULD_NOT_HAPPEN}`);
      return;
    }

    const duplicatedGroup = { ...structuredClone(data.groups[sourceIndex]), id: newId };
    const newGroups = [
      ...data.groups.slice(0, sourceIndex + 1),
      duplicatedGroup,
      ...data.groups.slice(sourceIndex + 1),
    ];

    updateData(dataType, { ...data, groups: newGroups });
  };


  // Unified function to update preferences when an ID changes

  // Unified function to update preferences when IDs are deleted


  const updateItem = (
    dataType: DataType,
    data: ItemGroupEditorPageData,
    oldId: string,
    newId: string,
    groupIds?: string[],
    description?: string
  ): void => {
    if (dataType === DataType.DATES && data.items.some(item => item.id === oldId && item.isAutoGenerated)) {
      console.error(`Cannot rename derived date item ID "${oldId}" to "${newId}". ${ERROR_SHOULD_NOT_HAPPEN}`);
      return;
    }

    // Check if the new ID is a reserved keyword
    if (isReservedKeyword(dataType, newId)) {
      console.error(`Cannot update item to ID "${newId}" - it is a reserved keyword. ${ERROR_SHOULD_NOT_HAPPEN}`);
      return;
    }

    // First update the item's ID and description
    const updatedItems = data.items.map(item =>
      item.id === oldId
        ? {
            ...item,
            id: newId,
            description: description !== undefined ? description : item.description
          }
        : item
    );

    // Always update group memberships to reflect the new ID
    const updatedGroups = data.groups.map(group => {
      // Get current members excluding the edited item
      const otherMembers = group.members.filter(id => id !== oldId);

      // Add the item if they should be in this group
      const allMembers = groupIds
        ? (groupIds.includes(group.id) ? [...otherMembers, newId] : otherMembers)
        : (group.members.includes(oldId) ? [...otherMembers, newId] : otherMembers);

      // Sort members based on updated items order
      const sortedMembers = updatedItems
        .filter(item => allMembers.includes(item.id))
        .map(item => item.id);

      if (allMembers.length !== sortedMembers.length) {
        console.error(`All members length ${allMembers.length} does not match sorted members length ${sortedMembers.length}. ${ERROR_SHOULD_NOT_HAPPEN}`);
        return group;
      }

      return {
        ...group,
        members: sortedMembers
      };
    });

    const newData = { items: updatedItems, groups: updatedGroups };

    updateState(prevState => {
      const nextState = applyDataUpdate(prevState, dataType, newData);
      return applyReferencesForIdChange(nextState, dataType, oldId, newId);
    });
  };

  const updateGroup = (
    dataType: DataType,
    data: ItemGroupEditorPageData,
    oldId: string,
    newId: string,
    members?: string[],
    description?: string
  ): void => {
    // Check if the new ID is a reserved keyword
    if (isReservedKeyword(dataType, newId)) {
      console.error(`Cannot update group to ID "${newId}" - it is a reserved keyword. ${ERROR_SHOULD_NOT_HAPPEN}`);
      return;
    }

    const group = data.groups.find(g => g.id === oldId);
    if (!group) {
      console.error(`Group with ID ${oldId} not found. ${ERROR_SHOULD_NOT_HAPPEN}`);
      return;
    }

    // Sort members based on items order
    const sortedMembers = members
      ? data.items
          .filter(item => members.includes(item.id))
          .map(item => item.id)
      : group.members;

    if (members && members.length !== sortedMembers.length) {
      console.error(`Members length ${members.length} does not match sorted members length ${sortedMembers.length}. ${ERROR_SHOULD_NOT_HAPPEN}`);
      return;
    }

    const newGroups = data.groups.map(g =>
      g.id === oldId
        ? {
            ...g,
            id: newId,
            members: sortedMembers,
            description: description !== undefined ? description : g.description
          }
        : g
    );

    const newData = { ...data, groups: newGroups };

    updateState(prevState => {
      const nextState = applyDataUpdate(prevState, dataType, newData);
      return applyReferencesForIdChange(nextState, dataType, oldId, newId);
    });
  };

  const deleteItem = (
    dataType: DataType,
    data: ItemGroupEditorPageData,
    id: string
  ): void => {
    if (isReservedKeyword(dataType, id)) {
      console.error(`Cannot delete item with ID "${id}" - it is a reserved keyword. ${ERROR_SHOULD_NOT_HAPPEN}`);
      return;
    }

    const newItems = data.items.filter(item => item.id !== id);
    const newGroups = data.groups.map(group => ({
      ...group,
      members: group.members.filter(memberId => memberId !== id)
    }));

    const newData = { items: newItems, groups: newGroups };

    updateState(prevState => {
      const nextState = applyDataUpdate(prevState, dataType, newData);
      return applyReferencesForIdDeletion(nextState, dataType, [id]);
    });
  };

  const deleteGroup = (
    dataType: DataType,
    data: ItemGroupEditorPageData,
    id: string
  ): void => {
    if (isReservedKeyword(dataType, id)) {
      console.error(`Cannot delete group with ID "${id}" - it is a reserved keyword. ${ERROR_SHOULD_NOT_HAPPEN}`);
      return;
    }

    const newGroups = data.groups.filter(g => g.id !== id);
    const newData = { ...data, groups: newGroups };

    updateState(prevState => {
      const nextState = applyDataUpdate(prevState, dataType, newData);
      return applyReferencesForIdDeletion(nextState, dataType, [id]);
    });
  };

  const removeItemFromGroup = (
    dataType: DataType,
    data: ItemGroupEditorPageData,
    itemId: string,
    groupId: string
  ): void => {
    if (isReservedKeyword(dataType, groupId)) {
      console.error(`Cannot remove item from group with ID "${groupId}" - it is a reserved keyword. ${ERROR_SHOULD_NOT_HAPPEN}`);
      return;
    }

    const newGroups = data.groups.map(group =>
      group.id === groupId
        ? { ...group, members: group.members.filter(id => id !== itemId) }
        : group
    );

    const newData = { ...data, groups: newGroups };

    updateData(dataType, newData);
  };

  const reorderItems = (
    dataType: DataType,
    data: ItemGroupEditorPageData,
    reorderedItems: Item[]
  ): void => {
    // Sort group members based on items order
    const updatedGroups = data.groups.map(group => ({
      ...group,
      members: reorderedItems
        .filter(item => group.members.includes(item.id))
        .map(item => item.id)
    }));

    const newData = { items: reorderedItems, groups: updatedGroups };

    updateData(dataType, newData);
  };

  const reorderGroups = (
    dataType: DataType,
    data: ItemGroupEditorPageData,
    newGroups: Group[]
  ): void => {
    const newData = { ...data, groups: newGroups };

    updateData(dataType, newData);
  };

  const addPersonHistory = (
    personId: string,
    shiftTypeId: string,
    options: HistoryMutationOptions = {}
  ) => {
    updateState(prevState => {
      const updatedPeople = {
        ...prevState.people,
        items: prevState.people.items.map(person => {
          if (person.id === personId) {
            const newHistory = [shiftTypeId, ...person.history!];
            return { ...person, history: newHistory };
          }
          return person;
        })
      };
      return { ...prevState, people: updatedPeople };
    }, options);
  };

  const updatePersonHistory = (
    personId: string,
    position: number,
    shiftTypeId?: string,
    options: HistoryMutationOptions = {}
  ) => {
    updateState(prevState => {
      const updatedPeople = {
        ...prevState.people,
        items: prevState.people.items.map(person => {
          if (person.id === personId) {
            if (shiftTypeId !== undefined) {
              // Update the specific position
              const newHistory = [...person.history!];
              if (position >= newHistory.length) {
                console.error(`Position ${position} is out of bounds for person ${personId}. ${ERROR_SHOULD_NOT_HAPPEN}`);
                return person;
              }
              newHistory[position] = shiftTypeId;
              return { ...person, history: newHistory };
            } else {
              // Clear all history entries before the specified position
              const newHistory = person.history!.slice(position + 1);
              return { ...person, history: newHistory };
            }
          }
          return person;
        })
      };
      return { ...prevState, people: updatedPeople };
    }, options);
  };

  // Helper functions to work with flattened preferences
  const getPreferencesByType = <T extends Preference>(type: string): T[] => {
    return historyState.state.preferences.filter(pref => pref.type === type) as T[];
  };

  const updatePreferences = (
    newPreferences: Preference[],
    options: HistoryMutationOptions = {}
  ) => {
    updateState(prevState => ({
      ...prevState,
      preferences: normalizePreferencesOrder(newPreferences, prevState)
    }), options);
  };

  const updatePreferencesByType = <T extends Preference>(
    type: string,
    newPreferences: T[],
    options: HistoryMutationOptions = {}
  ) => {
    const otherPreferences = historyState.state.preferences.filter(pref => pref.type !== type);
    if (type === SHIFT_REQUEST) {
      const combinedDateEntries = getOrderedEntries(historyState.state.dates);
      // Sort preferences by person, shift type, weight.
      newPreferences = sortShiftRequestsByEntityOrder(newPreferences as ShiftRequestPreference[], historyState.state) as T[];
      // Sort each preference date array
      (newPreferences as ShiftRequestPreference[]).forEach(pref => {
        if (pref.person.length !== 1) {
          console.error(`A single shift request corresponds to multiple people. ${ERROR_SHOULD_NOT_HAPPEN}`);
          return pref;
        }
        if (pref.shiftType.length !== 1) {
          console.error(`A single shift request corresponds to multiple shift types. ${ERROR_SHOULD_NOT_HAPPEN}`);
          return pref;
        }
        if (pref.date.length === 0) {
          console.error(`A single shift request corresponds to no dates. ${ERROR_SHOULD_NOT_HAPPEN}`);
          return pref;
        }
        pref.date.sort((a, b) => {
          const dateIndexA = combinedDateEntries.findIndex(p => p.id === a);
          const dateIndexB = combinedDateEntries.findIndex(p => p.id === b);
          return dateIndexA - dateIndexB;
        });
      });
    }
    // Sort preferences by type after updating
    const updatedPreferences = normalizePreferencesOrder([...otherPreferences, ...newPreferences], historyState.state);
    updatePreferences(updatedPreferences, options);
  };


  const duplicatePreferenceByType = <T extends Preference>(
    type: string,
    index: number,
    options: HistoryMutationOptions = {}
  ) => {
    const preferencesOfType = getPreferencesByType<T>(type);
    const duplicatedPreferences = duplicateEntryWithCopiedDescription(preferencesOfType, index, type);
    if (!duplicatedPreferences) return;

    updatePreferencesByType(type, duplicatedPreferences, options);
  };

  const updateExportFormatting = (formatting?: ExportFormatting[]) => {
    updateState(prevState => ({
      ...prevState,
      export: {
        ...(prevState.export ?? generateExportLayoutConfig(prevState.shiftTypes, prevState.dates.groups)),
        formatting: normalizeExportFormattingOrder(formatting, prevState)
      }
    }));
  };

  const updateExportExtraColumns = (extraColumns?: ExportExtraColumn[]) => {
    updateState(prevState => ({
      ...prevState,
      export: {
        ...(prevState.export ?? generateExportLayoutConfig(prevState.shiftTypes, prevState.dates.groups)),
        extraColumns: normalizeExportExtraColumnsOrder(extraColumns, prevState)
      }
    }));
  };

  const updateExportExtraRows = (extraRows?: ExportExtraRow[]) => {
    updateState(prevState => ({
      ...prevState,
      export: {
        ...(prevState.export ?? generateExportLayoutConfig(prevState.shiftTypes, prevState.dates.groups)),
        extraRows: normalizeExportExtraRowsOrder(extraRows, prevState)
      }
    }));
  };

  const updateExportConfig = (exportConfig?: ExportConfig) => {
    updateState(prevState => ({
      ...prevState,
      export: normalizeExportConfigOrder(exportConfig, prevState)
    }));
  };

  const duplicateExportFormatting = (index: number) => {
    const exportData = historyState.state.export ?? generateExportLayoutConfig(historyState.state.shiftTypes, historyState.state.dates.groups);
    const duplicatedFormatting = duplicateEntryWithCopiedDescription(exportData.formatting ?? [], index, 'export formatting rule');
    if (!duplicatedFormatting) return;

    updateExportFormatting(duplicatedFormatting);
  };

  const duplicateExportExtraColumn = (index: number) => {
    const exportData = historyState.state.export ?? generateExportLayoutConfig(historyState.state.shiftTypes, historyState.state.dates.groups);
    const duplicatedExtraColumns = duplicateEntryWithCopiedDescription(exportData.extraColumns ?? [], index, 'export extra column');
    if (!duplicatedExtraColumns) return;

    updateExportExtraColumns(duplicatedExtraColumns);
  };

  const duplicateExportExtraRow = (index: number) => {
    const exportData = historyState.state.export ?? generateExportLayoutConfig(historyState.state.shiftTypes, historyState.state.dates.groups);
    const duplicatedExtraRows = duplicateEntryWithCopiedDescription(exportData.extraRows ?? [], index, 'export extra row');
    if (!duplicatedExtraRows) return;

    updateExportExtraRows(duplicatedExtraRows);
  };

  const loadFromYaml = (yamlData: unknown) => {
    // Create new state from YAML data without validation
    // TODO: Add validation
    const importWarnings: string[] = [];

    // Cast to partial SchedulingState to access properties safely
    const data = yamlData as Partial<SchedulingState> & {
      dates?: Partial<SchedulingState['dates']> & {
        range?: Partial<DateRange>;
      };
      people?: Partial<SchedulingState['people']>;
      shiftTypes?: Partial<SchedulingState['shiftTypes']>;
      export?: Partial<ExportConfig>;
    };

    const newState: SchedulingState = addAutoGeneratedToState({
      apiVersion: data.apiVersion || API_VERSION,
      description: data.description || '',
      dates: {
        range: data.dates?.range ? {
          startDate: data.dates.range.startDate ? new Date(data.dates.range.startDate) : undefined,
          endDate: data.dates.range.endDate ? new Date(data.dates.range.endDate) : undefined,
        } : { startDate: undefined, endDate: undefined },
        items: data.dates?.items || [],
        groups: data.dates?.groups || []
      },
      people: {
        items: data.people?.items || [],
        groups: data.people?.groups || []
      },
      shiftTypes: data.shiftTypes || { items: [], groups: [] },
      preferences: data.preferences || [],
      ...(data.export ? { export: data.export } : {})
    });

    // If any ID is a number, convert it to a string
    const convertIdsToString = (arr: { id: number | string }[]) => {
      arr.forEach(obj => {
        if (typeof obj.id === 'number') obj.id = String(obj.id);
      });
    };
    convertIdsToString(newState.dates.items);
    convertIdsToString(newState.dates.groups);
    convertIdsToString(newState.people.items);
    convertIdsToString(newState.people.groups);
    convertIdsToString(newState.shiftTypes.items);
    convertIdsToString(newState.shiftTypes.groups);
    const stringifyReferenceIds = (value: unknown, isDate: boolean = false): unknown => {
      if (Array.isArray(value)) {
        return value.map(item => stringifyReferenceIds(item, isDate));
      }
      if (typeof value === 'number') {
        return isDate ? value.toString().padStart(2, '0') : String(value);
      }
      return value;
    };
    const normalizeReferenceIdsForImport = (value: unknown, path: string, isDate: boolean = false): unknown => {
      if (value === null || value === undefined) return value;

      const normalizedValue = stringifyReferenceIds(value, isDate);
      if (!Array.isArray(normalizedValue)) {
        return [normalizedValue];
      }

      if (hasNestedReferenceIds(normalizedValue)) {
        importWarnings.push(
          `${path} uses advanced backend reference syntax. It was preserved and may not be editable in the web UI without replacing it.`
        );
      }
      return normalizedValue;
    };
    const normalizeRequiredReferenceIdsForImport = (value: unknown, path: string, isDate: boolean = false): unknown => {
      if (value === null || value === undefined) {
        throw new Error(`${path} is required`);
      }
      return normalizeReferenceIdsForImport(value, path, isDate);
    };
    const addUnsupportedFrontendShapeWarning = (path: string) => {
      importWarnings.push(
        `${path} uses backend-compatible syntax that is outside the web UI editing subset. It was preserved and may be replaced if edited in the web UI.`
      );
    };
    newState.preferences.forEach((pref, preferenceIndex) => {
      // The backend permits an omitted date to mean all dates. Require an
      // explicit selector in frontend state to avoid ambiguous form values.
      if (pref.type === SHIFT_TYPE_REQUIREMENT && !('date' in pref)) {
        (pref as ShiftTypeRequirementsPreference).date = [ALL];
      } else if (pref.type === SHIFT_TYPE_SUCCESSIONS && !('date' in pref)) {
        (pref as ShiftTypeSuccessionsPreference).date = [ALL];
      }

      // Type-safe property access with proper type guards
      if ('shiftType' in pref && pref.shiftType) {
        pref.shiftType = normalizeReferenceIdsForImport(pref.shiftType, `preferences[${preferenceIndex}].shiftType`) as typeof pref.shiftType;
      }
      if (pref.type === SHIFT_TYPE_REQUIREMENT && pref.shiftTypeCoefficients) {
        pref.shiftTypeCoefficients = pref.shiftTypeCoefficients.map(([id, coefficient]) => [
          String(id),
          coefficient
        ]);
      }
      if ('qualifiedPeople' in pref && pref.qualifiedPeople) {
        pref.qualifiedPeople = normalizeReferenceIdsForImport(pref.qualifiedPeople, `preferences[${preferenceIndex}].qualifiedPeople`) as typeof pref.qualifiedPeople;
      }
      if ('date' in pref && pref.date) {
        pref.date = normalizeReferenceIdsForImport(pref.date, `preferences[${preferenceIndex}].date`, true) as typeof pref.date;
      }
      if ('person' in pref && pref.person) {
        pref.person = normalizeReferenceIdsForImport(pref.person, `preferences[${preferenceIndex}].person`) as typeof pref.person;
      }
      if ('pattern' in pref && pref.pattern) {
        pref.pattern = normalizeReferenceIdsForImport(pref.pattern, `preferences[${preferenceIndex}].pattern`) as typeof pref.pattern;
      }
      if ('countDates' in pref && pref.countDates) {
        pref.countDates = normalizeReferenceIdsForImport(pref.countDates, `preferences[${preferenceIndex}].countDates`, true) as typeof pref.countDates;
      }
      if ('countShiftTypes' in pref && pref.countShiftTypes) {
        pref.countShiftTypes = normalizeReferenceIdsForImport(pref.countShiftTypes, `preferences[${preferenceIndex}].countShiftTypes`) as typeof pref.countShiftTypes;
      }
      if (pref.type === SHIFT_COUNT && pref.countShiftTypeCoefficients) {
        pref.countShiftTypeCoefficients = pref.countShiftTypeCoefficients.map(([id, coefficient]) => [
          String(id),
          coefficient
        ]);
      }
      if ('people1' in pref && pref.people1) {
        pref.people1 = normalizeReferenceIdsForImport(pref.people1, `preferences[${preferenceIndex}].people1`) as typeof pref.people1;
      }
      if ('people2' in pref && pref.people2) {
        pref.people2 = normalizeReferenceIdsForImport(pref.people2, `preferences[${preferenceIndex}].people2`) as typeof pref.people2;
      }
      if ('shiftTypes' in pref && pref.shiftTypes) {
        pref.shiftTypes = normalizeReferenceIdsForImport(pref.shiftTypes, `preferences[${preferenceIndex}].shiftTypes`) as typeof pref.shiftTypes;
      }

      if (pref.type === SHIFT_REQUEST) {
        if (Array.isArray(pref.person) && pref.person.length !== 1) {
          addUnsupportedFrontendShapeWarning(`preferences[${preferenceIndex}].person`);
        }
        if (Array.isArray(pref.shiftType) && pref.shiftType.length !== 1) {
          addUnsupportedFrontendShapeWarning(`preferences[${preferenceIndex}].shiftType`);
        }
      } else if (pref.type === SHIFT_COUNT) {
        if (Array.isArray(pref.expression)) {
          addUnsupportedFrontendShapeWarning(`preferences[${preferenceIndex}].expression`);
        }
        if (Array.isArray(pref.target)) {
          addUnsupportedFrontendShapeWarning(`preferences[${preferenceIndex}].target`);
        }
      }
    });
    newState.export?.formatting?.forEach(rule => {
      if ('people' in rule) {
        rule.people = normalizeReferenceIdsForImport(rule.people, 'export.formatting[].people') as typeof rule.people;
      }
      if ('dates' in rule) {
        rule.dates = normalizeReferenceIdsForImport(rule.dates, 'export.formatting[].dates', true) as typeof rule.dates;
      }
      if ('shiftTypes' in rule) {
        rule.shiftTypes = normalizeReferenceIdsForImport(rule.shiftTypes, 'export.formatting[].shiftTypes') as typeof rule.shiftTypes;
      }
    });
    newState.export?.extraColumns?.forEach((rule, ruleIndex) => {
      rule.countShiftTypes = normalizeRequiredReferenceIdsForImport(
        rule.countShiftTypes,
        `export.extraColumns[${ruleIndex}].countShiftTypes`
      ) as typeof rule.countShiftTypes;
      if (rule.countShiftTypeCoefficients) {
        rule.countShiftTypeCoefficients = rule.countShiftTypeCoefficients.map(([id, coefficient]) => [
          String(id),
          coefficient
        ]);
      }
      rule.countDates = normalizeRequiredReferenceIdsForImport(
        rule.countDates,
        `export.extraColumns[${ruleIndex}].countDates`,
        true
      ) as typeof rule.countDates;
    });
    newState.export?.extraRows?.forEach((rule, ruleIndex) => {
      rule.countShiftTypes = normalizeRequiredReferenceIdsForImport(
        rule.countShiftTypes,
        `export.extraRows[${ruleIndex}].countShiftTypes`
      ) as typeof rule.countShiftTypes;
      rule.countPeople = normalizeRequiredReferenceIdsForImport(
        rule.countPeople,
        `export.extraRows[${ruleIndex}].countPeople`
      ) as typeof rule.countPeople;
    });
    newState.preferences = normalizePreferencesOrder(newState.preferences, newState);
    newState.export = normalizeExportConfigOrder(newState.export, newState);
    setYamlImportWarnings([...new Set(importWarnings)]);

    // Add to history and update state
    setHistoryState(prevHistoryState => {
      const newHistoryState = addToHistory(prevHistoryState, newState);
      saveStateToStorage(newHistoryState);
      return newHistoryState;
    });
  };

  const effectiveExportData =
    historyState.state.export ?? generateExportLayoutConfig(historyState.state.shiftTypes, historyState.state.dates.groups);

  const reloadFromStorage = () => {
    setHistoryState(loadStateFromStorage());
    setHasExternalStorageChange(false);
    setYamlImportWarnings([]);
  };

  const dismissExternalStorageChange = () => {
    setHasExternalStorageChange(false);
  };

  const dismissYamlImportWarnings = () => {
    setYamlImportWarnings([]);
  };

  return {
    hasExternalStorageChange,
    yamlImportWarnings,
    reloadFromStorage,
    dismissExternalStorageChange,
    dismissYamlImportWarnings,
    updateDateRange,
    apiVersionData: historyState.state.apiVersion,
    descriptionData: historyState.state.description,
    dateData: historyState.state.dates,
    peopleData: historyState.state.people,
    shiftTypeData: historyState.state.shiftTypes,
    preferences: historyState.state.preferences, // Flattened preferences API
    exportData: historyState.state.export,
    effectiveExportData,
    updatePreferences,
    updatePreferencesByType,
    getPreferencesByType,
    duplicatePreferenceByType,
    updateExportFormatting,
    updateExportExtraColumns,
    updateExportExtraRows,
    updateExportConfig,
    duplicateExportFormatting,
    duplicateExportExtraColumn,
    duplicateExportExtraRow,

    addPersonHistory,
    updatePersonHistory,
    createNewState,
    loadFromYaml,
    filterAutoGeneratedState,
    undo,
    redo,
    // Helper functions
    addItem,
    addGroup,
    duplicateItem,
    duplicateGroup,
    updateItem,
    updateGroup,
    deleteItem,
    deleteGroup,
    removeItemFromGroup,
    reorderItems,
    reorderGroups,
  };
}

const SchedulingDataContext = createContext<SchedulingDataValue | null>(null);

function ExternalStorageChangeBanner({
  onReload,
  onDismiss,
}: {
  onReload: () => void;
  onDismiss: () => void;
}) {
  return createElement(
    'div',
    { className: 'border-b border-amber-300 bg-amber-50 px-4 py-2 text-sm text-amber-900' },
    createElement(
      'div',
      { className: 'mx-auto flex max-w-7xl flex-col gap-2 sm:flex-row sm:items-center sm:justify-between' },
      createElement('span', null, 'Schedule data changed in another browser tab.'),
      createElement(
        'div',
        { className: 'flex gap-2' },
        createElement(
          'button',
          {
            type: 'button',
            onClick: onReload,
            className: 'rounded border border-amber-400 bg-white px-3 py-1 font-medium text-amber-900 hover:bg-amber-100',
          },
          'Reload data'
        ),
        createElement(
          'button',
          {
            type: 'button',
            onClick: onDismiss,
            className: 'rounded px-3 py-1 font-medium text-amber-800 hover:bg-amber-100',
          },
          'Dismiss'
        )
      )
    )
  );
}

function YamlImportWarningsBanner({
  warnings,
  onDismiss,
}: {
  warnings: string[];
  onDismiss: () => void;
}) {
  return createElement(
    'div',
    { className: 'border-b border-amber-300 bg-amber-50 px-4 py-2 text-sm text-amber-900' },
    createElement(
      'div',
      { className: 'mx-auto flex max-w-7xl flex-col gap-2 sm:flex-row sm:items-start sm:justify-between' },
      createElement(
        'div',
        null,
        createElement('p', { className: 'font-medium' }, 'Imported YAML contains advanced backend syntax.'),
        createElement(
          'ul',
          { className: 'mt-1 list-disc space-y-1 pl-5' },
          warnings.map(warning => createElement('li', { key: warning }, warning))
        )
      ),
      createElement(
        'button',
        {
          type: 'button',
          onClick: onDismiss,
          className: 'rounded px-3 py-1 font-medium text-amber-800 hover:bg-amber-100',
        },
        'Dismiss'
      )
    )
  );
}

export function SchedulingDataProvider({ children }: { children: ReactNode }) {
  const value = useSchedulingDataInternal();

  return createElement(
    SchedulingDataContext.Provider,
    { value },
    value.hasExternalStorageChange
      ? createElement(ExternalStorageChangeBanner, {
          onReload: value.reloadFromStorage,
          onDismiss: value.dismissExternalStorageChange,
        })
      : null,
    value.yamlImportWarnings.length > 0
      ? createElement(YamlImportWarningsBanner, {
          warnings: value.yamlImportWarnings,
          onDismiss: value.dismissYamlImportWarnings,
        })
      : null,
    children
  );
}

export function useSchedulingData() {
  const value = useContext(SchedulingDataContext);
  if (!value) {
    throw new Error('useSchedulingData must be used within SchedulingDataProvider');
  }
  return value;
}
